### ISSUE TITLE
Got 500 (Internal Server Error) when click on courses.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1057]
I made the Canvas LMS update (step-by-step updating). In general Canvas works fine but when I navigate to the course page I got:
https://www.screencast.com/t/eSQiNngeD5z

browser  interprets it as: "500 (Internal Server Error)"

In the Canvas's LMS production log file I see `next:`
```
`[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15] Started GET "/courses" for 109.86.195.77 at 2017-06-16 14:21:59 +0000
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15] Processing by CoursesController#index as HTML
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]
NoMethodError (undefined method `association' for nil:NilClass):
  /home/canvas_new/public_html/app/models/enrollment.rb:707:in `enrollment_state'
  /home/canvas_new/public_html/app/models/enrollment.rb:735:in `block in state_based_on_date'
  /home/canvas_new/public_html/lib/temp_cache.rb:50:in `cache'
  /home/canvas_new/public_html/app/models/enrollment.rb:733:in `state_based_on_date'
  /home/canvas_new/public_html/app/models/enrollment.rb:626:in `state_with_date_sortable'
  /home/canvas_new/public_html/app/controllers/courses_controller.rb:431:in `block (4 levels) in index'
  /home/canvas_new/public_html/app/controllers/courses_controller.rb:431:in `each'
  /home/canvas_new/public_html/app/controllers/courses_controller.rb:431:in `sort_by'
  /home/canvas_new/public_html/app/controllers/courses_controller.rb:431:in `block (3 levels) in index'
  /home/canvas_new/public_html/app/controllers/courses_controller.rb:430:in `each'
  /home/canvas_new/public_html/app/controllers/courses_controller.rb:430:in `block (2 levels) in index'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  /home/canvas_new/public_html/app/controllers/courses_controller.rb:421:in `index'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch'
  /home/canvas_new/public_html/app/controllers/application_controller.rb:399:in `batch_statsd'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  /home/canvas_new/public_html/lib/temp_cache.rb:28:in `enable'
  /home/canvas_new/public_html/app/controllers/application_controller.rb:395:in `enable_request_cache'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  /home/canvas_new/public_html/app/controllers/application_controller.rb:389:in `set_locale'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
  /home/canvas_new/public_html/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /home/canvas_new/public_html/app/middleware/request_throttle.rb:60:in `block in call'
  /home/canvas_new/public_html/app/middleware/request_throttle.rb:274:in `reserve_capacity'
  /home/canvas_new/public_html/app/middleware/request_throttle.rb:55:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
  /home/canvas_new/public_html/app/middleware/request_context_session.rb:25:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
  /home/canvas_new/public_html/app/middleware/load_account.rb:29:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:22:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
  /home/canvas_new/public_html/app/middleware/request_context_generator.rb:49:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
  /home/canvas_new/public_html/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
  /home/canvas_new/public_html/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
  /var/lib/gems/2.4.0/gems/passenger-5.1.4/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /var/lib/gems/2.4.0/gems/passenger-5.1.4/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /var/lib/gems/2.4.0/gems/passenger-5.1.4/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /var/lib/gems/2.4.0/gems/passenger-5.1.4/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /var/lib/gems/2.4.0/gems/passenger-5.1.4/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'


[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15] Created ErrorReport ID 10000000815713
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/errors/_error_form.html.erb (2.1ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/errors/500_message.html.erb within layouts/application (3.1ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered layouts/_head.html.erb (3.5ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/_static_notices.html.erb (0.8ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/_flash_notices.html.erb (0.1ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/svg/_svg_icon_accounts_new_styles.svg (0.0ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/svg/_svg_icon_dashboard.svg (0.0ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/svg/_svg_icon_courses_new_styles.svg (0.0ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/svg/_svg_icon_groups_new_styles.svg (0.0ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/svg/_svg_icon_calendar_new_styles.svg (0.0ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/svg/_svg_icon_inbox.svg (0.0ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered external_tools/_global_nav_menu_items.html.erb (2.9ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/svg/_svg_icon_navtoggle.svg (0.0ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered shared/_new_nav_header.html.erb (13.8ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15] Read fragment views/global_dialogs_render/en/dd766526033b0dc0354ad7f8317409b8 (0.2ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15]   Rendered layouts/_foot.html.erb (9.8ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15] Completed 500 Internal Server Error in 114ms (Views: 57.2ms | ActiveRecord: 9.4ms)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15] [STATSD] (sql_read: 13.00) (sql_write: 1.00) (sql_cache: 3.00) (active_record: 30.00) (cache_read: 32.00) (total: 113.76) (view: 57.20) (db: 9.36)
[bee8864fe2fa39dea51201182bed7b0d 07523bd7-d2e3-426f-b7c9-3410c1fbdb15] [STAT] 833576 833576 0 833576 0.09999999999999964 0.0
[b7475b643597e72bf347279da7b9313f 8a4fdb8a-697a-49f6-98db-359eb5258761] Started GET "/images/thumbnails/4951/oYFCTEm9V4EEcMlQaliey38TrhwSIGFxVBeBWuNL" for 109.86.195.77 at 2017-06-16 14:22:00 +0000
[b7475b643597e72bf347279da7b9313f 8a4fdb8a-697a-49f6-98db-359eb5258761] Processing by FilesController#image_thumbnail as HTML
[b7475b643597e72bf347279da7b9313f 8a4fdb8a-697a-49f6-98db-359eb5258761]   Parameters: {"id"=>"4951", "uuid"=>"oYFCTEm9V4EEcMlQaliey38TrhwSIGFxVBeBWuNL"}
[b7475b643597e72bf347279da7b9313f 8a4fdb8a-697a-49f6-98db-359eb5258761] Redirected to http://elearning.unza.zm/images/thumbnails/show/3632/pi52ACpthMeUKTqRkRUgfw5l6UuIN832h1klKE18
[b7475b643597e72bf347279da7b9313f 8a4fdb8a-697a-49f6-98db-359eb5258761] Completed 302 Found in 14ms (ActiveRecord: 1.3ms)
[b7475b643597e72bf347279da7b9313f 8a4fdb8a-697a-49f6-98db-359eb5258761] [STATSD] (sql_read: 2.00) (sql_write: 0.00) (sql_cache: 0.00) (active_record: 2.00) (cache_read: 1.00) (total: 14.29) (db: 1.30)
[b7475b643597e72bf347279da7b9313f 8a4fdb8a-697a-49f6-98db-359eb5258761] [STAT] 833576 833576 0 833576 0.019999999999999574 0.0
[b7475b643597e72bf347279da7b9313f 09002bbd-697b-41cf-86e7-fe9472f78fd5] Started GET "/images/thumbnails/show/3632/pi52ACpthMeUKTqRkRUgfw5l6UuIN832h1klKE18" for 109.86.195.77 at 2017-06-16 14:22:00 +0000
[b7475b643597e72bf347279da7b9313f 09002bbd-697b-41cf-86e7-fe9472f78fd5] Processing by FilesController#show_thumbnail as HTML
[b7475b643597e72bf347279da7b9313f 09002bbd-697b-41cf-86e7-fe9472f78fd5]   Parameters: {"id"=>"3632", "uuid"=>"pi52ACpthMeUKTqRkRUgfw5l6UuIN832h1klKE18"}
[b7475b643597e72bf347279da7b9313f 09002bbd-697b-41cf-86e7-fe9472f78fd5] Sent file /home/canvas_new/public_html/tmp/files/0000/4951/1462994788_593__profile_thumb.jpg (0.1ms)
[b7475b643597e72bf347279da7b9313f 09002bbd-697b-41cf-86e7-fe9472f78fd5] Completed 200 OK in 16ms (ActiveRecord: 1.3ms)
[b7475b643597e72bf347279da7b9313f 09002bbd-697b-41cf-86e7-fe9472f78fd5] [STATSD] (sql_read: 3.00) (sql_write: 0.00) (sql_cache: 0.00) (active_record: 3.00) (cache_read: 0.00) (total: 15.64) (db: 1.25)
[b7475b643597e72bf347279da7b9313f 09002bbd-697b-41cf-86e7-fe9472f78fd5] [STAT] 833576 833576 0 833576 0.009999999999999787 0.010000000000000009
[bee8864fe2fa39dea51201182bed7b0d 41ee9a8b-b054-402c-8c6c-3e6a65ff6f2c] Started GET "/api/v1/conversations/unread_count" for 109.86.195.77 at 2017-06-16 14:22:01 +0000
[bee8864fe2fa39dea51201182bed7b0d 41ee9a8b-b054-402c-8c6c-3e6a65ff6f2c] Processing by ConversationsController#unread_count as JSON
[bee8864fe2fa39dea51201182bed7b0d 41ee9a8b-b054-402c-8c6c-3e6a65ff6f2c] Completed 200 OK in 14ms (Views: 0.1ms | ActiveRecord: 0.9ms)
[bee8864fe2fa39dea51201182bed7b0d 41ee9a8b-b054-402c-8c6c-3e6a65ff6f2c] [STATSD] (sql_read: 2.00) (sql_write: 0.00) (sql_cache: 0.00) (active_record: 2.00) (cache_read: 0.00) (total: 14.02) (view: 0.10) (db: 0.94)
[bee8864fe2fa39dea51201182bed7b0d 41ee9a8b-b054-402c-8c6c-3e6a65ff6f2c] [STAT] 833576 833576 0 833576 0.009999999999999787 0.0
```
`Environment:
Canvas LMS - origin/stable/2017-06-03
bundler - 1.14.6
ruby - 2.4.1p111
nodejs - v6.11.0
gem - 2.6.11

Would be glad for any help.

**Comment by simonista** [comment]
Hey @ally1,  I'm not sure exactly what would have caused this, but maybe a migration didn't work right.  I think you should be able to fix it by opening a rails console (`script/rails console production` in your rails root dir) and running: `Enrollment.find_each{ |e| e.create_enrollment_state }`.  That should ensure that every enrollment object has an associated cached state object associated with it.

**Comment by ally1** [comment]
Hello @simonista,

Thanks! It is some kind of magic!  The problem was resolved. 
If you get any time at all can you please explain ( for the audience) why it works? If not, thank you anyways.

**Comment by simonista** [comment]
Well, the error is:

```
NoMethodError (undefined method `association' for nil:NilClass):
  /home/canvas_new/public_html/app/models/enrollment.rb:707:in `enrollment_state'
```

And if you look at https://github.com/instructure/canvas-lms/blob/stable/app/models/enrollment.rb#L707, the line previous is trying to load the cached enrollment state, which it expects to always exist, but for some reason yours did not.  Enrollment state is a complicated calculation dealing with course, enrollment, and term start and end times as well as explicit workflow states, so for performance reasons we cache the computation in a separate table.  In the past we have run migrations to create them for all existing enrollment objects (db/migrate/20160517153405_build_enrollment_states.rb), and https://github.com/instructure/canvas-lms/blob/stable/app/models/enrollment.rb#L67 should ensure they exist for all new enrollment objects, but for whatever reason you were trying to access an enrollment that didn't have one.

**Comment by ally1** [comment]
Awesome!  Thank you again!
