### ISSUE TITLE
PopulateScoresTable db migrate aborts if GradingPeriodGroup is missing method

### ISSUE THREAD

**Issue by shawniverson** [instructure/canvas-lms#1066]
### Summary:
If a GradingPeriodGroup is missing the weighted method, rake will abort during a db migration during PopulateScoresTable task.

### Steps to reproduce:

 1.  RAILS_ENV=production  bundle exec rake db:migrate

### Expected behavior:
db:migrate should continue

### Additional notes:

A workaround
lib/grade_calculator.rb line 189:
```
@compute_from_weighted_periods = grading_periods_for_course.first.grading_period_group.try(:weighted?)
```

Rake aborted message
```
==  PopulateScoresTable: migrating ============================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `weighted?' for #<GradingPeriodGroup:0x0000000cc41ee8>
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activemodel-4.2.8/lib/active_model/attribute_methods.rb:433:in `method_missing'
/var/canvas/lib/grade_calculator.rb:189:in `compute_course_scores_from_weighted_grading_periods?'
/var/canvas/lib/grade_calculator.rb:126:in `compute_scores_for_user'
/var/canvas/lib/grade_calculator.rb:99:in `block in compute_scores_and_group_sums_for_batch'
/var/canvas/lib/grade_calculator.rb:97:in `map'
/var/canvas/lib/grade_calculator.rb:97:in `compute_scores_and_group_sums_for_batch'
/var/canvas/lib/grade_calculator.rb:77:in `block in compute_scores'
/var/canvas/lib/grade_calculator.rb:76:in `each'
/var/canvas/lib/grade_calculator.rb:76:in `each_slice'
/var/canvas/lib/grade_calculator.rb:76:in `compute_scores'
/var/canvas/lib/grade_calculator.rb:85:in `compute_and_save_scores'
/var/canvas/lib/grade_calculator.rb:242:in `calculate_course_score'
/var/canvas/lib/grade_calculator.rb:87:in `compute_and_save_scores'
/var/canvas/lib/data_fixup/populate_scores_table.rb:52:in `block (2 levels) in run'
/var/canvas/lib/data_fixup/populate_scores_table.rb:39:in `each'
/var/canvas/lib/data_fixup/populate_scores_table.rb:39:in `block in run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block in find_each'
/var/canvas/config/initializers/active_record.rb:702:in `block (2 levels) in find_in_batches_with_cursor'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:70:in `block in unscoped'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/scoping/default.rb:33:in `block in unscoped'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:302:in `scoping'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/scoping/default.rb:33:in `unscoped'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:68:in `unscoped'
/var/canvas/config/initializers/active_record.rb:698:in `block in find_in_batches_with_cursor'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:56:in `transaction'
/var/canvas/config/initializers/active_record.rb:692:in `find_in_batches_with_cursor'
/var/canvas/config/initializers/active_record.rb:630:in `block in find_in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/relation.rb:77:in `activate'
/var/canvas/config/initializers/active_record.rb:630:in `find_in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:50:in `find_each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/querying.rb:9:in `find_each'
/var/canvas/lib/data_fixup/populate_scores_table.rb:21:in `run'
/var/canvas/db/migrate/20161220003113_populate_scores_table.rb:22:in `up'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:420:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:56:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1246:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/database_server.rb:99:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:71:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:372:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:584:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:86:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:583:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:370:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:366:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:66:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/database_server.rb:99:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:63:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/shackles.rb:22:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:62:in `block in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
NoMethodError: undefined method `weighted?' for #<GradingPeriodGroup:0x0000000cc41ee8>
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activemodel-4.2.8/lib/active_model/attribute_methods.rb:433:in `method_missing'
/var/canvas/lib/grade_calculator.rb:189:in `compute_course_scores_from_weighted_grading_periods?'
/var/canvas/lib/grade_calculator.rb:126:in `compute_scores_for_user'
/var/canvas/lib/grade_calculator.rb:99:in `block in compute_scores_and_group_sums_for_batch'
/var/canvas/lib/grade_calculator.rb:97:in `map'
/var/canvas/lib/grade_calculator.rb:97:in `compute_scores_and_group_sums_for_batch'
/var/canvas/lib/grade_calculator.rb:77:in `block in compute_scores'
/var/canvas/lib/grade_calculator.rb:76:in `each'
/var/canvas/lib/grade_calculator.rb:76:in `each_slice'
/var/canvas/lib/grade_calculator.rb:76:in `compute_scores'
/var/canvas/lib/grade_calculator.rb:85:in `compute_and_save_scores'
/var/canvas/lib/grade_calculator.rb:242:in `calculate_course_score'
/var/canvas/lib/grade_calculator.rb:87:in `compute_and_save_scores'
/var/canvas/lib/data_fixup/populate_scores_table.rb:52:in `block (2 levels) in run'
/var/canvas/lib/data_fixup/populate_scores_table.rb:39:in `each'
/var/canvas/lib/data_fixup/populate_scores_table.rb:39:in `block in run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block in find_each'
/var/canvas/config/initializers/active_record.rb:702:in `block (2 levels) in find_in_batches_with_cursor'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:70:in `block in unscoped'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/scoping/default.rb:33:in `block in unscoped'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation.rb:302:in `scoping'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/scoping/default.rb:33:in `unscoped'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:68:in `unscoped'
/var/canvas/config/initializers/active_record.rb:698:in `block in find_in_batches_with_cursor'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:56:in `transaction'
/var/canvas/config/initializers/active_record.rb:692:in `find_in_batches_with_cursor'
/var/canvas/config/initializers/active_record.rb:630:in `block in find_in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/relation.rb:77:in `activate'
/var/canvas/config/initializers/active_record.rb:630:in `find_in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:50:in `find_each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/querying.rb:9:in `find_each'
/var/canvas/lib/data_fixup/populate_scores_table.rb:21:in `run'
/var/canvas/db/migrate/20161220003113_populate_scores_table.rb:22:in `up'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:420:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/active_record/base.rb:56:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1044:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1246:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:72:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/database_server.rb:99:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:71:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:372:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:584:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:86:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:583:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:370:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/app/models/switchman/shard_internal.rb:366:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:66:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/database_server.rb:99:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:63:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/switchman/shackles.rb:22:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.9.14/lib/tasks/switchman.rake:62:in `block in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by shawniverson** [comment]
Old news, code has moved forward.
