### ISSUE TITLE
Compiling assets error (canvas_quizzes)

### ISSUE THREAD

**Issue by newperson1746** [instructure/canvas-lms#1135]
### Summary:
When I run RAILS_ENV=production bundle exec rake canvas:compile_assets after doing npm install, the following error occurs: 
```
Error: Cannot find module '/usr/local/canvas/client_apps/Cellar/yarn/0.27.5/bin/yarn.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
INSTALL FAILURE:
rake aborted!
Package installation failure for client app canvas_quizzes
/usr/local/canvas/lib/tasks/js.rake:19:in `block (4 levels) in <top (required)>'
/usr/local/canvas/lib/tasks/js.rake:12:in `chdir'
/usr/local/canvas/lib/tasks/js.rake:12:in `block (3 levels) in <top (required)>'
/usr/local/canvas/lib/tasks/js.rake:9:in `each'
/usr/local/canvas/lib/tasks/js.rake:9:in `block (2 levels) in <top (required)>'
/usr/local/canvas/lib/tasks/canvas.rake:75:in `block (2 levels) in <top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => js:build_client_apps
(See full trace by running task with --trace)
```
### Steps to reproduce:

 1. Download canvas
 2. run npm install
 3. run the bundle exec rake command

### Expected behavior:
There are no errors, and the command succeeds.
### Additional notes:
Why would it be searching for yarn inside the client_apps folder? I am running macOS 10.13 High Sierra with ruby 2.4.2p198 from homebrew, node.js 6.11.4 from their website and manually downgraded yarn to 0.27.5 (apparently anything higher than 0.27.5 causes errors) It should be searching for yarn in /usr/local/cellar/yarn/0.27.5, not in the directory of canvas_quizzes.

**Comment by newperson1746** [comment]
I just tried the beta branch and I get a different error when running the same command:
```
1: production:public
==  RegenerateBrandFilesBasedOnNewDefaultsPredeploy: migrating ================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

you need to run `gulp rev` first
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:102:in `load_gulp_data_if_needed'
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:35:in `gulp_manifest'
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:80:in `revved_url_for'
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:90:in `url_for'
/usr/local/canvas/config/initializers/revved_asset_urls.rb:30:in `path_to_asset'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/helpers/asset_url_helper.rb:311:in `image_path'
/usr/local/canvas/lib/brandable_css.rb:115:in `block in things_that_go_into_defaults_md5'
/usr/local/canvas/lib/brandable_css.rb:111:in `each'
/usr/local/canvas/lib/brandable_css.rb:111:in `each_with_object'
/usr/local/canvas/lib/brandable_css.rb:111:in `things_that_go_into_defaults_md5'
/usr/local/canvas/lib/brandable_css.rb:151:in `default_variables_md5_without_migration_check'
/usr/local/canvas/lib/brandable_css.rb:124:in `migration_version'
/usr/local/canvas/lib/brandable_css.rb:132:in `block in check_if_we_need_to_create_a_db_migration'
/usr/local/canvas/lib/brandable_css.rb:129:in `each'
/usr/local/canvas/lib/brandable_css.rb:129:in `check_if_we_need_to_create_a_db_migration'
/usr/local/canvas/lib/brandable_css.rb:145:in `default_variables_md5'
/usr/local/canvas/app/models/brand_config.rb:117:in `json_file'
/usr/local/canvas/app/models/brand_config.rb:149:in `save_json_file!'
/usr/local/canvas/app/models/brand_config.rb:201:in `save_all_files!'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:59:in `block (2 levels) in find_each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:59:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:59:in `block in find_each'
/usr/local/canvas/config/initializers/active_record.rb:716:in `block (2 levels) in find_in_batches_with_cursor'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:58:in `block in unscoped'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/scoping/default.rb:35:in `block in unscoped'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation.rb:351:in `scoping'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/scoping/default.rb:35:in `unscoped'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:56:in `unscoped'
/usr/local/canvas/config/initializers/active_record.rb:712:in `block in find_in_batches_with_cursor'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:44:in `transaction'
/usr/local/canvas/config/initializers/active_record.rb:706:in `find_in_batches_with_cursor'
/usr/local/canvas/config/initializers/active_record.rb:640:in `block in find_in_batches'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/relation.rb:74:in `activate'
/usr/local/canvas/config/initializers/active_record.rb:640:in `find_in_batches'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:58:in `find_each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/querying.rb:9:in `find_each'
/usr/local/canvas/db/migrate/75072935522965904110132_regenerate_brand_files_based_on_new_defaults_predeploy.rb:28:in `up'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:792:in `exec_migration'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:771:in `migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:601:in `migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:951:in `migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1232:in `block in execute_migration_in_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1300:in `block in ddl_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:44:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1231:in `execute_migration_in_transaction'
/usr/local/canvas/config/initializers/active_record.rb:1215:in `execute_migration_in_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1203:in `block in migrate_without_lock'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1202:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1202:in `migrate_without_lock'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1150:in `block in migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1319:in `with_advisory_lock'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1150:in `migrate'
/usr/local/canvas/lib/tasks/canvas.rake:157:in `block (3 levels) in <top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:72:in `block (6 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:72:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:72:in `block (5 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/database_server.rb:99:in `unshackle'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:71:in `block (4 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:372:in `block (2 levels) in with_each_shard'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:584:in `block in activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:86:in `activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:583:in `activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:370:in `block in with_each_shard'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:366:in `with_each_shard'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:66:in `block (3 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/database_server.rb:99:in `unshackle'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:63:in `block (2 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/shackles.rb:22:in `activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:62:in `block in shardify_task'
/usr/local/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
you need to run `gulp rev` first
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:102:in `load_gulp_data_if_needed'
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:35:in `gulp_manifest'
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:80:in `revved_url_for'
/usr/local/canvas/lib/canvas/cdn/rev_manifest.rb:90:in `url_for'
/usr/local/canvas/config/initializers/revved_asset_urls.rb:30:in `path_to_asset'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/helpers/asset_url_helper.rb:311:in `image_path'
/usr/local/canvas/lib/brandable_css.rb:115:in `block in things_that_go_into_defaults_md5'
/usr/local/canvas/lib/brandable_css.rb:111:in `each'
/usr/local/canvas/lib/brandable_css.rb:111:in `each_with_object'
/usr/local/canvas/lib/brandable_css.rb:111:in `things_that_go_into_defaults_md5'
/usr/local/canvas/lib/brandable_css.rb:151:in `default_variables_md5_without_migration_check'
/usr/local/canvas/lib/brandable_css.rb:124:in `migration_version'
/usr/local/canvas/lib/brandable_css.rb:132:in `block in check_if_we_need_to_create_a_db_migration'
/usr/local/canvas/lib/brandable_css.rb:129:in `each'
/usr/local/canvas/lib/brandable_css.rb:129:in `check_if_we_need_to_create_a_db_migration'
/usr/local/canvas/lib/brandable_css.rb:145:in `default_variables_md5'
/usr/local/canvas/app/models/brand_config.rb:117:in `json_file'
/usr/local/canvas/app/models/brand_config.rb:149:in `save_json_file!'
/usr/local/canvas/app/models/brand_config.rb:201:in `save_all_files!'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:59:in `block (2 levels) in find_each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:59:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:59:in `block in find_each'
/usr/local/canvas/config/initializers/active_record.rb:716:in `block (2 levels) in find_in_batches_with_cursor'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:58:in `block in unscoped'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/scoping/default.rb:35:in `block in unscoped'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation.rb:351:in `scoping'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/scoping/default.rb:35:in `unscoped'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:56:in `unscoped'
/usr/local/canvas/config/initializers/active_record.rb:712:in `block in find_in_batches_with_cursor'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:44:in `transaction'
/usr/local/canvas/config/initializers/active_record.rb:706:in `find_in_batches_with_cursor'
/usr/local/canvas/config/initializers/active_record.rb:640:in `block in find_in_batches'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/relation.rb:74:in `activate'
/usr/local/canvas/config/initializers/active_record.rb:640:in `find_in_batches'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/batches.rb:58:in `find_each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/querying.rb:9:in `find_each'
/usr/local/canvas/db/migrate/75072935522965904110132_regenerate_brand_files_based_on_new_defaults_predeploy.rb:28:in `up'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:792:in `exec_migration'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:771:in `migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:601:in `migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:951:in `migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1232:in `block in execute_migration_in_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1300:in `block in ddl_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/active_record/base.rb:44:in `transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1300:in `ddl_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1231:in `execute_migration_in_transaction'
/usr/local/canvas/config/initializers/active_record.rb:1215:in `execute_migration_in_transaction'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1203:in `block in migrate_without_lock'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1202:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1202:in `migrate_without_lock'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1150:in `block in migrate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1319:in `with_advisory_lock'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/migration.rb:1150:in `migrate'
/usr/local/canvas/lib/tasks/canvas.rake:157:in `block (3 levels) in <top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:72:in `block (6 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:72:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:72:in `block (5 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/database_server.rb:99:in `unshackle'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:71:in `block (4 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:372:in `block (2 levels) in with_each_shard'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:584:in `block in activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:86:in `activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:583:in `activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:370:in `block in with_each_shard'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/relation/delegation.rb:38:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/app/models/switchman/shard_internal.rb:366:in `with_each_shard'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:66:in `block (3 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/database_server.rb:99:in `unshackle'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:63:in `block (2 levels) in shardify_task'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/switchman/shackles.rb:22:in `activate'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.3/lib/tasks/switchman.rake:62:in `block in shardify_task'
/usr/local/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.3/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate:predeploy
(See full trace by running task with --trace)

```
I'm not sure why the error changed this time.

**Comment by omarkhan** [comment]
Hi @newperson1746. We're using github issues for bugs only. For setup and configuration issues like this, can you try asking on [the mailing list](http://groups.google.com/group/canvas-lms-users) or [IRC](http://webchat.freenode.net/?channels=canvas-lms)? Thanks.

**Comment by BLTSandwich** [comment]
This is occurring for me too, on stable, master, and beta. I don't think this is config related,

**Comment by newperson1746** [comment]
I believe that I found the issue. In the "Production Start" guide, it guides you through the commands that you should run to get canvas running. It turns out that the order of the commands is very important as well. Just to refresh your memory, the core commands, in order, are:
```
bundle install --path vendor/bundle
RAILS_ENV=production bundle exec rake db:initial_setup
yarn install
RAILS_ENV=production bundle exec rake canvas:compile_assets
RAILS_ENV=production bundle exec rake brand_configs:generate_and_upload_all
```
I'm fairly certain that many people attempt to run yarn install (npm is no longer recommended) out of order. The order the commands are run is very important. I git cloned the latest beta branch and master and both successfully compiled with those commands. (and copying my config folder from my actual, already running canvas installation that I have separate, but that was just to save time) I think that adding a warning to the Production Start guide that explains that the order of the commands is important would resolve this issue, but since I cannot edit that, I will leave the issue open. (until a permanent solution is hopefully found)

**Comment by simonista** [comment]
Can you say more about what got run out of order?
