### ISSUE TITLE
No implicit conversion of nil into String Error.

### ISSUE THREAD

**Issue by ally1** [instructure/canvas-lms#1141]
### Summary:

Hi Canvas LMS community,
The Canvas LMS is working fine with the exception of few pages that throws "Page error".

### Steps to reproduce:

 1. Log ino Canvas LMS;
 2. Navigate to Admin > Site Admin > Settings
 3. The page returns 'Page error' see screenshot - https://www.screencast.com/t/jzcv9typvhvn

### Additional notes:
- Ubuntu 14.04.5 LTS
- Ruby 2.4.2p198
- Bundler version 1.13.6
- Node v6.11.3
- yarn "0.27.5"

Error from log/production.log:
```
[306858bf8c3659a75627b66c43c65080 4c1e5f78-e9f8-4539-b52f-0d209ed01cf3]
TypeError (no implicit conversion of nil into String):
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jws.rb:71:in `digest'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jws.rb:71:in `sign'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jws.rb:16:in `sign!'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jwt.rb:40:in `sign'
  /home/canvas/public_html/lib/canvas/security.rb:134:in `create_encrypted_jwt'
  /home/canvas/public_html/lib/canvas/security/services_jwt.rb:71:in `generate'
  /home/canvas/public_html/lib/canvas/security/services_jwt.rb:95:in `for_user'
  /home/canvas/public_html/lib/services/rich_content.rb:26:in `env_for'
  /home/canvas/public_html/app/controllers/application_controller.rb:173:in `rce_js_env'
  /home/canvas/public_html/app/controllers/accounts_controller.rb:1157:in `rich_content_service_config'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `block in call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `each'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch'
  /home/canvas/public_html/app/controllers/application_controller.rb:411:in `batch_statsd'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /home/canvas/public_html/lib/temp_cache.rb:28:in `enable'
  /home/canvas/public_html/app/controllers/application_controller.rb:407:in `enable_request_cache'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /home/canvas/public_html/app/controllers/application_controller.rb:401:in `set_locale'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126:in `process'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:30:in `process'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190:in `dispatch'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262:in `dispatch'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:39:in `block in serve'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `each'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `serve'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:725:in `call'
  /home/canvas/public_html/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
  /home/canvas/public_html/app/middleware/request_throttle.rb:60:in `block in call'
  /home/canvas/public_html/app/middleware/request_throttle.rb:272:in `reserve_capacity'
  /home/canvas/public_html/app/middleware/request_throttle.rb:55:in `call'
  /home/canvas/public_html/app/middleware/request_context_session.rb:25:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
  /home/canvas/public_html/app/middleware/load_account.rb:29:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:26:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
  /home/canvas/public_html/app/middleware/request_context_generator.rb:49:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  /home/canvas/public_html/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `public_send'
  /home/canvas/public_html/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `method_missing'
  /var/lib/gems/2.4.0/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /var/lib/gems/2.4.0/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /var/lib/gems/2.4.0/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /var/lib/gems/2.4.0/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /var/lib/gems/2.4.0/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

Thanks in an advises.

**Comment by omarkhan** [comment]
Thanks for this @ally1. Looks like you might be missing an `ENCRYPTION_KEY` environment variable.

**Comment by simonista** [comment]
Closing due to lack of response, feel free to reopen if you're still having issues!

**Comment by moorecp** [comment]
I'm having the same issue. This happened after we updated to stable/2017-11-18 after having a working setup from a July build.

I have `encryption_key` defined in my `config/security.yml`, but I'm getting the same stack trace as @ally1 . I'm not sure if it's directly related to rich_content stuff, but I don't have a `dynamic_settings.yml` in my staging/production environments. I'm open to suggestions as to how to fix this.

**Comment by simonista** [comment]
Sounds like you have the `rich_content_service_high_risk` enabled.  Try this in a rails console:

```ruby
Setting.where(name: 'rich_content_service_enabled').delete_all
FeatureFlag.where(feature: 'rich_content_service_high_risk').delete_all
```

**Comment by moorecp** [comment]
Yup. I noticed that shortly after I posted my question. I disabled it via 
```ruby
account.disable_feature!(:rich_content_service_high_risk)
```
but hadn't made it back to this ticket. I have no idea what that is or how the users enabled it, but it was only in staging and is off now. Thanks.

**Comment by ally1** [comment]
Hello Canvas LMS community,

Unfortunately I can not test the above method because of the re-installing the Canvas LMS, but in any case, it can be helpful for others to resolve such kind of issue.

Thanks.

**Comment by ally1** [comment]
Hello @simonista & @moorecp 

I encountered the same issue but on another Canvas LMS instance.
@simonista I used your method but it did not help.
@moorecp Can you please explain how exactly did you disable it? Via some config file, rails console, PostgreSQL ? 

Lookig for your reply.

**Comment by simonista** [comment]
Is it the same stacktrace? Specifically these methods:

```
  /home/canvas/public_html/lib/services/rich_content.rb:26:in `env_for'
  /home/canvas/public_html/app/controllers/application_controller.rb:173:in `rce_js_env'
  /home/canvas/public_html/app/controllers/accounts_controller.rb:1157:in `rich_content_service_config'
```

**Comment by ally1** [comment]
Hi @simonista 

Yes, the stacktrace is looking like:

```
[bf2a0692cb8e5066c6d5349e1b0d322c 78039f19-a638-4043-95eb-f56dd9837c37]
TypeError (no implicit conversion of nil into String):
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jws.rb:71:in `digest'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jws.rb:71:in `sign'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jws.rb:16:in `sign!'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/json-jwt-1.7.2/lib/json/jwt.rb:40:in `sign'
  /home/canvas/lib/canvas/security.rb:134:in `create_encrypted_jwt'
  /home/canvas/lib/canvas/security/services_jwt.rb:71:in `generate'
  /home/canvas/lib/canvas/security/services_jwt.rb:95:in `for_user'
  /home/canvas/lib/services/rich_content.rb:26:in `env_for'
  /home/canvas/app/controllers/application_controller.rb:177:in `rce_js_env'
  /home/canvas/app/controllers/accounts_controller.rb:1169:in `rich_content_service_config'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `block in call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `each'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch'
  /home/canvas/app/controllers/application_controller.rb:425:in `batch_statsd'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /home/canvas/lib/temp_cache.rb:28:in `enable'
  /home/canvas/app/controllers/application_controller.rb:421:in `enable_request_cache'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /home/canvas/app/controllers/application_controller.rb:415:in `set_locale'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126:in `process'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:30:in `process'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190:in `dispatch'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262:in `dispatch'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:39:in `block in serve'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `each'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `serve'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:725:in `call'
  /home/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
  /home/canvas/app/middleware/request_throttle.rb:60:in `block in call'
  /home/canvas/app/middleware/request_throttle.rb:272:in `reserve_capacity'
  /home/canvas/app/middleware/request_throttle.rb:55:in `call'
  /home/canvas/app/middleware/request_context_session.rb:25:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
  /home/canvas/app/middleware/load_account.rb:29:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:26:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
  /home/canvas/app/middleware/request_context_generator.rb:49:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  /home/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `public_send'
  /home/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```

**Comment by simonista** [comment]
Yeah, that's the same thing, I'm not sure why my suggestion wouldn't have worked... maybe try clearing your redis cache? (I probably should have suggested `.destroy_all` rather than `.delete_all`)

**Comment by ally1** [comment]
Hi @simonista 

I clear the /var/lib/redis/dump.rdb and restarted the redis and the problem was resolved.
Thank you so much for the help!

Regards
Ally L.

**Comment by noriando** [comment]
None of above fix issue to my case.
Finally clearing redis cash made it work.

redis-cli flushall

**Comment by pouxol** [comment]
Hi,

I have Canvas running on an AWS Machine and I changed the Rich Content Setting yesterday in the front-end of Canvas.
Now I can not enter the settings-page at all -> Page Error.

I looked at the logs and I have the same errors as described here.

I don't know how to change the setting again though, since I don't have access to the front-end settings anymore.

I have access to all files via FileZilla and PuTTY.

Can someone help me please?
Where can I disable this Rich Content Setting? (Admin > Settings > Feature Options > Rich Content Editor Sidebar Enhancements)

I tried `cp config/dynamic_settings.yml.example config/dynamic_settings.yml` already.

Thank you.

**Comment by 3arrows** [comment]
Try this.
Connect to the PostgreSQL server of your Canvas site. And then,

SELECT * FROM feature_flags WHERE feature like '%rich_content_service%';

If the field 'state' is as 'on', update the value with the text 'off' as below.

UPDATE feature_flags SET state = 'off' WHERE feature = 'rich_content_service';
(I'm not sure that the 'feature' value is in your database. 'rich_content_service_*' )

**Comment by pouxol** [comment]
Thank you for your help.

I connected to the psql using putty
https://docs.bitnami.com/bch/apps/canvaslms/get-started/connect-postgresql/

When I try the select it gives me following error:
ERROR: relation "feature_flags" does not exist

Am I connected to the right psql? Am I using the right user?

**Comment by 3arrows** [comment]
Did you try to execute a command "redis-cli flushdb" or "flushall" ?

https://redis.io/commands/flushdb

I think that removing a Redis dump file is not required in this case.
But presumably Redis still has cached old status.

**Comment by pouxol** [comment]
Thank you 3arrows. I really appreciate your help.

Can I enter the code like that into PuTTY or do I need to connect to redis or open redis somehow?

**Comment by 3arrows** [comment]
I'm not sure about bitnami's Canvas enviroment. But, maybe you could do that with redis-cli utility like as below,

https://docs.bitnami.com/installer/apps/canvaslms/get-started/connect/

After connecting your Redis, just type a command.

flushdb
 "or"
flushall

Not mind one way or the other.

**Comment by pouxol** [comment]
Big Thanks to you 3arrows.

That helped a lot.

I had to configure the redis.conf since flushall and flushdb were disabled. 
But now everything works fine again.
