### ISSUE TITLE
Error starting application for production start

### ISSUE THREAD

**Issue by karasjoh000** [instructure/canvas-lms#1181]
### Summary:
ran **sudo /etc/init.d/canvas_init start** and received: 
`/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- bundler/setup (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
	from /var/canvas/script/delayed_job:7:in '<main>'` 
### Steps to reproduce:

 1. sudo /etc/init.d/canvas_init start

### Expected behavior:
should start the app. 

### Additional notes:

**Comment by karasjoh000** [comment]
used rvm before, then Unistalled rvm. 
**Ran:** 
ruby-install --system ruby 2.4.0
chruby ruby-2.4.0
gem update --system (in app dir)
bundle install (in app dir) 

Start working after that
