### ISSUE TITLE
CORS issues when calling canvas apis from an LTI app

### ISSUE THREAD

**Issue by lichenglu** [instructure/canvas-lms#1183]
### Summary:
Hi, I am having issues calling the apis of canvas from an LTI app. But I was able to make the requests successfully when using `postman`.

The endpoint I called is `/api/v1/courses/${courseId}/groups`, with `Bearer` token in the header granted through canvas oauth.

Here are the headers I sent along with the request in the LTI app:

```
headers: {
                'Access-Control-Allow-Origin': 'http://ltidemo.oii.test:8081',
                'Accept': 'application/json',
                'Authorization': `Bearer ${accessToken}`
 }
```

The `lti app` is running on localhost with port 8081, and `canvas` is running on localhost with port 3000

### Steps to reproduce:

 1. Get an access token through canvas oauth
 2. Use the token as authorization header, then send a `GET` request `/api/v1/courses/${courseId}/groups`
 3. Get errors from the browser console, saying
```
Failed to load http://ltidemo.oii.test:3000/api/v1/courses/1/groups?only_own_groups=false: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ltidemo.oii.test:8081' is therefore not allowed access. The response had HTTP status code 404.
```
Here is the error logs from *canvas server*:

```
ActionController::RoutingError (No route matches [OPTIONS] "/api/v1/courses/1/groups"):

app/middleware/request_context_generator.rb:49:in `call'
app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  Rendering /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendered collection of /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/routes/_route.html.erb [2116 times] (441.0ms)
  Rendered /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/routes/_table.html.erb (16.1ms)
  Rendering /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.5ms)
  Rendered /Users/cl38824/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (613.5ms)
```

### Expected behavior:
Pass the preflight check of cors, and receive some kind of response

Thank you in advance!

**Comment by chiragpurohit71085** [comment]
What's the solution? I am facing same issue.

**Comment by karendolan** [comment]
@lichenglu did you solve this by changing your corsRules file on your Canvas server or AWS S3? 

For example, did you have to add a `<AllowedMethod>OPTIONS</AllowedMethod>` ,  a ` <AllowedOrigin>*</AllowedOrigin>` and/or a `<AllowedHeader>*</AllowedHeader>`  like below?

```
<CORSConfiguration>
 <CORSRule>
  ... PUT, DELETE, POST, etc
  ....
 <CORSRule>
   <AllowedMethod>GET</AllowedMethod>
   <AllowedMethod>OPTIONS</AllowedMethod>
   <AllowedOrigin>*</AllowedOrigin>
   <AllowedHeader>*</AllowedHeader>
 </CORSRule>
</CORSConfiguration>
```

**Comment by karendolan** [comment]
Related issue for uploaded Canvas image files on S3 from the Safari browser https://github.com/jquery/jquery/issues/4788
