### ISSUE TITLE
Error during upgrade: you need to upgrade yarn

### ISSUE THREAD

**Issue by n3rve** [instructure/canvas-lms#1203]
### Summary:
I am trying to upgrade a Canvas LMS instance which was last upgraded about 3 months ago. I've successfully git pulled and bundle updated. (`bundle install` returned an error). I'm stuck on the `yarn install` stage. 

```
root@ip-172-31-7-233:/var/www/canvas_lms# yarn --version
1.0.1
------
root@ip-172-31-7-233:/var/www/canvas_lms# yarn install
yarn install v1.0.1
$ script/gem_npm install
[eval]:1
if (!(require('child_process').execSync('yarn --version').toString().match(require('./package.json').engines.yarn))) throw new Error('you need to upgrade yarn')
                                                                                                                   
Error: you need to upgrade yarn
    at [eval]:1:124
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:347:27)
    at run (bootstrap_node.js:122:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:121:9)
    at bootstrap_node.js:496:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I've tried downgrading yarn as well, and get the same error above.

```
Need to get 0 B/622 kB of archives.
After this operation, 111 kB disk space will be freed.
Do you want to continue? [Y/n] y
dpkg: warning: downgrading yarn from 1.0.1-1 to 0.27.5-1
(Reading database ... 72303 files and directories currently installed.)
Preparing to unpack .../archives/yarn_0.27.5-1_all.deb ...
Unpacking yarn (0.27.5-1) over (1.0.1-1) ...
Setting up yarn (0.27.5-1) ...
```

### Steps to reproduce:

 1. Upgrade a Canvas LMS instance that was last upgraded 3 months ago.
 2. `git reset --hard`, `git fetch && git pull origin stable`, `bundle update`
 3. `yarn install`

### Expected behavior:
Packages should be installed.

**Comment by djbender** [comment]
our [current version](https://github.com/instructure/canvas-lms/blob/56f866e9595574ab02fe7b8a869a61cffe258e0e/package.json#L7) of yarn is `1.3.2`. Can you upgrade to that version?

**Comment by n3rve** [comment]
Thanks @djbender. After upgrading to 1.3.2, yarn installed the dependencies successfully.
