### ISSUE TITLE
NameError (uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer

### ISSUE THREAD

**Issue by n3rve** [instructure/canvas-lms#1207]
### Summary:

One of our Canvas LMS instances was upgraded recently, although I had a few migration errors which were resolved with help from some contributors here. I woke up to 500 errors today and started investigating. I found that delayed_jobs (canvas_init) wasn't running which I restarted.

I also noticed the logs mentioned Redis. I checked and confirmed Redis was running but the dump had grown to 240MB+. I entered the redis cli and flushed it, restarted Apache, Canvas_init and Redis and services appear to be running fine and I no longer get the 500 error. I'm just curious to find out what happened. Can anyone make anything out of these logs?

### Logs:

```
[- 048caf04-5e32-42e4-84c4-abc00c65d8d9] Created ErrorReport ID 10000001270986
[- 048caf04-5e32-42e4-84c4-abc00c65d8d9] Created ErrorReport ID 10000001270987
[- 048caf04-5e32-42e4-84c4-abc00c65d8d9] Completed 500 Internal Server Error in 43ms (ActiveRecord: 4.7ms)
[- 048caf04-5e32-42e4-84c4-abc00c65d8d9] [STATSD] (sql_read: 1.00) (sql_write: 2.00) (sql_cache: 0.00) (active_record: 3.00) (cache_read: 2.00) (total: 43.36) (db: 4.68)
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] Started GET "/" for 13.76.241.210 at 2018-01-15 09:41:48 +0000
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668]   
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] NameError (uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer
Did you mean?  Integer):
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668]   
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] lib/multi_cache.rb:82:in `fetch'
app/models/account.rb:1211:in `block in find_cached'
app/models/account.rb:1210:in `find_cached'
app/models/account.rb:1229:in `block in get_special_account'
app/models/account.rb:1224:in `get_special_account'
app/models/account.rb:1184:in `default'
app/middleware/load_account.rb:32:in `default_domain_root_account'
app/middleware/load_account.rb:25:in `call'
app/middleware/request_context_generator.rb:49:in `call'
app/middleware/prevent_non_multipart_parse.rb:32:in `call'
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] Processing by ApplicationController#rescue_action_dispatch_exception as HTML
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] 
NameError (uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer
Did you mean?  Integer):
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/inflector/methods.rb:283:in `const_get'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/inflector/methods.rb:283:in `block in constantize'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/inflector/methods.rb:266:in `each'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/inflector/methods.rb:266:in `inject'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/inflector/methods.rb:266:in `constantize'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/core_ext/marshal.rb:8:in `rescue in load'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/core_ext/marshal.rb:4:in `load'
  /var/www/canvas_lms/gems/canvas_ext/lib/canvas_ext/marshal.rb:25:in `load'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/bundler/gems/redis-store-b2ffdf5d183d/lib/redis/store/serialization.rb:43:in `_unmarshal'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/bundler/gems/redis-store-b2ffdf5d183d/lib/redis/store/serialization.rb:17:in `get'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/bundler/gems/redis-store-b2ffdf5d183d/lib/redis/store/namespace.rb:23:in `block in get'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/bundler/gems/redis-store-b2ffdf5d183d/lib/redis/store/namespace.rb:89:in `namespace'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/bundler/gems/redis-store-b2ffdf5d183d/lib/redis/store/namespace.rb:23:in `get'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/redis-activesupport-5.0.4/lib/active_support/cache/redis_store.rb:260:in `block in read_entry'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/redis-activesupport-5.0.4/lib/active_support/cache/redis_store.rb:242:in `with'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/redis-activesupport-5.0.4/lib/active_support/cache/redis_store.rb:260:in `read_entry'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache.rb:291:in `block in fetch'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache.rb:562:in `block in instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache.rb:562:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache.rb:290:in `fetch'
  /var/www/canvas_lms/lib/multi_cache.rb:82:in `fetch'
  /var/www/canvas_lms/app/models/account.rb:1211:in `block in find_cached'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.4/app/models/switchman/shard_internal.rb:584:in `block in activate'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.4/app/models/switchman/shard_internal.rb:86:in `activate'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.4/app/models/switchman/shard_internal.rb:583:in `activate'
  /var/www/canvas_lms/app/models/account.rb:1210:in `find_cached'
  /var/www/canvas_lms/app/models/account.rb:1229:in `block in get_special_account'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.4/app/models/switchman/shard_internal.rb:584:in `block in activate'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.4/app/models/switchman/shard_internal.rb:86:in `activate'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/switchman-1.11.4/app/models/switchman/shard_internal.rb:583:in `activate'
  /var/www/canvas_lms/app/models/account.rb:1224:in `get_special_account'
  /var/www/canvas_lms/app/models/account.rb:1184:in `default'
  /var/www/canvas_lms/app/middleware/load_account.rb:32:in `default_domain_root_account'
  /var/www/canvas_lms/app/controllers/application_controller.rb:481:in `load_account'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:170:in `block in halting'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `block in call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `each'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:454:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126:in `process'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:30:in `process'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190:in `dispatch'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262:in `dispatch'
  /var/www/canvas_lms/config/application.rb:247:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:26:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/request_store-1.4.0/lib/request_store/middleware.rb:19:in `call'
  /var/www/canvas_lms/app/middleware/request_context_generator.rb:49:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  /var/www/canvas_lms/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `public_send'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `method_missing'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'


[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] Created ErrorReport ID 10000001270988
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] Created ErrorReport ID 10000001270989
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] Completed 500 Internal Server Error in 47ms (ActiveRecord: 6.4ms)
[- 2be4eb13-f6fd-4d6d-9e9d-1dec64a91668] [STATSD] (sql_read: 1.00) (sql_write: 2.00) (sql_cache: 0.00) (active_record: 3.00) (cache_read: 2.00) (total: 46.91) (db: 6.41)

```

**Comment by ccutrer** [comment]
It looks like you upgraded a Rails version during your Canvas upgrade, so the cache needed to be flushed. There is a migration that clears that cache when we upgrade Rails versions, but it's possible due to the order that things were applied that an process running older code/older Rails was still running after the clear, and inserted some data that could no longer be read.

**Comment by noriando** [comment]
I had the same error ... how we should upgrade Rails when canvas upgrade then? Can anybody put some light on it? Only clean installation is successful so far.

**Comment by noriando** [comment]
Now it is OK ...
I upgrade Redis first and execute following 
bundle update
bundle install
yarn install
npm cache clean && rm -rf node_modules && npm install
RAILS_ENV=production  bundle exec rake canvas:compile_assets

**Comment by Boudewijn26** [comment]
Forgive the necropost, but this is the first result when looking for this error and I figured this may help people having the same issue.

As @ccutrer says this issue is caused by older jobs being stuck in Redis. I fixed it by `redis-cli flushall` to clear all jobs, if you care about the data you might want to be more precise in your cleaning. To prevent this be sure to run `/etc/init.d/canvas_init stop` before upgrading.

**Comment by n3rve** [comment]
That's helpful information. Thanks @Boudewijn26.

**Comment by n3rve** [comment]
Hi, 

I have continued to get these errors, even after several upgrades. The only way to get Canvas to work again and not display the 500 error is by running **redis-cli flushall** - The application starts up immediately after the redis cache is flushed. 

Can anyone share any tips to resolve this? Some information on my environment:
- Ubuntu 16.04 LTS
- ruby 2.4.0p0 (2016-12-24 revision 57164)
- PostgreSQL 9.6.9 on x86_64-pc-linux-gnu (Ubuntu 9.6.9-2.pgdg14.04+1)
- Apache/2.4.18
