### ISSUE TITLE
ActionView::Template::Error (Fingerprint not found. bundles/addpeople new_styles_normal_contrast)

### ISSUE THREAD

**Issue by n3rve** [instructure/canvas-lms#1210]
### Summary:

I'm getting a 500 error when I attempt to load `/courses/2/users`. The following is an excerpt from `production.log`

### Logs:

```
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f] Created ErrorReport ID 10000001271116
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f]   Rendering shared/errors/500_message.html.erb within layouts/application
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f]   Rendered shared/errors/_error_form.html.erb (1.0ms)
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f]   Rendered shared/errors/500_message.html.erb within layouts/application (1.5ms)
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f]   Rendered layouts/_head.html.erb (1.0ms)
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f] Created ErrorReport ID 10000001271117
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f] Completed 500 Internal Server Error in 107ms (ActiveRecord: 15.8ms)
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f] [STATSD] (sql_read: 18.00) (sql_write: 3.00) (sql_cache: 0.00) (active_record: 22.00) (cache_read: 39.00) (total: 106.61) (db: 15.82)
[74ceaa99bb4e610bc806008ec9afafc2 2acb64e9-25c7-4a1d-9e97-ee14dfd94e0f] [STAT] 713452 713452 0 713452 0.08999999999999997 0.0
[74ceaa99bb4e610bc806008ec9afafc2 0004123a-fc99-4329-8dc9-fcf9a12b137c] Started GET "/api/v1/conversations/unread_count" for 154.118.108.125 at 2018-01-16 12:30:58 +0000
[74ceaa99bb4e610bc806008ec9afafc2 0004123a-fc99-4329-8dc9-fcf9a12b137c] Processing by ConversationsController#unread_count as JSON
[74ceaa99bb4e610bc806008ec9afafc2 0004123a-fc99-4329-8dc9-fcf9a12b137c] Completed 200 OK in 14ms (Views: 0.2ms | ActiveRecord: 1.0ms)
[74ceaa99bb4e610bc806008ec9afafc2 0004123a-fc99-4329-8dc9-fcf9a12b137c] [STATSD] (sql_read: 2.00) (sql_write: 0.00) (sql_cache: 0.00) (active_record: 2.00) (cache_read: 0.00) (total: 13.64) (view: 0.15) (db: 0.99)
[74ceaa99bb4e610bc806008ec9afafc2 0004123a-fc99-4329-8dc9-fcf9a12b137c] [STAT] 713452 713452 0 713452 0.020000000000000018 0.0
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3] Started GET "/courses/2/users" for 154.118.108.125 at 2018-01-16 12:31:39 +0000
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3] Processing by ContextController#roster as HTML
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3]   Parameters: {"course_id"=>"2"}
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3]   Rendering context/roster.html.erb within layouts/application
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3]   Rendered context/_roster_right_side.html.erb (2.1ms)
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3]   Rendered context/roster.html.erb within layouts/application (3.5ms)
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3]   Rendered layouts/_head.html.erb (3.8ms)
[74ceaa99bb4e610bc806008ec9afafc2 8f7d9649-c810-4261-ab23-c97faf83d2a3] 
ActionView::Template::Error (Fingerprint not found. bundles/addpeople new_styles_normal_contrast):
["    64:   <%= include_custom_meta_tags %>", "    65:   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">", "    66:   <meta name=\"theme-color\" content=\"<%= brand_variable('ic-brand-primary') %>\">", "    67:   <%= include_css_bundles %>", "    68:   <%= yield :stylesheets %>", "    69:   <%= include_account_css %>", "    70:   <script>"]  /var/www/canvas_lms/lib/brandable_css.rb:309:in `cache_for'
  /var/www/canvas_lms/app/helpers/application_helper.rb:255:in `css_url_for'
  /var/www/canvas_lms/app/helpers/application_helper.rb:235:in `block in include_css_bundles'
  /var/www/canvas_lms/app/helpers/application_helper.rb:234:in `map'
  /var/www/canvas_lms/app/helpers/application_helper.rb:234:in `include_css_bundles'
  /var/www/canvas_lms/app/views/layouts/_head.html.erb:67:in `_app_views_layouts__head_html_erb__2853617588234321364_70147207205440'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:159:in `block in render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:354:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:157:in `render'
  /var/www/canvas_lms/config/initializers/i18n.rb:260:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/partial_renderer.rb:343:in `render_partial'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/partial_renderer.rb:311:in `block in render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/partial_renderer.rb:310:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:47:in `render_partial'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:21:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/helpers/rendering_helper.rb:32:in `render'
  /var/www/canvas_lms/app/views/layouts/application.html.erb:79:in `_app_views_layouts_application_html_erb___3572003906533790310_70147193072680'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:159:in `block in render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:354:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/template.rb:157:in `render'
  /var/www/canvas_lms/config/initializers/i18n.rb:260:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/template_renderer.rb:14:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/renderer/renderer.rb:23:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:104:in `_render_template'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:83:in `render_to_body'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/rendering.rb:26:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:36:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /var/www/canvas_lms/app/controllers/application_controller.rb:1937:in `render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/implicit_render.rb:36:in `default_render'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:188:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:126:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/canvas_statsd-2.0.4/lib/canvas_statsd/statsd.rb:81:in `batch'
  /var/www/canvas_lms/app/controllers/application_controller.rb:442:in `batch_statsd'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /var/www/canvas_lms/lib/temp_cache.rb:28:in `enable'
  /var/www/canvas_lms/app/controllers/application_controller.rb:438:in `enable_request_cache'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  /var/www/canvas_lms/app/controllers/application_controller.rb:432:in `set_locale'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:382:in `block in make_lambda'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:285:in `block in halting'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:447:in `block in around'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:455:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `block in instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:164:in `instrument'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/abstract_controller/base.rb:126:in `process'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.4/lib/action_view/rendering.rb:30:in `process'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:190:in `dispatch'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_controller/metal.rb:262:in `dispatch'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:39:in `block in serve'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `each'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/journey/router.rb:26:in `serve'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:725:in `call'
  /var/www/canvas_lms/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
  /var/www/canvas_lms/app/middleware/request_throttle.rb:60:in `block in call'
  /var/www/canvas_lms/app/middleware/request_throttle.rb:272:in `reserve_capacity'
  /var/www/canvas_lms/app/middleware/request_throttle.rb:55:in `call'
  /var/www/canvas_lms/app/middleware/request_context_session.rb:25:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
  /var/www/canvas_lms/app/middleware/load_account.rb:29:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:26:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/request_store-1.4.0/lib/request_store/middleware.rb:19:in `call'
  /var/www/canvas_lms/app/middleware/request_context_generator.rb:49:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  /var/www/canvas_lms/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `public_send'
  /var/www/canvas_lms/vendor/bundle/ruby/2.4.0/gems/railties-5.0.4/lib/rails/railtie.rb:193:in `method_missing'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/local/lib/ruby/gems/2.4.0/gems/passenger-5.1.5/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```

### Steps Taken:

I've followed all the steps from the upgrading document, updating gems, running migrations, compiling assets, yarn install, every step completes successfully without any errors. The only warning I got was about a bundle mismatch (server is running `1.13.6` which is older than the version that generated the lockfile `1.14.3`.

### Additional notes:
The instance was upgraded recently. I also re-attempted the upgrade using the latest code from origin/stable.

**Comment by omarkhan** [comment]
We use github issues for bugs only. For support see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Good luck!
