### ISSUE TITLE
error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.3.2".

### ISSUE THREAD

**Issue by pengc99** [instructure/canvas-lms#1250]
### Summary:
Installing into production from a base up to date Debian 9.3 system results in the following when attempting to use Yarn to install modules

```
$ yarn install
yarn install v1.5.1
$ script/gem_npm install
running yarn install for gems/canvas_i18nliner/package.json
yarn install v1.5.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.11s.
running yarn install for gems/selinimum/package.json
yarn install v1.5.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.76s.
[1/5] Validating package.json...
error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.3.2".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/src/canvas/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
### Steps to reproduce:

 1. Follow the Production Start instructions at https://github.com/instructure/canvas-lms/wiki/Production-Start
 2. Issue is encountered during the Yarn Installation part of the phase

### Expected behavior:
Expected Yarn to be able to install required modules. Using npm satisfies the modules requirement, but the application fails when raked:

```$ RAILS_ENV=production bundle exec rake canvas:compile_assets --trace
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
** Invoke canvas:compile_assets (first_time)
** Execute canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
** Invoke js:yarn_install (first_time)
** Execute js:yarn_install
node is: v8.9.4 (/usr/bin/node)
yarn install v1.5.1
$ script/gem_npm install
running yarn install for gems/canvas_i18nliner/package.json
yarn install v1.5.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.60s.
running yarn install for gems/selinimum/package.json
yarn install v1.5.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.56s.
[1/5] Validating package.json...
error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.3.2".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/src/canvas/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
rake aborted!
error running yarn install
/usr/local/src/canvas/lib/tasks/js.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/local/src/canvas/lib/tasks/canvas.rake:31:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/usr/local/src/canvas/lib/tasks/canvas.rake:7:in `log_time'
/usr/local/src/canvas/lib/tasks/canvas.rake:30:in `block (2 levels) in <top (required)>'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/bin/rake:23:in `load'
/usr/local/src/canvas/vendor/bundle/ruby/2.4.0/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => js:yarn_install
```
### Additional notes:
Has anyone ever installed this successfully? Not even the "quick start" guide works.

**Comment by claydiffrient** [comment]
Looks like you are using `yarn@1.5.1`, but currently our package.json limits you to `yarn@1.3.2`.  I'll see if we can upgrade this week.

For now to get unblocked you can manually edit your local copy of the package.json `engines` field to allow `yarn@1.5.1` or you can downgrade the version of yarn in use on your system.

**Comment by pengc99** [comment]
Thank you for the reply; after performing the modifications you suggested I was able to get it working.

**Comment by simonista** [comment]
We've got a patchset in progress to upgrade to 1.6.0, just testing now, hopefully merged today. In the mean time you can do the same workaround @claydiffrient mentioned above: directly edit your package.json file to reference 1.6.0

**Comment by qq7** [comment]
Great to hear that, thanks @simonista. :+1:
