### ISSUE TITLE
Initial set up error on Mac OS High Sierra

### ISSUE THREAD

**Issue by subratrout** [instructure/canvas-lms#1279]
### Summary:
I am trying to setup Canvas-lms on my local machine using Quick Setup method. However, when I run "bundle exec rails db:initial_setup"
### Actual behavior:
Gives me following error:
```
rails aborted!
LoadError: dlopen(/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/nokogiri-xmlsec-instructure-0.9.4/lib/nokogiri_ext_xmlsec.bundle, 9): Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /Users/subratrout/.rvm/gems/ruby-2.4.1/gems/nokogiri-xmlsec-instructure-0.9.4/lib/nokogiri_ext_xmlsec.bundle
  Reason: Incompatible library version: nokogiri_ext_xmlsec.bundle requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0 - /Users/subratrout/.rvm/gems/ruby-2.4.1/gems/nokogiri-xmlsec-instructure-0.9.4/lib/nokogiri_ext_xmlsec.bundle
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/nokogiri-xmlsec-instructure-0.9.4/lib/xmlsec.rb:3:in `<top (required)>'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/nokogiri-xmlsec-instructure-0.9.4/lib/nokogiri-xmlsec.rb:1:in `<top (required)>'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/saml2-2.1.0/lib/saml2/response.rb:3:in `<top (required)>'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/saml2-2.1.0/lib/saml2.rb:7:in `<top (required)>'
/Users/subratrout/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/subratrout/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/Users/subratrout/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/Users/subratrout/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/Users/subratrout/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/Users/subratrout/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/subratrout/rails_project/canvas/config/application.rb:36:in `<top (required)>'
/Users/subratrout/rails_project/canvas/Rakefile:4:in `require'
/Users/subratrout/rails_project/canvas/Rakefile:4:in `<top (required)>'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/command.rb:46:in `invoke'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
/Users/subratrout/rails_project/canvas/bin/rails:9:in `require'
/Users/subratrout/rails_project/canvas/bin/rails:9:in `<top (required)>'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/subratrout/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/subratrout/rails_project/canvas/bin/spring:13:in `require'
/Users/subratrout/rails_project/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
```

**Comment by tierra** [comment]
Hi @subratrout . We use github issues for bugs only, for support please see [getting help](https://github.com/instructure/canvas-lms/wiki#getting-help). Thanks!

That said, this is a pretty common issue getting started on OSX, and you should try running the following first:

```
gem update --system
xcode-select --install # Then agree to the terms, even if you have done this before!
bundle
```

If that doesn't resolve your issue, please follow up on one of the various support channels we have available.
