### ISSUE TITLE
Missing method recache_grade_distribution

### ISSUE THREAD

**Issue by shawniverson** [instructure/canvas-lms#1325]
### Summary:

When performing a CSV SIS Import, an error is thrown that recache_grade_distribution is an undefined method.

### Steps to reproduce:

 1.  Prepare a CSV Import containing courses and users.
 2.  Upload
 3.  Wait for delayed jobs to finish processing CSV.

### Expected behavior:

Method should not be undefined

### Actual behavior:

```
#2798543 Importing CSV for account: 1 (...) sis_batch_id: 720: undefined method `recache_grade_distribution' for #<Course:0x0000555b09d0ef30>
category: NoMethodError
created at: 2018-07-23 18:32:20 -0400

hostname: task-node1 
pid: 4911 
type: sis_import 
        undefined method `recache_grade_distribution' for #<Course:0x0000555b09d0ef30>

        /var/canvas/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
/var/canvas/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
/var/canvas/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
/var/canvas/lib/sis/enrollment_importer.rb:50:in `block in process'
/var/canvas/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in `block in in_groups_of'
/var/canvas/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in `each'
/var/canvas/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in `each_slice'
/var/canvas/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in `in_groups_of'
/var/canvas/lib/sis/enrollment_importer.rb:47:in `process'
/var/canvas/lib/sis/csv/enrollment_importer.rb:36:in `process'
/var/canvas/lib/sis/csv/import.rb:186:in `block (2 levels) in process'
/var/canvas/lib/sis/csv/import.rb:186:in `each'
/var/canvas/lib/sis/csv/import.rb:186:in `block in process'
/var/canvas/lib/sis/csv/import.rb:184:in `each'
/var/canvas/lib/sis/csv/import.rb:184:in `process'
/var/canvas/lib/sis/csv/import.rb:87:in `process'
/var/canvas/app/models/sis_batch.rb:316:in `process_instructure_csv_zip'
/var/canvas/app/models/sis_batch.rb:46:in `block in valid_import_types'
/var/canvas/app/models/sis_batch.rb:222:in `process_without_send_later'
/var/canvas/app/models/sis_batch.rb:283:in `block (2 levels) in process_all_for_account'
/var/canvas/app/models/sis_batch.rb:282:in `each'
/var/canvas/app/models/sis_batch.rb:282:in `block in process_all_for_account'
/var/canvas/app/models/sis_batch.rb:279:in `loop'
/var/canvas/app/models/sis_batch.rb:279:in `process_all_for_account'
...
```

### Additional notes:

An examination of the source tree in master has left me empty-handed trying to find a method definition.

**Comment by roor0** [comment]
This method is defined in the analytics plugin. I just merged a fix to master but replication is lagging.

**Comment by shawniverson** [comment]
@roor0 Thanks!
