### ISSUE TITLE
Possible small error in Quick Start Guide instructions

### ISSUE THREAD

**Issue by dmuneras** [instructure/canvas-lms#1355]
### Summary:

Looks like you have to create the assets before executing the command to setup the database.

### Steps to reproduce:

 1. Follow the instructions to install canvas lms in MacOS HighSierra
 2. You are going to get this error:

``` 
/Users/dmuneras/Documents/OpenSource/canvas/lib/brandable_css.rb:136:in `block in check_if_we_need_to_create_a_db_migration'
/Users/dmuneras/Documents/OpenSource/canvas/lib/brandable_css.rb:132:in `each'
/Users/dmuneras/Documents/OpenSource/canvas/lib/brandable_css.rb:132:in `check_if_we_need_to_create_a_db_migration'
/Users/dmuneras/Documents/OpenSource/canvas/lib/brandable_css.rb:148:in `default_variables_md5'
/Users/dmuneras/Documents/OpenSource/canvas/app/models/brand_config.rb:130:in `block (2 levels) in <class:BrandConfig>'
/Users/dmuneras/Documents/OpenSource/canvas/app/models/brand_config.rb:134:in `block (2 levels) in <class:BrandConfig>'
/Users/dmuneras/Documents/OpenSource/canvas/app/models/brand_config.rb:156:in `save_all_files!'
/Users/dmuneras/Documents/OpenSource/canvas/config/initializers/active_record.rb:690:in `find_in_batches'
/Users/dmuneras/Documents/OpenSource/canvas/db/migrate/75072935522965904110132_regenerate_brand_files_based_on_new_defaults_predeploy.rb:28:in `up'
/Users/dmuneras/Documents/OpenSource/canvas/config/initializers/active_record.rb:1361:in `execute_migration_in_transaction'
/Users/dmuneras/Documents/OpenSource/canvas/lib/tasks/canvas.rake:170:in `block (3 levels) in <top (required)>'
/Users/dmuneras/Documents/OpenSource/canvas/lib/tasks/db_load_data.rake:206:in `block (2 levels) in <top (required)>'
/Users/dmuneras/Documents/OpenSource/canvas/bin/rails:9:in `require'
/Users/dmuneras/Documents/OpenSource/canvas/bin/rails:9:in `<top (required)>'
/Users/dmuneras/Documents/OpenSource/canvas/bin/spring:13:in `require'
/Users/dmuneras/Documents/OpenSource/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Caused by:
BrandableCSS::DefaultMD5NotUpToDateError:
You have made changes to either app/stylesheets/brandable_variables.json or one of the images it
references so you need to rename the db migrations that makes sure when this change is deployed it
makes a new .css file for the css variables for each brand based on these new defaults.
To do that, run this command and then restart your rails process. (for local dev, if you want the
changes to show up in the ui, make sure you also run `rake db:migrate`).
```

### Expected behavior:

Should setup correctly the database without any error.

### Actual behavior:

Throws an error an abort migrations

### Additional notes:

Generating assets before initializing the database fix the problem for me.

**Comment by dmuneras** [comment]
I love talking to bots 😄
