### ISSUE TITLE
Error bundle exec rails, nokogiri-xmlsec-instructure not found but exist

### ISSUE THREAD

**Issue by shijij** [instructure/canvas-lms#1362]
https://github.com/instructure/canvas-lms/wiki/Quick-Start#database-population
```
bundle exec rails db:initial_setup
rails aborted!
LoadError: libicui18n.so.58: cannot open shared object file: No such file or directory - /usr/local/rvm/gems/ruby-2.4.4/gems/nokogiri-xmlsec-instructure-0.9.6/lib/nokogiri_ext_xmlsec.so
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/nokogiri-xmlsec-instructure-0.9.6/lib/xmlsec.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/nokogiri-xmlsec-instructure-0.9.6/lib/nokogiri-xmlsec.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/saml2-3.0.1/lib/saml2/response.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/usr/local/rvm/gems/ruby-2.4.4/gems/saml2-3.0.1/lib/saml2.rb:7:in `<top (required)>'
/srv/canvas/canvas/config/application.rb:36:in `<top (required)>'
/srv/canvas/canvas/Rakefile:4:in `require'
/srv/canvas/canvas/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
/usr/local/rvm/gems/ruby-2.4.4/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
/srv/canvas/canvas/bin/rails:9:in `require'
/srv/canvas/canvas/bin/rails:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/usr/local/rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.4.4/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/usr/local/rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/srv/canvas/canvas/bin/spring:13:in `require'
/srv/canvas/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
```

What I tried:

I'm running as root, while checking the 'missing' file, I found `/usr/local/rvm/gems/ruby-2.4.4/gems/nokogiri-xmlsec-instructure-0.9.6/lib/nokogiri_ext_xmlsec.so` **actually exist.** 

Same thing for later steps: 
`bundle exec rails server`
`bundle exec rails canvas:compile_assets`
Seems the problem is caused by gem `nokogiri-xmlsec-instructure-0.9.6`

Debian 8 w/ RVM using ruby 2.4.4p296

Anyone has any idea on what I've missing?

Thank you.

**Comment by zeyadsaleh** [comment]
I'm having the same issue here, any help?

**Comment by slaughter550** [comment]
We're looking into this issue. 

For now - you can pin SAML2 and its deps in this manner to get around the issue
```
gem 'saml2', '~> 3.0'
  gem 'nokogiri-xmlsec-instructure', '~> 0.9', '>= 0.9.5'
    gem 'nokogiri', '1.10.10'
```

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
