### ISSUE TITLE
Error: Permission denied @ rb_sysopen - /usr/src/app/log/development.log (Errno::EACCES)

### ISSUE THREAD

**Issue by leasonliu** [instructure/canvas-lms#1368]
### Summary:
Error: The application encountered the following error: Permission denied @ rb_sysopen - /usr/src/app/log/development.log (Errno::EACCES)
**AND**: 
got "Failed to load https://canvas.docker/file_session/clear: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://***' is therefore not allowed access."
from console of webpage

App 17346 output: Error: The application encountered the following error: Permission denied @ rb_sysopen - /usr/src/app/log/development.log (Errno::EACCES)
App 17346 output:
App 17346 output:     /usr/lib/ruby/2.4.0/open-uri.rb:37:in `initialize'
App 17346 output:     /usr/lib/ruby/2.4.0/open-uri.rb:37:in `open'
App 17346 output:     /usr/lib/ruby/2.4.0/open-uri.rb:37:in `open'
App 17346 output:     /usr/lib/ruby/2.4.0/logger.rb:744:in `open_logfile'
App 17346 output:     /usr/lib/ruby/2.4.0/logger.rb:736:in `set_dev'
App 17346 output:     /usr/lib/ruby/2.4.0/logger.rb:671:in `initialize'
App 17346 output:     /usr/lib/ruby/2.4.0/logger.rb:387:in `new'
App 17346 output:     /usr/lib/ruby/2.4.0/logger.rb:387:in `initialize'
App 17346 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/logger.rb:80:in `initialize'
App 17346 output:     /usr/src/app/lib/canvas_logger.rb:27:in `initialize'
App 17346 output:     /usr/src/app/config/application.rb:97:in `new'
App 17346 output:     /usr/src/app/config/application.rb:97:in `<class:Application>'
App 17346 output:     /usr/src/app/config/application.rb:39:in `<module:CanvasRails>'
App 17346 output:     /usr/src/app/config/application.rb:38:in `<top (required)>'
App 17346 output:     /usr/src/app/config/environment.rb:25:in `require'
App 17346 output:     /usr/src/app/config/environment.rb:25:in `<top (required)>'
App 17346 output:     config.ru:3:in `require'
App 17346 output:     config.ru:3:in `block in <main>'
App 17346 output:     /home/docker/.gem/ruby/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
App 17346 output:     /home/docker/.gem/ruby/2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
App 17346 output:     config.ru:1:in `new'
App 17346 output:     config.ru:1:in `<main>'
App 17346 output:     /usr/share/passenger/helper-scripts/rack-loader.rb:96:in `eval'
App 17346 output:     /usr/share/passenger/helper-scripts/rack-loader.rb:96:in `load_app'
App 17346 output:     /usr/share/passenger/helper-scripts/rack-loader.rb:116:in `block in <module:App>'
App 17346 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 17346 output:     /usr/share/passenger/helper-scripts/rack-loader.rb:115:in `<module:App>'
App 17346 output:     /usr/share/passenger/helper-scripts/rack-loader.rb:28:in `<module:PhusionPassenger>'
App 17346 output:     /usr/share/passenger/helper-scripts/rack-loader.rb:27:in `<main>'
[ E 2018-10-22 21:19:48.7675 14/T3l age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /usr/src/app: The application encountered the following error: Permission denied @ rb_sysopen - /usr/src/app/log/development.log (Errno::EACCES)
  Error ID: d732cc50
  Error details saved to: /tmp/passenger-error-TSLdgu.html

### Steps to reproduce:

 1. log out from http://canvas.docker
 2. logs got from container "canvas_web"

### Expected behavior:
no error alert
### Actual behavior:
alert on web page and have permission denied in logs

**Comment by leasonliu** [comment]
I also got ERR_NAME_NOT_RESOLVED when I logged out and access to pictures I uploaded.
