### ISSUE TITLE
Cannot run canvas in Arch Linux (thrift gem error)

### ISSUE THREAD

**Issue by PinkFLoyd92** [instructure/canvas-lms#1370]
### Summary:
I am trying to run canvas on development environment but when I install the gems using bundler I get the following output:
```
sebas@robot canvas-lms $ bundle _1.16.4_ install
Fetching https://github.com/rails-api/active_model_serializers.git
Fetching https://github.com/flyerhzm/bullet.git
Fetching https://github.com/kreynolds/cassandra-cql.git
Fetching https://github.com/twitter/thrift_client.git
Fetching https://github.com/redis-store/redis-store.git
Fetching https://github.com/redis-store/redis-activesupport.git
Fetching https://github.com/instructure/test-queue.git
Fetching https://github.com/tucker-m/pact-support.git
Fetching https://github.com/tucker-m/pact-ruby.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies..............
Using rake 12.3.1
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.1.6
Using multi_xml 0.6.0
Using httparty 0.16.1
Using academic_benchmarks 0.0.10
Using builder 3.2.3
Using erubi 1.7.1
Using mini_portile2 2.3.0
Using nokogiri 1.8.5
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.2
Using rails-html-sanitizer 1.0.4
Using actionview 5.1.6
Using rack 2.0.4
Using rack-test 0.8.3
Using actionpack 5.1.6
Using nio4r 2.3.1
Using websocket-extensions 0.1.3
Using websocket-driver 0.6.5
Using actioncable 5.1.6
Using globalid 0.4.1
Using activejob 5.1.6
Using mini_mime 1.0.0
Using mail 2.7.0
Using actionmailer 5.1.6
Using activemodel 5.1.6
Using arel 8.0.0
Using activerecord 5.1.6
Using bundler 1.16.4
Using method_source 0.9.0
Using thor 0.20.0
Using railties 5.1.6
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.1.6
Using academic_benchmark 1.1.0 from source at `/home/sebas/Projects/canvas-lms/gems/plugins/academic_benchmark`
Using account_reports 1.1.0 from source at `/home/sebas/Projects/canvas-lms/gems/plugins/account_reports`
Using active_model-better_errors 1.6.7
Using active_model_serializers 0.9.0.alpha1 from https://github.com/rails-api/active_model_serializers.git (at 61882e1@61882e1)
Using activesupport-suspend_callbacks 0.0.1 from source at `gems/activesupport-suspend_callbacks`
Using acts_as_list 0.0.1 from source at `gems/acts_as_list`
Using public_suffix 3.0.3
Using addressable 2.5.2
Using aroi 0.0.6
Using statsd-ruby 1.4.0
Using canvas_statsd 2.0.4
Using adheres_to_policy 0.0.1 from source at `gems/adheres_to_policy`
Using adobe_connect 1.0.6
Using aes_key_wrap 1.0.1
Using after_transaction_commit 2.0.0
Using io-like 0.3.0
Using archive-zip 0.11.0
Using ast 2.4.0
Using attachment_fu 1.0.0 from source at `gems/attachment_fu`
Using request_store 1.4.1
Using ffi 1.9.18
Using ffi-compiler 1.0.1
Using scrypt 3.0.5
Using authlogic 4.0.1
Using autoextend 1.0.0 from source at `gems`
Using extlib 0.9.16
Using multi_json 1.13.1
Using autoparse 0.3.3
Using awesome_print 1.8.0
Using aws-eventstream 1.0.1
Using aws-partitions 1.106.0
Using aws-sigv4 1.0.3
Using jmespath 1.4.0
Using aws-sdk-core 3.27.0
Using aws-sdk-autoscaling 1.5.0
Using aws-sdk-kinesis 1.6.0
Using aws-sdk-kms 1.9.0
Using aws-sdk-s3 1.19.0
Using aws-sdk-sns 1.5.0
Using aws-sdk-sqs 1.6.0
Using barby 0.6.5
Using bcrypt 3.1.11
Using bindata 2.4.4
Using bluecloth 2.2.0
Using folio-pagination 0.0.12
Using json 2.1.0
Using json_token 0.0.1 from source at `gems/json_token`
Using will_paginate 3.1.6
Using paginated_collection 1.0.0 from source at `gems/paginated_collection`
Using bookmarked_collection 1.0.0 from source at `gems/bookmarked_collection`
Using brakeman 4.3.1
Using broadcast_policy 1.0.0 from source at `gems/broadcast_policy`
Using uniform_notifier 1.11.0
Using bullet 5.7.5 from https://github.com/flyerhzm/bullet.git (at 1677bc0@1677bc0)
Using byebug 10.0.2
Using canvas_breach_mitigation 0.0.1 from source at `gems/canvas_breach_mitigation`
Using simple_uuid 0.4.0
Fetching thrift 0.9.3.0
Installing thrift 0.9.3.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/sebas/.rvm/gems/ruby-2.4.4/gems/thrift-0.9.3.0/ext
/home/sebas/.rvm/rubies/ruby-2.4.4/bin/ruby -r ./siteconf20181023-4180-1ohe88n.rb extconf.rb --with-cppflags=
checking for strlcpy() in string.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/sebas/.rvm/rubies/ruby-2.4.4/bin/$(RUBY_BASE_NAME)
/home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:768:in `try_func'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:1055:in `block in have_func'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:1054:in `have_func'
	from extconf.rb:31:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/sebas/.rvm/gems/ruby-2.4.4/extensions/x86_64-linux/2.4.0/thrift-0.9.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/sebas/.rvm/gems/ruby-2.4.4/gems/thrift-0.9.3.0 for inspection.
Results logged to /home/sebas/.rvm/gems/ruby-2.4.4/extensions/x86_64-linux/2.4.0/thrift-0.9.3.0/gem_make.out

An error occurred while installing thrift (0.9.3.0), and Bundler cannot continue.
Make sure that `gem install thrift -v '0.9.3.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  event_stream was resolved to 0.0.1, which depends on
    canvas_cassandra was resolved to 0.0.1, which depends on
      cassandra-cql was resolved to 1.2.3, which depends on
        thrift_client was resolved to 0.9.3, which depends on
```
I have already installed the base-devel packages in Arch Linux, but even following the stetps on the page I get

```
sebas@robot canvas-lms $ gem install thrift -v '0.9.3.0' --source 'https://rubygems.org/'
Building native extensions. This could take a while...
/home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/site_ruby/2.4.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /home/sebas/.config/yarn/global/node_modules in PATH, mode 040777
ERROR:  Error installing thrift:
	ERROR: Failed to build gem native extension.

    current directory: /home/sebas/.rvm/gems/ruby-2.4.4/gems/thrift-0.9.3.0/ext
/home/sebas/.rvm/rubies/ruby-2.4.4/bin/ruby -r ./siteconf20181023-6885-1dslw97.rb extconf.rb
checking for strlcpy() in string.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/sebas/.rvm/rubies/ruby-2.4.4/bin/$(RUBY_BASE_NAME)
/home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:768:in `try_func'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:1055:in `block in have_func'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
	from /home/sebas/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/mkmf.rb:1054:in `have_func'
	from extconf.rb:31:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/sebas/.rvm/gems/ruby-2.4.4/extensions/x86_64-linux/2.4.0/thrift-0.9.3.0/mkmf.log

extconf failed, exit code 1
```
 
### Steps to reproduce:

 1. Run bundle install or try to install the gem thrift 0.9.3 in Arch linux

### Additional notes:
Linux Distribution: Arch linux
Kernel: Linux robot 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018 x86_64 GNU/Linux
ruby version: 2.4.4
bundler version: 1.16.4

**Comment by PinkFLoyd92** [comment]
Well the workaround was to install the gem using the following command and flags:

gem install thrift -v 0.9.3 -- --with-cppflags=\"-Wno-attribute-alias\"
