### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by Bicet** [instructure/canvas-lms#1376]
### Summary:
bundle exec rake canvas:compile_assets doesn't complete giving an error on webpack

### Steps to reproduce:

 1. Follow the production start guide

### Expected behavior:
complete the bundle exec rake canvas:compile_assets without error

### Actual behavior:
It trash out an error
``` 68% building modules 2346/2401 modules 55 active ...gradebook/OutcomeGradebookGrid.coffeeHappy[babel]: All set; signaling webpack to proceed.
Happy[coffee]: Version: 3.1.0. Using cache? No. Threads: 4 (shared pool)
Happy[coffee]: All set; signaling webpack to proceed.
Happy[handlebars-i18n]: Version: 3.1.0. Using cache? No. Threads: 4 (shared pool)
Happy[handlebars-i18n]: All set; signaling webpack to proceed.
Happy[handlebars-ember]: Version: 3.1.0. Using cache? No. Threads: 4 (shared pool)
Happy[handlebars-ember]: All set; signaling webpack to proceed.
 69% building modules 2850/2864 modules 14 active ...rations/CollaboratorPickerView.coffeeModuleNotFoundError: Module not found: Error: Can't resolve 'translations/accounts.users_list' in '/var/canvas/public/javascripts'
    at factoryCallback (/var/canvas/node_modules/webpack/lib/Compilation.js:282:40)
    at factory (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:237:20)
    at resolver (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /var/canvas/node_modules/async/dist/async.js:3888:9
    at /var/canvas/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/var/canvas/node_modules/async/dist/async.js:1062:13)
    at /var/canvas/node_modules/async/dist/async.js:969:16
    at /var/canvas/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/var/canvas/node_modules/tapable/lib/Tapable.js:252:11)
    at /var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/var/canvas/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/var/canvas/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/var/canvas/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/var/canvas/node_modules/tapable/lib/Tapable.js:249:35)
resolve 'translations/accounts.users_list' in '/var/canvas/public/javascripts'
  Parsed request is a module
  using description file: /var/canvas/package.json (relative path: ./public/javascripts)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /var/canvas/package.json (relative path: ./public/javascripts)
    resolve as module
      looking for modules in /var/canvas/public/javascripts
        using description file: /var/canvas/package.json (relative path: ./public/javascripts)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /var/canvas/package.json (relative path: ./public/javascripts)
          using description file: /var/canvas/package.json (relative path: ./public/javascripts/translations/accounts.users_list)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/public/javascripts/translations/accounts.users_list doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/public/javascripts/translations/accounts.users_list.js doesn't exist
            as directory
              /var/canvas/public/javascripts/translations/accounts.users_list doesn't exist
      looking for modules in /var/canvas/gems/plugins
        using description file: /var/canvas/package.json (relative path: ./gems/plugins)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /var/canvas/package.json (relative path: ./gems/plugins)
          using description file: /var/canvas/package.json (relative path: ./gems/plugins/translations/accounts.users_list)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/gems/plugins/translations/accounts.users_list doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/gems/plugins/translations/accounts.users_list.js doesn't exist
            as directory
              /var/canvas/gems/plugins/translations/accounts.users_list doesn't exist
      /var/canvas/public/javascripts/node_modules doesn't exist or is not a directory
      /var/canvas/public/node_modules doesn't exist or is not a directory
      /var/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /var/canvas/node_modules
        using description file: /var/canvas/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /var/canvas/package.json (relative path: ./node_modules)
          using description file: /var/canvas/package.json (relative path: ./node_modules/translations/accounts.users_list)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/node_modules/translations/accounts.users_list doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/node_modules/translations/accounts.users_list.js doesn't exist
            as directory
              /var/canvas/node_modules/translations/accounts.users_list doesn't exist
 95% emitting[ ModuleDependencyWarning: 35:15-43 "export 'default' (imported as 'returnValueOfUnpatchedWidget') was not found in 'jqueryui/widget-unpatched'
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:707:23)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at HarmonyImportSpecifierDependency._getErrors (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9),
  ModuleDependencyWarning: 42:15-41 "export 'default' (imported as 'returnValOfUnpatchedDialog') was not found in 'jqueryui/dialog-unpatched'
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:707:23)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at HarmonyImportSpecifierDependency._getErrors (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9),
  ModuleDependencyWarning: 49:19-24 "export 'Model' was not found in 'Backbone'
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:707:23)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at HarmonyImportSpecifierDependency._getErrors (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9),
  ModuleDependencyWarning: 4:15-46 "export 'default' (imported as 'returnValueOfUnpatchedDraggable') was not found in 'jqueryui/draggable-unpatched'
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:707:23)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at HarmonyImportSpecifierDependency._getErrors (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9),
  ModuleDependencyWarning: 51:26-34 "export 'debounce' was not found in 'underscore'
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:707:23)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at HarmonyImportSpecifierDependency._getErrors (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9),
  ModuleDependencyWarning: 66:23-26 "export 'map' was not found in 'underscore'
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:707:23)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at HarmonyImportSpecifierDependency._getErrors (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/var/canvas/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/var/canvas/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/var/canvas/node_modules/webpack/lib/Compilation.js:565:9)
    at applyPluginsParallel.err (/var/canvas/node_modules/webpack/lib/Compiler.js:502:17)
    at /var/canvas/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/var/canvas/node_modules/webpack/lib/Compilation.js:511:11)
    at processModuleDependencies.err (/var/canvas/node_modules/webpack/lib/Compilation.js:481:14)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) ]
/var/canvas/frontend_build/baseWebpackConfig.js:235
          throw new Error('webpack build had warnings. Failing.')
          ^

Error: webpack build had warnings. Failing.
    at Compiler.plugin (/var/canvas/frontend_build/baseWebpackConfig.js:235:17)
    at Compiler.applyPlugins (/var/canvas/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/var/canvas/node_modules/webpack/lib/Compiler.js:264:11)
    at Compiler.emitRecords (/var/canvas/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/var/canvas/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/var/canvas/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/var/canvas/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/var/canvas/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/var/canvas/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/var/canvas/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/var/canvas/node_modules/webpack/lib/Compiler.js:350:15)
    at /var/canvas/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/var/canvas/node_modules/async/dist/async.js:1064:13)
    at /var/canvas/node_modules/async/dist/async.js:969:16
    at /var/canvas/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by Bicet** [comment]
Same results with stable.
Does somebody test the stable before releasing them?

**Comment by sdb1228** [comment]
Can you give us your node version and yarn versions? Also yes we do test stable before releasing.  Stable is currently what is running in our production environment.

**Comment by claydiffrient** [comment]
@Bicet Would you mind running `./script/nuke_node.sh` and see if that gets things working better for you.

**Comment by sdb1228** [comment]
Also your yarn version is a minor version behind we run "yarn": "1.10.1".  I also run node 8.10.0.  I doubt either of those would be a problem but something you can try.

**Comment by Bicet** [comment]
> Can you give us your node version and yarn versions? Also yes we do test stable before releasing. Stable is currently what is running in our production environment.

No way It didn't work :/

> Also your yarn version is a minor version behind we run "yarn": "1.10.1". I also run node 8.10.0. I doubt either of those would be a problem but something you can try.

```
yarn install v1.10.1
[1/5] Validating package.json...
error canvas-lms@0.0.0: The engine "yarn" is incompatible with this module. Expected version "1.9.4". Got "1.10.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

So I modified package.json to use yarn 1.10.1

Same Resulto as before :/

It's a clean installation of ubuntu 16.04
