### ISSUE TITLE
UndumpableException: RuntimeError: Error running js:webpack_production

### ISSUE THREAD

**Issue by nakedou** [instructure/canvas-lms#1469]
### Steps to reproduce:

 1.git clone --depth 1  https://github.com/instructure/canvas-lms.git
 2.cd canvas-lms
 3../script/docker_dev_setup.sh

**Comment by djbender** [comment]
I've verified that the reproduction steps do work, could you provide some more details and include a stack trace?

**Comment by odero** [comment]
Not sure if it's the same error but I keep getting stuck at step 3/5. Here are 2 examples. In both cases I'm using ran the docker version using `./script/docker_dev_setup.sh`

**Example 1: Tried from master branch**
```sh
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/visionmedia/page.js/tar.gz/d11509f1f0fed0309391d995919c25dce84b8abd: getaddrinfo EAI_AGAIN codeload.github.com codeload.github.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

ERROR: Service 'jobs' failed to build: The command '/bin/sh -c bundle install --jobs 8   && yarn install --pure-lockfile' returned a non-zero code: 1
```

**Example 2: Tried from stable branch**
```sh
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/bkirkby/scroll-into-view.git
Directory: /usr/src/app
Output:
fatal: unable to access 'https://github.com/bkirkby/scroll-into-view.git/': Could not resolve host: github.com
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

ERROR: Service 'webpack' failed to build: The command '/bin/sh -c bundle install --jobs 8   && yarn install --pure-lockfile' returned a non-zero code: 128
```

Generally I'd suspect a DNS issue but there are a lot of other github.com calls before these the succeed before this so I'm not sure why this is the step that where it keeps failing.

**Comment by ryankshaw** [comment]
are you using a shared ip address or proxy/vpn or tor something where lots of requests to github end up coming from the same public IP address you are on? because maybe the problem is that github is throttling you. I noticed that both requests that fail are requests to github from.

**Comment by odero** [comment]
Seems like it was a temporary issue. I reran the command again today and it worked.

**Comment by ryankshaw** [comment]
Ya my bet is that it was GitHub throttling then

**Comment by rizkyekoputra** [comment]
I have issue same like this **UndumpableException: RuntimeError: Error running js:webpack_production** after `running docker-compose up -d --build`

```$ es-check es5 ./public/dist/**/*.js
ES-Check: there were no ES version matching errors!  🎉
Done in 118.07s.
--> Finished: 'js:webpack_development' in 118.82335449999664
rake aborted!
Parallel::UndumpableException: RuntimeError: Error running js:webpack_production:
ABORTING
/usr/src/app/lib/tasks/js.rake:50:in `block (2 levels) in <top (required)>'
/usr/src/app/lib/tasks/canvas.rake:76:in `block (5 levels) in <top (required)>'
/usr/src/app/lib/tasks/canvas.rake:7:in `log_time'
/usr/src/app/lib/tasks/canvas.rake:76:in `block (4 levels) in <top (required)>'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:486:in `call_with_index'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:341:in `block in work_in_threads'
/home/docker/.gem/ruby/2.4.0/gems/parallel-1.12.1/lib/parallel.rb:206:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
ERROR: Service 'jobs' failed to build: The command '/bin/sh -c bash -c '   set -e;     sudo -u docker -E env HOME=/home/docker PATH=$PATH bundle install --jobs 8;   yarn install --pure-lockfile;   COMPILE_ASSETS_NPM_INSTALL=0 bundle exec rake canvas:compile_assets;     sudo -u docker -E env HOME=/home/docker PATH=$PATH bundle install --without test development;   sudo -u docker -E env HOME=/home/docker PATH=$PATH bundle clean --force;   yarn install --prod;     rm -rf     /home/docker/.bundle/cache     $GEM_HOME/cache     $GEM_HOME/bundler/gems/*/{.git,spec,test,features}     $GEM_HOME/gems/*/{spec,test,features}     `yarn cache dir`     /root/.node-gyp     /tmp/phantomjs     .yardoc     client_apps/canvas_quizzes/{tmp,node_modules}     config/locales/generated     gems/*/node_modules     gems/plugins/*/node_modules     log     public/dist/maps     public/doc/api/*.json     public/javascripts/translations     tmp-*.tmp'' returned a non-zero code: 1```

**Comment by djbender** [comment]
@rizkyekoputra could you open a new issue?

**Comment by rizkyekoputra** [comment]
> @rizkyekoputra could you open a new issue?

ok @djbender , 
sorry oot, any documentation about production start with docker?
