### ISSUE TITLE
NoMethodError (undefined method `lti_guid' for #<Account:0x000056083e1df3e8>):

### ISSUE THREAD

**Issue by ecornellnick** [instructure/canvas-lms#1472]
### Summary:
I'm having the same issue as [this issue](https://github.com/instructure/canvas-lms/issues/1374) but it has not been commented on for a solution or solved (closed). Whenever I try to run this, I received the "undefined method 'lti_guid'.

NoMethodError (undefined method `lti_guid' for #<Account:0x000056083e1df3e8>):
  /var/lib/gems/2.4.0/gems/activemodel-5.1.6.2/lib/active_model/attribute_methods.rb:432:in `method_missing'
  /home/ubuntu/canvas/app/controllers/application_controller.rb:2373:in `setup_live_events_context'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:413:in `block in make_lambda'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:198:in `block in halting'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:507:in `block in invoke_before'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:507:in `each'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:507:in `invoke_before'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:106:in `block in run_callbacks'
  /home/ubuntu/canvas/app/controllers/application_controller.rb:484:in `report_to_datadog'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /var/lib/gems/2.4.0/gems/inst_statsd-2.1.4/lib/inst_statsd/statsd.rb:95:in `batch'
  /home/ubuntu/canvas/app/controllers/application_controller.rb:472:in `batch_statsd'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /home/ubuntu/canvas/lib/temp_cache.rb:28:in `enable'
  /home/ubuntu/canvas/app/controllers/application_controller.rb:468:in `enable_request_cache'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /home/ubuntu/canvas/app/controllers/application_controller.rb:462:in `set_locale'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:135:in `run_callbacks'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `block in instrument'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `instrument'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
  /var/lib/gems/2.4.0/gems/activerecord-5.1.6.2/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/abstract_controller/base.rb:124:in `process'
  /var/lib/gems/2.4.0/gems/actionview-5.1.6.2/lib/action_view/rendering.rb:30:in `process'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_controller/metal.rb:189:in `dispatch'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_controller/metal.rb:253:in `dispatch'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:31:in `serve'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `each'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `serve'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:844:in `call'
  /home/ubuntu/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:25:in `call'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
  /home/ubuntu/canvas/app/middleware/request_throttle.rb:60:in `block in call'
  /home/ubuntu/canvas/app/middleware/request_throttle.rb:278:in `reserve_capacity'
  /home/ubuntu/canvas/app/middleware/request_throttle.rb:55:in `call'
  /home/ubuntu/canvas/app/middleware/request_context_session.rb:25:in `call'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
  /home/ubuntu/canvas/app/middleware/load_account.rb:29:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:97:in `run_callbacks'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /var/lib/gems/2.4.0/gems/railties-5.1.6.2/lib/rails/rack/logger.rb:36:in `call_app'
  /var/lib/gems/2.4.0/gems/railties-5.1.6.2/lib/rails/rack/logger.rb:26:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  /var/lib/gems/2.4.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
  /home/ubuntu/canvas/app/middleware/request_context_generator.rb:49:in `call'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
  /home/ubuntu/canvas/app/middleware/prevent_non_multipart_parse.rb:33:in `call'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
  /var/lib/gems/2.4.0/gems/activesupport-5.1.6.2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /var/lib/gems/2.4.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/static.rb:125:in `call'
  /var/lib/gems/2.4.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
  /var/lib/gems/2.4.0/gems/railties-5.1.6.2/lib/rails/engine.rb:522:in `call'
  /var/lib/gems/2.4.0/gems/puma-3.11.3/lib/puma/configuration.rb:225:in `call'
  /var/lib/gems/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:624:in `handle_request'
  /var/lib/gems/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:438:in `process_client'
  /var/lib/gems/2.4.0/gems/puma-3.11.3/lib/puma/server.rb:302:in `block in run'
  /var/lib/gems/2.4.0/gems/puma-3.11.3/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

### Steps to reproduce:

 1. Run the rails server
 2. Go to the URL

Ubuntu 18.04.2 LTS
Rails: 5.1.6.2
Gem: 2.6.14.4
Ruby: 2.4.6p354 (2019-04-01 revision 67394) [x86_64-linux-gnu]
Yarn: 1.10.1
PostregreSQL: 10.9 
NPM: 6.9.0

**Comment by simonista** [comment]
This is strange, I'm wondering if something is cached incorrectly or if database migrations didn't run correctly. Account's definitely have an lti_guid field on them...
