### ISSUE TITLE
budle fails on git://github.com/amireh/grunt-template-jasmine-requirejs.git

### ISSUE THREAD

**Issue by lababidi** [instructure/canvas-lms#1515]
### Summary:
After running `bundle exec rails canvas:compile_assets` (or yarn install) I get a 
Timing out on installation:
```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/amireh/grunt-template-jasmine-requirejs.git
Directory: /Users/jqv515/a/canvas
Output:
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Operation timed out
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
rails aborted!
error running yarn install
/Users/jqv515/a/canvas/lib/tasks/js.rake:58:in `block (2 levels) in <top (required)>'
/Users/jqv515/a/canvas/lib/tasks/canvas.rake:31:in `block (3 levels) in <top (required)>'
/Users/jqv515/a/canvas/lib/tasks/canvas.rake:7:in `log_time'
/Users/jqv515/a/canvas/lib/tasks/canvas.rake:30:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/usr/local/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/Users/jqv515/a/canvas/bin/rails:9:in `require'
/Users/jqv515/a/canvas/bin/rails:9:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/usr/local/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/usr/local/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/usr/local/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/usr/local/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/jqv515/a/canvas/bin/spring:13:in `require'
/Users/jqv515/a/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => js:yarn_install
(See full trace by running task with --trace)
```

### Steps to reproduce:

 1. install external dependencis
 2. bundle install
 3. bundle exec rails canvas:compile_assets

**Comment by simonista** [comment]
Hey @lababidi, this looks like a transient failure with your computer being able to connect to github. I don't think there's any systemic issue here. Let us know if you're still struggling!
