### ISSUE TITLE
Outgoing email not working for student enrollment

### ISSUE THREAD

**Issue by cma00000** [instructure/canvas-lms#1554]
### Summary:
I ran up a docker server locally with smtp services on. I encountered a problem when sending out invitation email to student.  But email can be sent out to any other roles with no error. 
### Steps to reproduce:

 1. Run docker server locally.
 2. Expose 465 port for ssl smtp and setup stmp server config following production guide.
 3. Run delayed_job script to make sure all delayed jobs are daemonizing

### Expected behavior:
Send out enrollment invitation email
### Actual behavior:
No msg sent out

Error report said: ```Delayed Notification processing failed | confirm_registration.email.erb:2:in `block in parse!'    | /opt/canvas/canvas-lms/app/models/message.rb:503:in `eval'                                                                                      | /opt/canvas/canvas-lms/app/models/message.rb:503:in `populate_body' ```
...

No error stored in delayed jobs database using psql command: `select last_error from delayed_jobs order by updated_at desc limit 1;`
### Additional notes:
Temp workaround: I just sent instructor invitation email to students and change their role after. This method is apparently not what I'm looking for. 
May related to issue in the google group but with no reply: [https://groups.google.com/forum/#!msg/canvas-lms-users/RJMy0RMAHZo/HcFNyx7-CQAJ](https://groups.google.com/forum/#!msg/canvas-lms-users/RJMy0RMAHZo/HcFNyx7-CQAJ)

**Comment by chiennv97** [comment]
you need public that course and try to resend invitation

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
