### ISSUE TITLE
Production start issue - weird error log

### ISSUE THREAD

**Issue by eidyz** [instructure/canvas-lms#1580]
### Additional notes: here is a log from the /log/production.log file

```
[production:1 master]
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   SQL  (1.5ms)  COMMIT  [production:1 master]
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf] Created ErrorReport ID 10000000000061
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   SQL Setting Load (0.4ms)  SELECT "settings".* FROM "settings" WHERE "settings"."name" = 'collect_error_statistics' LIMIT 1  [production:1 master] 
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   SQL ErrorReport Load (0.7ms)  SELECT "error_reports".* FROM "error_reports" WHERE "error_reports"."id" = 61 LIMIT 1  [production:1 master]
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   Rendering shared/errors/500_message.html.erb within layouts/application
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   Rendered shared/errors/_error_form.html.erb (1.6ms)
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   Rendered shared/errors/500_message.html.erb within layouts/application (3.5ms) 
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf] include_css_bundles (0.3ms)
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   SQL PluginSetting Load (0.5ms)  SELECT "plugin_settings".* FROM "plugin_settings" WHERE "plugin_settings"."name" = 'pandapub' ORDER BY "plugin_settings"."id" ASC LIMIT 1  [production:1 master]
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf] rendering INST (2.2ms)
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf] rendering ENV (0.1ms) 
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   Rendered layouts/_head.html.erb (5.5ms)
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   SQL  (0.2ms)  BEGIN  [production:1 master]
[432c6c7c5029b5bcf599c4ad50a28b0d fec6270a-457f-4f35-8974-87a1e0126bdf]   SQL ErrorReport Create (1.0ms)  INSERT INTO "error_reports" ("backtrace", "message", "created_at", "updated_at", "email", "data", "category") VALUES ('<Caused>
/var/canvas/lib/temp_cache.rb:50:in `cache''
/var/canvas/app/controllers/login/canvas_controller.rb:153:in `maybe_render_mobile_login''
/var/canvas/app/controllers/login/canvas_controller.rb:35:in `new''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks''
/var/canvas/app/controllers/application_controller.rb:519:in `report_to_datadog''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:95:in `batch'' 
/var/canvas/app/controllers/application_controller.rb:507:in `batch_statsd''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks''
/var/canvas/lib/temp_cache.rb:28:in `enable''
/var/canvas/app/controllers/application_controller.rb:503:in `enable_request_cache''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'' 
/var/canvas/app/controllers/application_controller.rb:497:in `set_locale''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'' 
<Caused>
<Caused>
/var/canvas/lib/canvas/cdn/rev_manifest.rb:127:in `block (2 levels) in load_webpack_data_if_needed''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/benchmarkable.rb:43:in `block in benchmark''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'' 
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `ms''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/benchmarkable.rb:43:in `benchmark''
/var/canvas/lib/canvas/cdn/rev_manifest.rb:121:in `block in load_webpack_data_if_needed''
/var/canvas/lib/temp_cache.rb:53:in `cache'' 
/var/canvas/lib/canvas/cdn/rev_manifest.rb:120:in `load_webpack_data_if_needed''
/var/canvas/lib/canvas/cdn/rev_manifest.rb:46:in `webpack_manifest''
/var/canvas/lib/canvas/cdn/rev_manifest.rb:72:in `all_webpack_chunks_for''
/var/canvas/app/helpers/application_helper.rb:211:in `include_head_js''
/var/canvas/app/views/layouts/_head.html.erb:92:in `block in _app_views_layouts__head_html_erb__119134148561163460_47318942644080''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/benchmarkable.rb:43:in `block in benchmark''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `block in ms''
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `ms''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/benchmarkable.rb:43:in `benchmark'' 
/var/canvas/app/views/layouts/_head.html.erb:92:in `_app_views_layouts__head_html_erb__119134148561163460_47318942644080''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:159:in `block in render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:354:in `instrument_render_template''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:157:in `render''
/var/canvas/config/initializers/i18n.rb:264:in `render'' 
/var/canvas/config/initializers/template_streaming.rb:113:in `render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/partial_renderer.rb:333:in `render_partial''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/partial_renderer.rb:312:in `render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:49:in `render_partial'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:23:in `render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/helpers/rendering_helper.rb:33:in `render''
/var/canvas/app/views/layouts/application.html.erb:29:in `_app_views_layouts_application_html_erb___1967450851426418876_47318953106360''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:159:in `block in render'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:354:in `instrument_render_template''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/template.rb:157:in `render''
/var/canvas/config/initializers/i18n.rb:264:in `render''
/var/canvas/config/initializers/template_streaming.rb:113:in `render'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/template_renderer.rb:16:in `render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:44:in `render_template''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/renderer/renderer.rb:25:in `render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:103:in `_render_template''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/streaming.rb:219:in `_render_template''
/var/canvas/config/initializers/template_streaming.rb:26:in `_render_template''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:84:in `render_to_body'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:52:in `render_to_body''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/renderers.rb:142:in `render_to_body''
/var/canvas/config/initializers/template_streaming.rb:4:in `render_to_body''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/rendering.rb:25:in `render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:36:in `render'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `block in ms''
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `ms''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:46:in `block in render'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:45:in `render'' 
/var/canvas/app/controllers/application_controller.rb:2124:in `render''
/var/canvas/app/controllers/application_controller.rb:1495:in `render_rescue_action''
/var/canvas/app/controllers/application_controller.rb:1453:in `rescue_action_in_public''
/var/canvas/app/controllers/application_controller.rb:1399:in `rescue_exception''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/rescuable.rb:92:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/rescuable.rb:92:in `rescue_with_handler'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/rescuable.rb:165:in `rescue_with_handler''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:25:in `rescue in process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:21:in `process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call''
/var/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/deflater.rb:34:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/chunked.rb:54:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/tempfile_reaper.rb:15:in `call'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/etag.rb:25:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/conditional_get.rb:25:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/head.rb:12:in `call''
/var/canvas/app/middleware/request_throttle.rb:63:in `block in call'' 
/var/canvas/app/middleware/request_throttle.rb:317:in `reserve_capacity''
/var/canvas/app/middleware/request_throttle.rb:58:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call''
/var/canvas/app/middleware/request_context_session.rb:25:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:259:in `context'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:253:in `call''
/var/canvas/app/middleware/load_account.rb:29:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:28:in `call'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call''
/var/canvas/app/middleware/request_context_generator.rb:49:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/method_override.rb:22:in `call''
/var/canvas/app/middleware/prevent_non_multipart_parse.rb:33:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/runtime.rb:22:in `call'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/sendfile.rb:111:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/puma-4.2.1/lib/puma/configuration.rb:228:in `call'' 
/var/canvas/vendor/bundle/ruby/2.4.0/gems/puma-4.2.1/lib/puma/server.rb:667:in `handle_request''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/puma-4.2.1/lib/puma/server.rb:470:in `process_client''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/puma-4.2.1/lib/puma/server.rb:328:in `block in run''
/var/canvas/vendor/bundle/ruby/2.4.0/gems/puma-4.2.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread''', 'you need to run webpack caused by you need to run webpack caused by you need to run webpack caused by you need to run webpack', '2020-02-26 17:44:59.132497', '2020-02-26 17:44:59.132497', 'unknown-example-com@instructure.example.com', '---
exception_message: you need to run webpack caused by you need to run webpack caused 
 by you need to run webpack caused by you need to run webpack
hostname: ubuntu-s-1vcpu-1gb-sfo2-01
pid: 12730
', 'ActionView::Template::Error') RETURNING "id"
```

**Comment by eidyz** [comment]
Okay for anyone stumbling upon this in the future here is what I did to fix my problem which was caused by the compile assets command running out of memory.
Anyways to solve this issue I have increased my swap size to 5 GB and disabled the parallel build for the compile assets command which is done by running 
```bash
CANVAS_BUILD_CONCURRENCY=1 RAILS_ENV=production bundle exec rake canvas:compile_assets
```
