### ISSUE TITLE
ERROR in ./public/javascripts/dummyI18nResource.js

### ISSUE THREAD

**Issue by yuanpeterli** [instructure/canvas-lms#1581]
### Steps to reproduce:

 1. Follow the instruction on the Production Start page
```
Ubuntu 18.04 or 16.04
RUBY_MAJOR=2.4
BUNDLER_VERSION=1.17.3
RUBYGEMS_VERSION=2.7.10
YARN_VERSION=1.19.1-1
```

### Actual behavior:
`RAILS_ENV=production bundle exec rake canvas:compile_assets`

give the following error
```
ERROR in ./public/javascripts/dummyI18nResource.js (./node_modules/i18n?assignments_2_MoreOptions_CanvasFiles!./public/javascripts/dummyI18nResource.js)
Module build failed (from ./node_modules/i18n/index.js):
LoaderRunnerError: Module '/var/canvas/node_modules/i18n/index.js' is not a loader (must have normal or pitch function)
    at loadLoader (/var/canvas/node_modules/loader-runner/lib/loadLoader.js:43:20)
    at iteratePitchingLoaders (/var/canvas/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/var/canvas/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/var/canvas/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/var/canvas/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/var/canvas/node_modules/webpack/lib/Compilation.js:739:10)
    at factory.create (/var/canvas/node_modules/webpack/lib/Compilation.js:981:14)
    at factory (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
    at hooks.afterResolve.callAsync (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (<anonymous>:18:1)
    at resolver (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
    at process.nextTick (/var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:346:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 @ ./app/jsx/assignments_2/student/components/AttemptType/MoreOptions/CanvasFiles/index.js 26:0-62 40:16-20 229:15-19 263:23-27
 @ ./app/jsx/assignments_2/student/components/AttemptType/MoreOptions/Tools.js
 @ ./app/jsx/assignments_2/student/components/AttemptType/MoreOptions/UserGroupsQuery.js
 @ ./app/jsx/assignments_2/student/components/AttemptType/MoreOptions/index.js
 @ ./app/jsx/assignments_2/student/components/AttemptType/FileUpload.js
 @ ./app/jsx/assignments_2/student/components/AttemptTab.js
 @ ./app/jsx/assignments_2/student/components/SubmissionManager.js
 @ ./app/jsx/assignments_2/student/components/ContentTabs.js
 @ ./app/jsx/assignments_2/student/components/StudentContent.js
 @ ./app/jsx/assignments_2/student/components/StudentViewQuery.js
 @ ./app/jsx/assignments_2/studentIndex.js
 @ ./app/jsx/bundles/assignments_2_show_student.js
 @ ./node_modules/bundles-generated.js
 @ ./app/jsx/main.js
error Command failed with exit code 2.

```

**Comment by simonista** [comment]
What version of Node are you using?

**Comment by yuanpeterli** [comment]
sudo curl -sL https://deb.nodesource.com/setup_10.x | bash -

**Comment by yuanpeterli** [comment]
It turns out `rake i18n:generate_js` needs to be run first.
See https://github.com/instructure/canvas-lms/blob/master/doc/working_with_webpack.md

So the sequence of commands are
```
bundle install --path vendor/bundle
bundle check
yarn install
RAILS_ENV=production bundle exec rake i18n:generate_js
RAILS_ENV=production  bundle exec rake canvas:compile_assets
RAILS_ENV=production bundle exec rake db:initial_setup
```

Suggest to update the "Production Start" document.
