### ISSUE TITLE
RAILS_ENV=test bundle exec rails db:test:reset 

### ISSUE THREAD

**Issue by anwarbashir** [instructure/canvas-lms#1614]
I am following the Quick Start Instructions. 

In the Test Database Configuration this all seems to work
psql -c 'CREATE USER canvas' -d postgres
psql -c 'ALTER USER canvas CREATEDB' -d postgres
createdb -U canvas canvas_test
psql -c 'GRANT ALL PRIVILEGES ON DATABASE canvas_test TO canvas' -d canvas_test
psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO canvas' -d canvas_test
psql -c 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO canvas' -d canvas_test
but then the next command
RAILS_ENV=test bundle exec rails db:test:reset
...aborts at Tasks: TOP => db:test:reset #see output below

Can anyone advise/assist?

```
postgres@virtualserver03:/home/anwarbashir/canvas$ RAILS_ENV=test bundle exec rails db:test:reset --trace
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
** Invoke db:test:reset (first_time)
** Invoke environment (first_time)
** Execute environment
DEPRECATION WARNING: `secrets.secret_token` is deprecated in favor of `secret_key_base` and will be removed in Rails 6.0. (called from <top (required)> at /home/anwarbashir/canvas/config/environment.rb:28)
** Invoke db:load_config (first_time)
** Invoke environment
** Execute db:load_config
** Execute db:test:reset
fe_sendauth: no password supplied
Couldn't drop database 'canvas_test'
fe_sendauth: no password supplied
Couldn't create 'canvas_test' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
/home/anwarbashir/canvas/config/application.rb:141:in `initialize'
/home/anwarbashir/canvas/config/application.rb:141:in `new'
/home/anwarbashir/canvas/config/application.rb:141:in `block in connect'
/home/anwarbashir/canvas/config/application.rb:137:in `each'
/home/anwarbashir/canvas/config/application.rb:137:in `each_with_index'
/home/anwarbashir/canvas/config/application.rb:137:in `connect'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/home/anwarbashir/canvas/config/application.rb:132:in `initialize'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/switchman-1.14.10/lib/switchman/active_record/connection_pool.rb:29:in `block in checkout_new_connection'
/var/lib/postgresql/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/switchman-1.14.10/lib/switchman/active_record/connection_pool.rb:23:in `checkout_new_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/switchman-1.14.10/lib/switchman/active_record/connection_pool.rb:36:in `connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/switchman-1.14.10/lib/switchman/connection_pool_proxy.rb:59:in `connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1014:in `retrieve_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:90:in `connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:119:in `create'
/home/anwarbashir/canvas/lib/tasks/canvas.rake:206:in `block (3 levels) in <top (required)>'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/postgresql/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/home/anwarbashir/canvas/bin/rails:9:in `require'
/home/anwarbashir/canvas/bin/rails:9:in `<top (required)>'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/var/lib/postgresql/.rvm/gems/ruby-2.4.4/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/home/anwarbashir/canvas/bin/spring:13:in `require'
/home/anwarbashir/canvas/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:test:reset
```

**Comment by Ardena** [comment]
Anward,

Postgres recently made an upgrade that requires you to use a password with the database.  If you add a password to your database.yml file, drop and recreate the database, it should solve your issue.

**Comment by anwarbashir** [comment]
Okay great, Followed your advice:

In the database.yml file under the development section and after the database: canvas_development I added a password: <somepassword>, then dropped the database and tried again. It worked - thanks. :)
