### ISSUE TITLE
error on sudo /etc/init.d/canvas_init start command

### ISSUE THREAD

**Issue by anwarbashir** [instructure/canvas-lms#1619]
I am installing using production start instructions (Debian 9) and I am getting the error below at the end of the procedure. I checked issues and  the same error 3 years ago #1181. I had used rvm to install ruby 2.4.4, so I tried to follow and install 2.4.0. Did this but I am still getting the same error - any suggestions? The error seems to be in the kernal_require.rb file.

/var/canvas$ sudo /etc/init.d/canvas_init start
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/canvas/script/delayed_job:7:in `<main>'
postgres@virtualserver03:/var/canvas$

**Comment by anwarbashir** [comment]
I reinstalled on Ubuntu, now it seems to run says demonizing....
