### ISSUE TITLE
Outgoing email configuration

### ISSUE THREAD

**Issue by jefelon** [instructure/canvas-lms#1623]
### Summary:

I have installed CANVAS LMS on a VPS (DigitalOcean) following the steps of https://github.com/instructure/canvas-lms/wiki/Production-Start

Everything is going great, but the emails don't get anywhere, when adding a user, the message from Sent seems ... but nothing happens; I have tested the smtp data of the mail, it sends without problems, but in CANVAS, it does not work. I have reviewed all the manuals, tutorials, publications, but I have not managed to solve.

### Steps to reproduce:

 1. Production installation

### Expected behavior:
Send mail

### Actual behavior:

Does not send notification email to configure account

### Additional notes:

config/outgoing_mail.yml

production:
  address: "mail.domain.pe"
  port: "465"
  user_name: "user@domain.pe"
  password: "#####"
  authentication: "plain" # plain, login, or cram_md5
  domain: "domain.pe"
  outgoing_address: "user@domain.pe"
  default_name: "USER USER"

sudo /etc/init.d/canvas_init status
    Delayed jobs running, pool PID: 24583

I have restarted
 sudo /etc/init.d/canvas_init restart
and it still doesn't work

![error-mail](https://user-images.githubusercontent.com/29901436/81232964-7acaf880-8fbb-11ea-8c35-67d1fdd63818.png)

**Comment by schrink** [comment]
I updated the Canvas fed days ago to the latest stable release and the same thing happens. All email notification stopped working. There are no errors in delayed_job.log. I tried changing smtp accounts, everything - nothing works.

**Comment by lawrencetungsten** [comment]
How to turn off the remote service for notifications?

**Comment by schrink** [comment]
In the account Settings -> Feature Options

![Account_Settings](https://user-images.githubusercontent.com/2532619/83191704-bc6f3f00-a134-11ea-8263-ec70720c17ea.png)

**Comment by impnandhu** [comment]
Hi,
        I launched a site using bitnami LMS Canvas and I tried to set up an SMTP for my site. I tried several SMTP hosts like mailchimp(madrill SMTP), gmail SMTP and AWS SES. The test mail is working perfectly(SMTP Online tester) but in CANVAS it is not working. I edited my outgoing_mail.yml file and checked. The mail is not sending in any of the SMTP Server I have mentioned above and also the madrill SMTP worked for a while but it is  also not working now. 

**outgoing_mail.yml**:
While using gmail SMTP:

production:
  address: "smtp.gmail.com"
  tls : true
  port: "587"
  user_name: "XXXXXX"
  password: "XXXXXXXXXXXXX"
  authentication: "login" # plain, login, or cram_md5
  domain: "XXXXXXXXXXX.in"
  outgoing_address: "XXXXXXXX"
  default_name: "XXXXXXXX"

While using madrill SMTP:
production:
  address: "smtp.mandrillapp.com"
  tls : true
  port: "587"
  user_name: "XXXXXX"
  password: "XXXXXXXXXXXXX"
  authentication: "login" # plain, login, or cram_md5
  domain: "XXXXXXXXXXX.in"
  outgoing_address: "XXXXXXXX"
  default_name: "XXXXXXXX"

While using AWS(SES) SMTP:
production:
  address: "XXXXXXXXXXXXXXX(The host I got from AWS SES)"
  tls : true
  port: "587"
  user_name: "XXXXXX"
  password: "XXXXXXXXXXXXX"
  authentication: "login" # plain, login, or cram_md5
  domain: "XXXXXXXXXXX.in"
  outgoing_address: "XXXXXXXX"
  default_name: "XXXXXXXX"

           I don't know what I am missing and also madrill SMTP is worked for a while but I don't know why it is not working now. Could anybody please reply and correct me if I am done anything wrong. 

Thanks.

**Comment by mezuqu** [comment]
@[impnandhu] wer you able to solve the issue ? I am having same problem, and we are using amazon SEs

**Comment by maths22** [comment]
You probably want to add `enable_starttls_auto: true` to the smtp config.  I can't say if that's the only thing you need but that appears to be one of them.

**Comment by mezuqu** [comment]
@maths22 i have enabled it also. no luck.

`production:
  address: "email-smtp.us-east-1.amazonaws.com"
  port: "587"
  #tls: false
  #delivery_method: "smtp"
  enable_starttls_auto: true
  user_name: "AK........O"
  password: "B........a"
  authentication: "plain" # plain, login, or cram_md5
  domain: "online.......org"
  outgoing_address: "canvas@online.......org"
  default_name: "Instructure Canvas"`

No luck with this configuration, as i am getting this error:

`<table>
	<tr>
		<td>2022-06-23 02:49:24.821491</td>
		<td>530 Must issue a STARTTLS command first
</td>
		<td>/opt/bitnami/ruby/lib/ruby/2.7.0/net/smtp.rb:975:in `check_auth_response'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/smtp.rb:736:in `auth_plain'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/smtp.rb:728:in `authenticate'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/smtp.rb:565:in `do_start'
/opt/bitnami/ruby/lib/ruby/2.7.0/net/smtp.rb:518:in `start'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.2/lib/action_mailer/base.rb:589:in `block in deliver_mail'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/notifications.rb:180:in `block in instrument'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/notifications.rb:180:in `instrument'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.2/lib/action_mailer/base.rb:587:in `deliver_mail'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.2/lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.2/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.0.4.2/lib/action_mailer/message_delivery.rb:114:in `deliver_now'
/opt/bitnami/canvaslms/app/models/message.rb:1039:in `deliver_via_email'
/opt/bitnami/canvaslms/app/models/message.rb:736:in `deliver'
/opt/bitnami/canvaslms/app/models/message.rb:55:in `deliver'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/performable_method.rb:40:in `perform'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/backend/base.rb:305:in `block in invoke_job'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/sentry-inst_jobs-1.0.0/lib/sentry/inst_jobs/plugin.rb:12:in `block (2 levels) in <class:Plugin>'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block (2 levels) in add'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:73:in `block in initialize'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block in add'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:78:in `execute'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:51:in `run_callbacks'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/backend/base.rb:302:in `invoke_job'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-3.2.7/lib/switchman_inst_jobs/delayed/backend/base.rb:86:in `block in invoke_job'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:596:in `block in activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:98:in `activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:595:in `activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-3.2.7/lib/switchman_inst_jobs/delayed/backend/base.rb:86:in `invoke_job'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:219:in `block (2 levels) in perform'
/opt/bitnami/ruby/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:213:in `block in perform'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.1.2/lib/inst_jobs_statsd/stats/timing/perform.rb:22:in `block (2 levels) in enable_perform_timing'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.1.2/lib/inst_jobs_statsd/stats/timing.rb:8:in `block in report_timing'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst_statsd-2.2.0/lib/inst_statsd/statsd.rb:91:in `time'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.1.2/lib/inst_jobs_statsd/stats/timing.rb:8:in `report_timing'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.1.2/lib/inst_jobs_statsd/stats/timing/perform.rb:21:in `block in enable_perform_timing'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block (2 levels) in add'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.1.2/lib/inst_jobs_statsd/stats/timing/perform.rb:13:in `block (2 levels) in enable_batching'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst_statsd-2.2.0/lib/inst_statsd/statsd.rb:97:in `batch'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.1.2/lib/inst_jobs_statsd/stats/timing/perform.rb:12:in `block in enable_batching'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block (2 levels) in add'
/opt/bitnami/canvaslms/config/initializers/delayed_job.rb:153:in `block (2 levels) in <top (required)>'
/opt/bitnami/canvaslms/lib/temp_cache.rb:30:in `enable'
/opt/bitnami/canvaslms/config/initializers/delayed_job.rb:152:in `block in <top (required)>'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block (2 levels) in add'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:73:in `block in initialize'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block in add'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block in add'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:91:in `block in add'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:78:in `execute'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:51:in `run_callbacks'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:210:in `perform'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:180:in `block (2 levels) in run'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:285:in `block in configure_for_job'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:54:in `running_job'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:281:in `configure_for_job'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:179:in `block in run'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:73:in `block in initialize'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:78:in `execute'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:51:in `run_callbacks'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:171:in `run'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-3.2.7/lib/switchman_inst_jobs/delayed/worker.rb:26:in `block in run'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:596:in `block in activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:98:in `activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:595:in `activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-3.2.7/lib/switchman_inst_jobs/delayed/worker.rb:26:in `run'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:135:in `block in start'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:73:in `block in initialize'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:78:in `execute'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/lifecycle.rb:51:in `run_callbacks'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/worker.rb:134:in `start'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-3.2.7/lib/switchman_inst_jobs/delayed/worker.rb:19:in `block in start'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:596:in `block in activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:98:in `activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-2.2.2/app/models/switchman/shard.rb:595:in `activate'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-3.2.7/lib/switchman_inst_jobs/delayed/worker.rb:19:in `start'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:103:in `block in spawn_worker'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:115:in `block in fork_with_reconnects'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:111:in `fork'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:111:in `fork_with_reconnects'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:102:in `spawn_worker'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:268:in `respawn_child'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:229:in `block in maintain_children'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:228:in `each'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:228:in `maintain_children'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:175:in `block in join'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:174:in `loop'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:174:in `join'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/pool.rb:50:in `start'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/cli.rb:111:in `start'
/opt/bitnami/canvaslms/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.0.6/lib/delayed/cli.rb:36:in `run'
script/delayed_job:11:in `<main>'</td>
	</tr>
</table>
`

**Comment by impnandhu** [comment]
Thank you... But I solved the issue...

Nandhu

**Comment by mezuqu** [comment]
@impnandhu can you explain how you solved it please ?

**Comment by impnandhu** [comment]
Sure,

First you need to go to outgoing.yml file and change the following things:

production:
  address: "XXXXXXXXXXX"(You need to put the address of your smtp that
you got from AWS SES).
  port: "587" (Port No: 465 or 25 or 587)
  enable_starttls_auto : true (Keep it as true)
  user_name: "YYYYYYYYYYYY"(User name you got from AWS SES).
  password: "ZZZZZZZZZZZZZZZZZZZ"(User name you got from AWS SES).
  authentication: "login" # plain, login, or cram_md5
  domain: "google.com"(Your domain name)
  outgoing_address: "WWWWWWWWWWW"(Enter the mail ID, From which your
students need to get the mail).
  default_name: "Support iIndia"("Some name-> Eg: google")


*Note: If you are running your instance in AWS.*

1. You need to restart your services "sudo /opt/bitnami/ctlscript.sh
restart".
2. If it is not working just stop and start the instance then it will work.


Thanks,
Nandhu
