### ISSUE TITLE
uninitialized constant Lti::Concerns::DeepLinkingServices

### ISSUE THREAD

**Issue by gnovotny** [instructure/canvas-lms#1640]
### Summary:

Deep Linking response from a LTI tool is failing with the following error:

uninitialized constant Lti::Concerns::DeepLinkingServices
Rails.root: /usr/src/app

Application Trace | Framework Trace | Full Trace
app/controllers/lti/ims/deep_linking_controller.rb:25:in `<class:DeepLinkingController>'
app/controllers/lti/ims/deep_linking_controller.rb:22:in `<module:Ims>'
app/controllers/lti/ims/deep_linking_controller.rb:21:in `<module:Lti>'
app/controllers/lti/ims/deep_linking_controller.rb:20:in `<top (required)>'
app/middleware/request_throttle.rb:63:in `block in call'
app/middleware/request_throttle.rb:314:in `reserve_capacity'
app/middleware/request_throttle.rb:58:in `call'
app/middleware/request_context_session.rb:25:in `call'
app/middleware/load_account.rb:29:in `call'
app/middleware/request_context_generator.rb:49:in `call'
app/middleware/prevent_non_multipart_parse.rb:33:in `call'

### Steps to reproduce:

POST to {DOMAIN}/courses/{course_id}/deep_linking_response?context_module_id={cm_id}&modal=true

**Comment by sptik12** [comment]
got the same issue.
any progress in it?

**Comment by gnovotny** [comment]
`sed -i 's/include Concerns/include Lti::Ims::Concerns/g' canvas-lms/app/controllers/lti/ims/deep_linking_controller.rb`

**Comment by sptik12** [comment]
This helps, thank you.
But now we just get a page with 'Something broke unexpectedly' message
<img width="742" alt="error_screen" src="https://user-images.githubusercontent.com/15731725/101360414-49464280-38a6-11eb-9d1c-41b4cfef043b.png">
Please advice.

**Comment by ifThenPrem** [comment]
@sptik12 I am getting the same error when sending the LTIDeepLinkingResponseMessage to the LMS. Were you able to resolve this? 

Also if the deep_link_return_url from the Deep Linking request has a data param in the query param should we consider that data param for the data claim[https://purl.imsglobal.org/spec/lti-dl/claim/data] in the JWT we generate at the Tool?
