### ISSUE TITLE
Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)

### ISSUE THREAD

**Issue by azazahmed93** [instructure/canvas-lms#1658]
Summary:
Tried setting up canvas using Docker on macOS catalina. Currently stuck on this error even though database.yml exists. I tried copying configurations using `cp docker-compose/config/* config/`

Steps to reproduce:
 1.  docker-compose up

Expected behaviour:
Database should setup

Actual behavior:
database.yml not being detected and following error shows up:```

Error: The application encountered the following error: Cannot load database configuration:
Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)
```
Additional notes:
I've tried copying configs using `cp docker-compose/config/* config/` but no use.
I've tried giving read/write permissions to database.yml for "Everyone"
Here are complete logs

`redis_1     | 1:M 25 Jun 2020 20:39:28.832 * RDB memory usage when created 0.77 Mb
redis_1     | 1:M 25 Jun 2020 20:39:28.832 * DB loaded from disk: 0.000 seconds
redis_1     | 1:M 25 Jun 2020 20:39:28.832 * Ready to accept connections
web_1       | [ N 2020-06-25 20:43:20.5623 11/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
web_1       | [ N 2020-06-25 20:43:20.5625 11/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
web_1       | [ N 2020-06-25 20:43:20.5772 11/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 11
jobs_1      | bundler: failed to load command: script/delayed_job (script/delayed_job)
jobs_1      | Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/src/app/config/delayed_jobs.yml
jobs_1      |   /home/docker/.gem/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/settings.rb:79:in `read'
jobs_1      |   /home/docker/.gem/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/settings.rb:79:in `worker_config'
jobs_1      |   /home/docker/.gem/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/cli.rb:64:in `load_and_apply_config!'
jobs_1      |   /home/docker/.gem/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/cli.rb:27:in `run'
jobs_1      |   script/delayed_job:11:in `<top (required)>'
canvas-lms_jobs_1 exited with code 1
web_1       | [ N 2020-06-25 20:43:23.2189 11/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
web_1       | App 42 output: /home/docker/.gem/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
web_1       | App 42 output: /home/docker/.gem/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
web_1       | App 42 output: Error: The application encountered the following error: Cannot load database configuration:
web_1       | App 42 output: Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/application/configuration.rb:185:in `database_configuration'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/railtie.rb:133:in `block (2 levels) in <class:Railtie>'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:42:in `each'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:347:in `each'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:347:in `call'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
web_1       | App 42 output:     /usr/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `public_send'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/railtie.rb:190:in `method_missing'
web_1       | App 42 output:     /usr/src/app/config/environment.rb:28:in `<top (required)>'
web_1       | App 42 output:     config.ru:3:in `require'
web_1       | App 42 output:     config.ru:3:in `block in <main>'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
web_1       | App 42 output:     /home/docker/.gem/ruby/2.4.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
web_1       | App 42 output:     config.ru:1:in `new'
web_1       | App 42 output:     config.ru:1:in `<main>'
web_1       | App 42 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
web_1       | App 42 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
web_1       | App 42 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
web_1       | App 42 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:378:in `run_block_and_record_step_progress'
web_1       | App 42 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
web_1       | App 42 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
web_1       | App 42 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
web_1       | [ E 2020-06-25 20:43:29.4989 11/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /usr/src/app: The application encountered the following error: Cannot load database configuration:
web_1       | Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)
web_1       |   Error ID: 2a01da9a
web_1       |   Error details saved to: /tmp/passenger-error-Ou0W94.html
web_1       | 
web_1       | [ E 2020-06-25 20:43:29.5051 11/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 2a01da9a. Please see earlier logs for details about the error.
web_1       | 127.0.0.1 - - [25/Jun/2020:20:43:29 +0000] "HEAD / HTTP/1.1" 500 0 "-" "Passenger Prespawn Script"
`


Thanks in advance :)

**Comment by sijpkes** [comment]
Same issue here.  Firstly it says the file does not exist and secondly the example file contains [placeholder informaiton](https://github.com/instructure/canvas-lms/blob/master/config/database.yml.example).  

Its difficult to work with this project when the 'easy' option of setting up the dev server is this painful.

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
