### ISSUE TITLE
db:migrate:predeploy fails with "undefined method root_account_id" error

### ISSUE THREAD

**Issue by srdurai** [instructure/canvas-lms#1665]
### Summary:
undefined method `root_account_id' while doing db:migrate:predeploy
### Steps to reproduce:

 1. Upgrade from release/2019-09-11.10-11815-g3fb7d51 to release/2020-07-15.01-13781-g0a84c35
 2. After compile_asset try ´RAILS_ENV=production bundle exec rake db:migrate:predeploy´

### Expected behavior:
predeploy should succeed

### Actual behavior:
Fails with the following trace:
```
sudo RAILS_ENV=production bundle exec rake db:migrate:predeploy
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
1: production:public
==  PopulateModerateUserContentPermission: migrating ==========================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `root_account_id' for #<RoleOverride:0x000000001492c4a8>
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.4.3/lib/active_model/attribute_methods.rb:430:in `method_missing'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:435:in `block in inverted_lambda'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `all?'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `block in halting_and_conditional'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:181:in `run_callbacks'
/var/canvas/config/initializers/active_record.rb:1485:in `block in run_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:281:in `scoping'
/var/canvas/config/initializers/active_record.rb:1485:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/callbacks.rb:342:in `create_or_update'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/persistence.rb:308:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/validations.rb:52:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:315:in `block in save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:41:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/relation.rb:102:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:36:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:315:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/suppressor.rb:48:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:115:in `block in save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:281:in `scoping'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:115:in `save!'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:39:in `block (2 levels) in run'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:33:in `each'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:33:in `block in run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:222:in `loop'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:222:in `in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/var/canvas/config/initializers/active_record.rb:725:in `find_in_batches'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:29:in `run'
/var/canvas/db/migrate/20191210021541_populate_moderate_user_content_permission.rb:22:in `up'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:817:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:797:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:796:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.2/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:608:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:977:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:49:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1343:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1390:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `migrate'
/var/canvas/lib/tasks/canvas.rake:184:in `block (3 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:87:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:87:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:87:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/database_server.rb:107:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:86:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:373:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:625:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:93:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:624:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:371:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:367:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/database_server.rb:107:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/shackles.rb:22:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.2/lib/switchman_inst_jobs/shackles.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:67:in `block in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
NoMethodError: undefined method `root_account_id' for #<RoleOverride:0x000000001492c4a8>
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activemodel-5.2.4.3/lib/active_model/attribute_methods.rb:430:in `method_missing'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:435:in `block in inverted_lambda'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `all?'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:178:in `block in halting_and_conditional'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:181:in `run_callbacks'
/var/canvas/config/initializers/active_record.rb:1485:in `block in run_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:281:in `scoping'
/var/canvas/config/initializers/active_record.rb:1485:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/callbacks.rb:342:in `create_or_update'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/persistence.rb:308:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/validations.rb:52:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:315:in `block in save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:41:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/relation.rb:102:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:36:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:315:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/suppressor.rb:48:in `save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:115:in `block in save!'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:281:in `scoping'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:115:in `save!'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:39:in `block (2 levels) in run'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:33:in `each'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:33:in `block in run'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:222:in `loop'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:222:in `in_batches'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/var/canvas/config/initializers/active_record.rb:725:in `find_in_batches'
/var/canvas/lib/data_fixup/add_role_overrides_for_new_permission.rb:29:in `run'
/var/canvas/db/migrate/20191210021541_populate_moderate_user_content_permission.rb:22:in `up'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:817:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:797:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:796:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.2/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:608:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:977:in `migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/active_record/base.rb:49:in `transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1343:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1390:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:1210:in `migrate'
/var/canvas/lib/tasks/canvas.rake:184:in `block (3 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:87:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:87:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:87:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/database_server.rb:107:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:86:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:373:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:625:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:93:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:624:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:371:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/app/models/switchman/shard.rb:367:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/database_server.rb:107:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/switchman/shackles.rb:22:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.2/lib/switchman_inst_jobs/shackles.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.15.1/lib/tasks/switchman.rake:67:in `block in shardify_task'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate:predeploy
```
### Additional notes:
However removing this file from folder db/migrate, makes predeploy successful. If fix is not in the horizon, could someone please tell me if its ok to remove this script? Thanks.

**Comment by ccutrer** [comment]
Can you try applying https://github.com/ccutrer/canvas-lms/commit/48f2ead4be96964152a6480770c19f20f5a2847f, and see if it fixes it?

**Comment by srdurai** [comment]
Thanks ccutrer. I can't test it right now as its a production server, will try it asap. Will keep you updated.

**Comment by srdurai** [comment]
@ccutrer It worked. Thank you.
