### ISSUE TITLE
Unrecognized authentication type

### ISSUE THREAD

**Issue by LipSoft** [instructure/canvas-lms#1668]
### Summary:
Cannot send Outgoing Emails

### Steps to reproduce:
Using this config

production:

  address: "smtp.server"

  port: "587"

  user_name: "user"

  password: "password"

  authentication: "login"

  domain: "server.com"

  outgoing_address: "no-reply@server.com"

  default_name: "No Reply"

### Expected behavior:
Email Sent
### Actual behavior:
Exception: Net::SMTPAuthenticationError: 504 5.7.4 Unrecognized authentication type
### Additional notes:

I can send emails from telnet , and made a smtp sample in nodejs and can send emails to.

error trace

```
 Exception: Net::SMTPAuthenticationError: 504 5.7.4 Unrecognized authentication type

        /usr/lib/ruby/2.4.0/net/smtp.rb:981:in `check_auth_response'
        /usr/lib/ruby/2.4.0/net/smtp.rb:736:in `auth_plain'
        /usr/lib/ruby/2.4.0/net/smtp.rb:728:in `authenticate'
        /usr/lib/ruby/2.4.0/net/smtp.rb:565:in `do_start'
        /usr/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.2.4.3/lib/action_mailer/base.rb:560:in `block in deliver_mail'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.2.4.3/lib/action_mailer/base.rb:558:in `deliver_mail'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.2.4.3/lib/action_mailer/message_delivery.rb:114:in `block in deliver_now'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.2.4.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.2.4.3/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
        /var/canvas/app/models/message.rb:880:in `deliver_via_email'
        /var/canvas/app/models/message.rb:631:in `deliver'
        /var/canvas/app/models/message.rb:47:in `deliver'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/performable_method.rb:23:in `perform'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/backend/base.rb:254:in `block in invoke_job'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:67:in `block in initialize'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:72:in `execute'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:45:in `run_callbacks'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/backend/base.rb:251:in `invoke_job'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.1/lib/switchman_inst_jobs/delayed/backend/base.rb:62:in `block in invoke_job'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:605:in `block in activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:93:in `activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:604:in `activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.1/lib/switchman_inst_jobs/delayed/backend/base.rb:62:in `invoke_job'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:210:in `block (2 levels) in perform'
        /usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:204:in `block in perform'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-statsd-1.4.0/lib/inst_jobs_statsd/stats/timing/perform.rb:22:in `block (2 levels) in enable_perform_timing'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-statsd-1.4.0/lib/inst_jobs_statsd/stats/timing.rb:8:in `block in report_timing'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:89:in `time'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-statsd-1.4.0/lib/inst_jobs_statsd/stats/timing.rb:8:in `report_timing'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-statsd-1.4.0/lib/inst_jobs_statsd/stats/timing/perform.rb:21:in `block in enable_perform_timing'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:85:in `block (2 levels) in add'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-statsd-1.4.0/lib/inst_jobs_statsd/stats/timing/perform.rb:13:in `block (2 levels) in enable_batching'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:95:in `batch'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-statsd-1.4.0/lib/inst_jobs_statsd/stats/timing/perform.rb:12:in `block in enable_batching'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:85:in `block (2 levels) in add'
        /var/canvas/config/initializers/delayed_job.rb:136:in `block (2 levels) in <top (required)>'
        /var/canvas/lib/temp_cache.rb:28:in `enable'
        /var/canvas/config/initializers/delayed_job.rb:135:in `block in <top (required)>'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:85:in `block (2 levels) in add'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:67:in `block in initialize'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:85:in `block in add'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:85:in `block in add'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:85:in `block in add'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:72:in `execute'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:45:in `run_callbacks'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:201:in `perform'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:174:in `block (2 levels) in run'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:271:in `block in configure_for_job'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:173:in `block in run'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:67:in `block in initialize'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:72:in `execute'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:45:in `run_callbacks'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:166:in `run'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.1/lib/switchman_inst_jobs/delayed/worker.rb:26:in `block in run'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:605:in `block in activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:93:in `activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:604:in `activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.1/lib/switchman_inst_jobs/delayed/worker.rb:26:in `run'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:133:in `block in start'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:67:in `block in initialize'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:72:in `execute'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/lifecycle.rb:45:in `run_callbacks'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/worker.rb:131:in `start'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.1/lib/switchman_inst_jobs/delayed/worker.rb:19:in `block in start'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:605:in `block in activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:93:in `activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-1.14.10/app/models/switchman/shard_internal.rb:604:in `activate'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/switchman-inst-jobs-1.4.1/lib/switchman_inst_jobs/delayed/worker.rb:19:in `start'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:97:in `block in spawn_worker'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:108:in `block in fork_with_reconnects'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:105:in `fork'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:105:in `fork_with_reconnects'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:96:in `spawn_worker'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:74:in `block (2 levels) in spawn_all_workers'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:74:in `times'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:74:in `block in spawn_all_workers'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:73:in `each'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:73:in `spawn_all_workers'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/pool.rb:40:in `start'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/cli.rb:96:in `start'
        /var/canvas/vendor/bundle/ruby/2.4.0/gems/inst-jobs-0.15.21/lib/delayed/cli.rb:48:in `run'
        script/delayed_job:11:in `<main>'
```

**Comment by LipSoft** [comment]
So after alot of testing i think this is because the smtp only allows NTLM

can NTLM be added/supported ? 

![image](https://user-images.githubusercontent.com/20966226/87050272-8fab4e80-c1ed-11ea-86fe-163676942579.png)

I found something like this , i will try on my server

**Comment by LipSoft** [comment]
So i was able to make it work ,

i added the ruby-ntlm gem , and the require on the environment.rb

hen on outgoing_smtp i changed authentication to ntlm

its working
