### ISSUE TITLE
Error When Initializing DB

### ISSUE THREAD

**Issue by UniWrighte** [instructure/canvas-lms#1710]
### Summary:
The initial setup of the database ends in an error.
### Steps to reproduce:

 1. Follow the installation guide
 2. Run db migration ()
 3. RAILS_ENV=production bundle exec rake db:initial_setup

### Expected behavior:
Complete database migration with no errors.
### Actual behavior:
```
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.4.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
default: production
rake aborted!
TypeError: {:keyword_init=>true} is not a symbol
/var/canvas/app/models/auditors/grade_change.rb:24:in `new'
/var/canvas/app/models/auditors/grade_change.rb:24:in `<class:GradeChange>'
/var/canvas/app/models/auditors/grade_change.rb:19:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:378:in `block in require_or_load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies/interlock.rb:13:in `loading'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:37:in `load_interlock'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:356:in `require_or_load'
/var/canvas/gems/autoextend/lib/autoextend.rb:200:in `block in require_or_load'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
/var/canvas/gems/autoextend/lib/autoextend.rb:183:in `new_constants_in'
/var/canvas/gems/autoextend/lib/autoextend.rb:200:in `require_or_load'
/var/canvas/config/initializers/active_record.rb:130:in `block in models_from_files'
/var/canvas/config/initializers/active_record.rb:128:in `each'
/var/canvas/config/initializers/active_record.rb:128:in `models_from_files'
/var/canvas/config/initializers/active_record.rb:115:in `all_models'
/var/canvas/lib/tasks/db_load_data.rake:209:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:initial_setup
(See full trace by running task with --trace)
```

**Comment by simonista** [comment]
I think this is because you appear to be running ruby 2.4 and that piece of syntax is ruby 2.5+ only. We recently started requiring ruby 2.6, so I'm surprised you're not hitting that error, which branch are you running?

**Comment by simonista** [comment]
Looks like the "require 2.6" commit is in the 2020-10-07 branch, but this got added to 2020-09-23. Thanks for bringing it up, let me think about the best way to fix it.

**Comment by UniWrighte** [comment]
thank you. I was on stable.

**Comment by simonista** [comment]
er, maybe I'll leave this open while I work out what the inconsistency of the two branches

**Comment by UniWrighte** [comment]
@simonista should I just use the beta branch to get this running today?

**Comment by simonista** [comment]
No, beta is ahead of stable. You'd need to checkout one of the 2020-09-09 tags to still run ruby 2.4 right now.

**Comment by lferf** [comment]
Hello, 
I'm having the same issue. I'm running Ruby 2.6.

```
==  InvalidateBuiltInRoleCaches: migrating ====================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `global_id' for nil:NilClass
/var/canvas/db/migrate/20200914184302_invalidate_built_in_role_caches.rb:43:in `up'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-1.5.2/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:608:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1345:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1446:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/tasks/switchman.rake:87:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/tasks/switchman.rake:87:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/tasks/switchman.rake:87:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/switchman/database_server.rb:107:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/tasks/switchman.rake:86:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/app/models/switchman/shard.rb:373:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/app/models/switchman/shard.rb:625:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/app/models/switchman/shard.rb:93:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/app/models/switchman/shard.rb:624:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/app/models/switchman/shard.rb:371:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/app/models/switchman/shard.rb:367:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/tasks/switchman.rake:71:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/switchman/database_server.rb:107:in `unshackle'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/tasks/switchman.rake:68:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/switchman/shackles.rb:22:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-inst-jobs-1.5.2/lib/switchman_inst_jobs/shackles.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-1.15.2/lib/tasks/switchman.rake:67:in `block in shardify_task'
/var/canvas/lib/tasks/db_load_data.rake:210:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

**Comment by UniWrighte** [comment]
@lferf I ended up using the 10.7 release tag to get it to work with ruby 2.6

**Comment by simonista** [comment]
@lferf : that is a different issue, mentioned here: https://github.com/instructure/canvas-lms/issues/1711

At this point, since we're past 10/7 now, I'm just going to close this. Sorry for the bump in the ruby transition!

**Comment by thesk8ingtoad** [comment]
@simonista  This issue still exists on stable branch as of 10-14-2020. Same error messages as provided by @lferf on Ubuntu 18.04, running ruby 2.6.
