### ISSUE TITLE
MakeRoleRootAccountIdNotNull Fails on 2020-10-10 release

### ISSUE THREAD

**Issue by grahamb** [instructure/canvas-lms#1721]
### Summary:

(Follow-up from discussion with @ccutrer in IRC)

Pre-deploy migrations fail on the 2020-10-10 release in the `MakeRoleRootAccountIdNotNull` migration with a `PG::ForeignKeyViolation` error.

```
PG::ForeignKeyViolation: ERROR:  update or delete on table "roles" violates foreign key constraint "role_overrides_role_id_fk" on table "role_overrides"
DETAIL:  Key (id)=(19) is still referenced from table "role_overrides".`
```

### Steps to reproduce:

 1. Clone and build the 2020-10-10 release (e.g. current `instructure/stable` branch
 2. Build as normal
 3. run `RAILS_ENV=production bundle exec rake db:migrate:predeploy`

### Expected behavior:

Migrations should succeed

### Actual behavior:

Migration fails with error. Full stack trace: https://gist.github.com/grahamb/0bd17ded3212382bbbf2984d8e8c8eb8

### Additional notes:

In our database, the role with ID 19 is `NoPermissions`. It has a `workflow_state` of `built_in`. The `role_overrides` with `role_id` 19 has a `null` `context_id`.

![Screen Shot 2020-10-08 at 21 05 06](https://user-images.githubusercontent.com/146111/95817600-b25e6f00-0cd6-11eb-9e53-c45e21b1f3ab.png)
![Screen Shot 2020-10-09 at 09 54 04](https://user-images.githubusercontent.com/146111/95817606-b5595f80-0cd6-11eb-8cea-691a6db13049.png)

**Comment by grahamb** [comment]
The `role` with ID 19 is the only one that has null context_ids, so I took a leap and deleted those (probably orphaned) entries from the `role_overrides` table. The migration completed successfully.

**Comment by grahamb** [comment]
And now we're seeing errors related to role permissions, e.g. `undefined method `base_role_type' for nil:NilClass`

Example stack trace:

```
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/role_override.rb:1184:in `uncached_permission_for'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/role_override.rb:1143:in `block (2 levels) in permission_for'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/lib/canvas/cache_register.rb:217:in `block in fetch_with_cache_register'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:663:in `block in instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:663:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/lib/canvas/cache_register.rb:217:in `fetch_with_cache_register'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/lib/canvas/cache_register.rb:169:in `fetch_with_batched_keys'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/role_override.rb:1141:in `block in permission_for'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:323:in `block in fetch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:694:in `block in save_block_result_to_cache'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:663:in `block in instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:663:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:693:in `save_block_result_to_cache'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache.rb:323:in `fetch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/lib/canvas/cache/fallback_expiration_cache.rb:33:in `fetch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/lib/local_cache.rb:23:in `fetch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/role_override.rb:1140:in `permission_for'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/role_override.rb:1274:in `enabled_for?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/account_user.rb:156:in `enabled_for?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/account_user.rb:160:in `has_permission_to?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/account.rb:1201:in `block (4 levels) in <class:Account>'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/account.rb:1201:in `any?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/models/account.rb:1201:in `block (3 levels) in <class:Account>'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/condition.rb:54:in `instance_exec'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/condition.rb:54:in `applies?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/instance_methods.rb:254:in `block (2 levels) in check_right?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/instance_methods.rb:251:in `any?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/instance_methods.rb:251:in `block in check_right?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/cache.rb:46:in `fetch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/instance_methods.rb:241:in `check_right?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/adheres_to_policy/lib/adheres_to_policy/instance_methods.rb:152:in `grants_right?'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/application_controller.rb:2073:in `require_context_with_permission'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/application_controller.rb:2069:in `require_site_admin_with_permission'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/errors_controller.rb:71:in `require_view_error_reports'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:107:in `block in run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/application_controller.rb:570:in `compute_http_cost'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/application_controller.rb:587:in `report_to_datadog'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:98:in `block in batch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/statsd-ruby-1.4.0/lib/statsd.rb:73:in `easy'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/statsd-ruby-1.4.0/lib/statsd.rb:429:in `batch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:96:in `batch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/application_controller.rb:565:in `batch_statsd'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/lib/temp_cache.rb:28:in `enable'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/application_controller.rb:561:in `enable_request_cache'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/controllers/application_controller.rb:555:in `set_locale'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/marginalia-1.8.0/lib/marginalia.rb:111:in `record_query_comment'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:134:in `process'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.4.4/lib/action_view/rendering.rb:32:in `process'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:191:in `dispatch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:252:in `dispatch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `each'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `serve'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:840:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/chunked.rb:98:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/middleware/request_throttle.rb:64:in `block in call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/middleware/request_throttle.rb:332:in `reserve_capacity'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/middleware/request_throttle.rb:59:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/middleware/request_context_session.rb:25:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/middleware/load_account.rb:29:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:28:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/middleware/request_context_generator.rb:49:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/app/middleware/prevent_non_multipart_parse.rb:33:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `public_send'
/var/rails/canvas/releases/20201013182249-sfu-release-2020-10-22-2/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `method_missing'
/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `block in process_request'
/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:364:in `maybe_tag_logger'
/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `process_request'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:134:in `accept_and_process_next_request'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:95:in `main_loop'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:439:in `block (3 levels) in start_threads'
/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:97:in `block in create_thread_and_abort_on_exception'
```

**Comment by maneframe** [comment]
It seems like the cache clearing inside this migration didn't work quite right https://github.com/instructure/canvas-lms/blob/master/db/migrate/20200914184302_invalidate_built_in_role_caches.rb
You should be able to run it directly in a console with 
`[[AccountUser, :account_users], [Enrollment, :enrollments]].each { |klass, cache_type| DataFixup::InvalidateBuiltInRoleCaches.run(klass, cache_type, nil, nil) }`
and 
`Account.site_admin.clear_downstream_caches(:role_overrides)`

**Comment by grahamb** [comment]
@maneframe: we ran both of those, but the error persisted. I fully restarted our three redis instances and _that_ did resolve the issue; this isn't optimal as it also destroys active sessions and we do no-downtime deploys during the day. Any suggestions?

Also, since we'll have to do this on our staging and production systems which also have these seemingly-orphaned `role_override` records, is deleting them the right thing to do?

**Comment by maneframe** [comment]
Oh, I'm sorry about that... I thought those should have cleared out any cached references to the deleted roles in Redis but if that didn't work, I would instead run `Role.where(root_account_id: nil).update_all(root_account_id: 0)` before running the migration to satisfy the not-null constraint without having to delete anything.

**Comment by grahamb** [comment]
Migration still fails, which I'd expect, since the related `role_override` records have a `null` `context_id` value. I set the `context_id` to 0 on those `role_override` records, and the migration completed, and I'm not seeing any issues in Canvas post-deploy. The `role_override` records do persist in the database post-migration, as does the related `role` entry.

**Comment by rkanka21** [comment]
I have the same issue and none of the suggested fixes are working.

**Comment by rkanka21** [comment]
this worked

Migration fails on MakeRoleRootAccountIdNotNull

Edit db/migrate/20200910165057_make_role_root_account_id_not_null.rb:

tag :predeploy

def up
- Role.where(:root_account_id => nil).delete_all
+ Role.where(:root_account_id => nil).update_all(:root_account_id => 0)
  change_column_null :roles, :root_account_id, false
end
