### ISSUE TITLE
Unable to compile assets - NodeJS error

### ISSUE THREAD

**Issue by phk18-pitt** [instructure/canvas-lms#1751]
### Summary:
I am trying to recompile assets using: `sudo RAILS_ENV=production bundle exec rake canvas:compile_assets --trace`

### Actual behavior:
I am getting this error: 

```
rake aborted!
error running yarn install
yarn install v1.3.2
error An unexpected error occurred: "patterns.map is not a function".
```
In the error log, I see:

```
Trace:
  TypeError: patterns.map is not a function
      at /opt/bitnami/nodejs/lib/node_modules/yarn/lib/cli.js:54024:78
      at Generator.next (<anonymous>)
      at step (/opt/bitnami/nodejs/lib/node_modules/yarn/lib/cli.js:92:30)
      at /opt/bitnami/nodejs/lib/node_modules/yarn/lib/cli.js:110:14
      at new Promise (<anonymous>)
      at new F (/opt/bitnami/nodejs/lib/node_modules/yarn/lib/cli.js:29389:28)
      at /opt/bitnami/nodejs/lib/node_modules/yarn/lib/cli.js:89:12
      at Config.resolveWorkspaces (/opt/bitnami/nodejs/lib/node_modules/yarn/lib/cli.js:54060:7)
      at /opt/bitnami/nodejs/lib/node_modules/yarn/lib/cli.js:21998:49
      at Generator.next (<anonymous>)
```

Can somebody guide me on how to fix this issue please? Thanks!

**Comment by valerio-bozzolan** [comment]
I'm interested in your bug report.

Are you still having this problem?

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
