### ISSUE TITLE
There was an error evaluating `Gemfile`: ruby_version must match the :engine_version for MRI. Bundler cannot continue.

### ISSUE THREAD

**Issue by dcodeakshay** [instructure/canvas-lms#1761]
### Summary:

I'm trying to install "Canvas LMS Production" in Ubuntu 18.04.1 and installed all the packages properly. But when at last I'm entering this following command in SSH :

/etc/init.d/canvas_init start

it's giving me the following error :

[!] There was an error evaluating `Gemfile`: ruby_version must match the :engine_version for MRI. Bundler cannot continue.

 #  from /var/canvas/Gemfile.d/_before.rb:33
 #  -------------------------------------------
 #   >   #  
 #  -------------------------------------------

SO GUYS PLEASE HELP ME TO RESOLVE THIS ERROR ASAP

THANKS

**Comment by dcodeakshay** [comment]
Fetching thrift 0.9.3.0
Installing thrift 0.9.3.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/canvas/vendor/bundle/ruby/2.6.0/gems/thrift-0.9.3.0/ext
/usr/share/rvm/rubies/ruby-2.6.5/bin/ruby -I /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0 -r ./siteconf20201130-23033-150znwx.rb extconf.rb --with-cppflags\=\"-D_FORTIFY_SOURCE\=0\\
-Wno-shift-negative-value\"
checking for strlcpy() in string.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/share/rvm/rubies/ruby-2.6.5/bin/$(RUBY_BASE_NAME)
/usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:1069:in `block in have_func'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/mkmf.rb:1068:in `have_func'
	from extconf.rb:31:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/canvas/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/thrift-0.9.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/canvas/vendor/bundle/ruby/2.6.0/gems/thrift-0.9.3.0 for inspection.
Results logged to /var/canvas/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/thrift-0.9.3.0/gem_make.out

An error occurred while installing thrift (0.9.3.0), and Bundler cannot continue.
Make sure that `gem install thrift -v '0.9.3.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  event_stream was resolved to 0.0.1, which depends on
    canvas_cassandra was resolved to 0.0.1, which depends on
      cassandra-cql was resolved to 1.2.3, which depends on
        thrift_client was resolved to 0.9.3, which depends on
          thrift

**Comment by ccutrer** [comment]
Canvas no longer depends on Cassandra (and thus Thrift), so this should no longer be an issue.
