### ISSUE TITLE
Error 500 when loading external tools

### ISSUE THREAD

**Issue by shenieee09** [instructure/canvas-lms#1779]
### Steps to reproduce:

 1. I created a developer keys
 2. Go to course and adding apps
 3. Access app and get error 500 on route /courses/22/external_tools/46

When I log the error, it says:

`
ActiveModel::ValidationError (Validation failed: Iss can't be blank):
  /home/app/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:414:in `raise_validation_error'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.4/lib/active_model/validations.rb:385:in `validate!'
  /home/app/lib/lti/messages/jwt_message.rb:57:in `generate_post_payload_message'
  /home/app/lib/lti/messages/resource_link_request.rb:28:in `generate_post_payload_message'
  /home/app/lib/lti/messages/jwt_message.rb:62:in `generate_post_payload'
  /home/app/app/models/lti/lti_advantage_adapter.rb:64:in `generate_lti_params'
  /home/app/app/models/lti/lti_advantage_adapter.rb:45:in `generate_post_payload'
  /home/app/app/controllers/external_tools_controller.rb:549:in `basic_lti_launch_request'
  /home/app/app/controllers/external_tools_controller.rb:482:in `lti_launch'
  /home/app/app/controllers/external_tools_controller.rb:389:in `show'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:194:in `process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
  /home/app/app/controllers/application_controller.rb:562:in `compute_http_cost'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  /home/app/app/controllers/application_controller.rb:579:in `report_to_datadog'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  /home/app/vendor/bundle/ruby/2.6.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:95:in `batch'
  /home/app/app/controllers/application_controller.rb:557:in `batch_statsd'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  /home/app/lib/temp_cache.rb:28:in `enable'
  /home/app/app/controllers/application_controller.rb:553:in `enable_request_cache'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  /home/app/app/controllers/application_controller.rb:547:in `set_locale'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.4/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:134:in `process'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.4.4/lib/action_view/rendering.rb:32:in `process'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:191:in `dispatch'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:252:in `dispatch'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:34:in `serve'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `each'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `serve'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:840:in `call'
  /home/app/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:78:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/chunked.rb:98:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
  /home/app/app/middleware/request_throttle.rb:64:in `block in call'
  /home/app/app/middleware/request_throttle.rb:332:in `reserve_capacity'
  /home/app/app/middleware/request_throttle.rb:59:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  /home/app/app/middleware/request_context_session.rb:25:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
  /home/app/app/middleware/load_account.rb:29:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/cookies.rb:670:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'
  /home/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:28:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
  /home/app/app/middleware/request_context_generator.rb:49:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /home/app/app/middleware/prevent_non_multipart_parse.rb:33:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
  /home/app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
  /home/app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
  /home/app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
  /home/app/vendor/bundle/ruby/2.6.0/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'

`

### Expected behavior:

How can I resolve this?

**Comment by shenieee09** [comment]
@simonista could you help me?

**Comment by shenieee09** [comment]
The issue is solved by remove the comment about ISS in `config/security.yml ` file.
