### ISSUE TITLE
Database Population Error

### ISSUE THREAD

**Issue by BlackDog-HaHaHa** [instructure/canvas-lms#1796]
### Steps to reproduce:

1. Followed production steps to install canvas LMS
2. Populate DB
3. Getting this error:
canvas@instance-2:/var/canvas$ RAILS_ENV=production bundle exec rake db:initial_setup
/var/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:150: warning: constant ::Fixnum is deprecated
/var/canvas/vendor/bundle/ruby/2.6.0/gems/soap4r-ruby1.9-2.0.5/lib/soap/mapping/encodedregistry.rb:216: warning: constant ::Fixnum is deprecated
rake aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 27 column 3
/var/canvas/vendor/bundle/ruby/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:149:in `load'
/var/canvas/config/application.rb:186:in `load'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml.rb:29:in `safe_load'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml.rb:12:in `load_with_options'
/var/canvas/lib/config_file.rb:50:in `load'
/var/canvas/config/initializers/outgoing_mail.rb:27:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `block in load'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:285:in `load'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:663:in `block in load_config_initializer'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:170:in `instrument'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:662:in `load_config_initializer'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:619:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/engine.rb:619:in `block in <class:Engine>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `public_send'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `method_missing'
/var/canvas/config/environment.rb:28:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/canvas/lib/tasks/db_load_data.rake:207:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate:predeploy => environment
(See full trace by running task with --trace)
canvas@instance-2:/var/canvas$ gem list | grep rake
rake (0.8.7)

### Additional notes:
Please help me fix this, I tried many times and still doesn’t work.

**Comment by BlackDog-HaHaHa** [comment]
I found that there was a problem with my yml configuration file, so sorry
