### ISSUE TITLE
Cannot Create Courses (undefined method `template_changed?')

### ISSUE THREAD

**Issue by zjr** [instructure/canvas-lms#1864]
### Summary:

Commit 57a1bb777457e30fd13127f343e70152c6d7ad30 seems to have added a `template_changed?` check that may not exist. When creating a new course this fails with error: 

```ruby
undefined method `template_changed?' for #<Course:0x00005619f84cd958>
Did you mean?  template_course_id_changed?
```

### Steps to reproduce:

1. On latest `stable`, try making a course.
2. Enabling or disabling "Course Templates" feature doesn't seem to have effect.

### Expected behavior:

Course is created.

### Actual behavior:

Internal error due to undefined method `template_changed?`.

### Additional notes:

Trace:

```
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:180:in `block (2 levels) in halting_and_conditional'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:180:in `all?'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:183:in `run_callbacks'
/var/canvas/config/initializers/active_record.rb:1568:in `block in run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `block in scoping'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:784:in `_scoping'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `scoping'
/var/canvas/config/initializers/active_record.rb:1568:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:825:in `_run_validate_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.6/lib/active_model/validations.rb:406:in `run_validations!'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.6/lib/active_model/validations/callbacks.rb:117:in `block in run_validations!'
/var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:184:in `run_callbacks'
/var/canvas/config/initializers/active_record.rb:1568:in `block in run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `block in scoping'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:784:in `_scoping'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `scoping'
/var/canvas/config/initializers/active_record.rb:1568:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.6/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.6/lib/active_model/validations.rb:337:in `valid?'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:68:in `valid?'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:84:in `perform_validations'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:47:in `save'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:314:in `block in save'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:212:in `transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.8/lib/switchman/active_record/base.rb:43:in `block in transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.8/lib/switchman/active_record/relation.rb:104:in `activate'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.8/lib/switchman/active_record/base.rb:38:in `transaction'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:314:in `save'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/suppressor.rb:44:in `save'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.8/lib/switchman/active_record/base.rb:112:in `block in save'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `block in scoping'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:784:in `_scoping'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `scoping'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/switchman-2.0.8/lib/switchman/active_record/base.rb:112:in `save'
/var/canvas/app/controllers/courses_controller.rb:863:in `block in create'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/mime_responds.rb:205:in `respond_to'
/var/canvas/app/controllers/courses_controller.rb:862:in `create'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/abstract_controller/base.rb:195:in `process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/var/canvas/app/controllers/application_controller.rb:2744:in `manage_live_events_context'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/canvas/app/controllers/application_controller.rb:594:in `compute_http_cost'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/canvas/app/controllers/application_controller.rb:611:in `report_to_datadog'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:95:in `batch'
/var/canvas/app/controllers/application_controller.rb:589:in `batch_statsd'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/canvas/lib/temp_cache.rb:30:in `enable'
/var/canvas/app/controllers/application_controller.rb:585:in `enable_request_cache'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/canvas/app/controllers/application_controller.rb:579:in `set_locale'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:139:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/rescue.rb:22:in `process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/notifications.rb:180:in `block in instrument'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/notifications.rb:180:in `instrument'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.6/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/abstract_controller/base.rb:136:in `process'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionview-6.0.3.6/lib/action_view/rendering.rb:39:in `process'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal.rb:190:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_controller/metal.rb:254:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/journey/router.rb:32:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/journey/router.rb:32:in `serve'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/routing/route_set.rb:834:in `call'
/var/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:80:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-brotli-1.0.0/lib/rack/brotli/deflater.rb:34:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/chunked.rb:98:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/var/canvas/app/middleware/request_throttle.rb:66:in `block in call'
/var/canvas/app/middleware/request_throttle.rb:323:in `reserve_capacity'
/var/canvas/app/middleware/request_throttle.rb:61:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/var/canvas/gems/request_context/lib/request_context/session.rb:28:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/var/canvas/app/middleware/load_account.rb:31:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:101:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/rack/logger.rb:37:in `call_app'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/rack/logger.rb:28:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/var/canvas/gems/request_context/lib/request_context/generator.rb:71:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/var/canvas/app/middleware/prevent_non_multipart_parse.rb:35:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.6/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/engine.rb:527:in `call'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/railtie.rb:190:in `public_send'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/railtie.rb:190:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by ccutrer** [comment]
Either you have not run migrations, or you have bad database metadata cached somehow. This column was added in 307dfe09b94d3623efdb79f67c27e838ce84635e

**Comment by zjr** [comment]
I have triple checked that I have run migrations. Could you please explain how I might have bad database metadata cached?

**Comment by ccutrer** [comment]
Canvas aggressively cache database metadata in the configured Cache. If you have one of MultiCache/HACache or redis caching configured, the easiest way is to run `redis-cli flushall`. I'm hesitant to spend too much time digging in this area to get you a more targeted clearing command, since there is working in progress to significantly revamp how we cache column information.

**Comment by zjr** [comment]
Thank you very much, I'll give that a try.

**Comment by zjr** [comment]
Just realized I never responded to this… for posterity, flushing redis did the trick.
