### ISSUE TITLE
Got 500 (Internal Server Error) when click on courses, peoples, settings after update

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#1917]
I think it's a related to this issue https://github.com/instructure/canvas-lms/issues/1737

any suggestion for fix?
Last working tag release/2020-09-23.28

may be other too but next I tryed end of next month already was not working

Ubuntu 18.04
ruby 2.6 ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux-gnu]
nodejs v14.17.2
bundler 2.2.17
```
[CANVAS_ERRORS] EXCEPTION LOG
NoMethodError (undefined method `id' for nil:NilClass):
  /home/canvas/public_html/app/models/role.rb:233:in `block in all_enrollment_roles_for_account'
  /home/canvas/public_html/app/models/role.rb:231:in `map'
  /home/canvas/public_html/app/models/role.rb:231:in `all_enrollment_roles_for_account'
  /home/canvas/public_html/app/models/role.rb:331:in `course_role_data_for_account'
  /home/canvas/public_html/app/controllers/accounts_controller.rb:1454:in `course_user_search'
  /home/canvas/public_html/app/controllers/accounts_controller.rb:394:in `block (2 levels) in show'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
  /home/canvas/public_html/app/controllers/accounts_controller.rb:391:in `show'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
  /home/canvas/public_html/app/controllers/application_controller.rb:2775:in `manage_live_events_context'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  /home/canvas/public_html/app/controllers/application_controller.rb:608:in `compute_http_cost'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  /home/canvas/public_html/app/controllers/application_controller.rb:625:in `report_to_datadog'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/inst_statsd-2.1.6/lib/inst_statsd/statsd.rb:95:in `batch'
  /home/canvas/public_html/app/controllers/application_controller.rb:603:in `batch_statsd'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  /home/canvas/public_html/lib/temp_cache.rb:30:in `enable'
  /home/canvas/public_html/app/controllers/application_controller.rb:599:in `enable_request_cache'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  /home/canvas/public_html/app/controllers/application_controller.rb:593:in `set_locale'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'
  /home/canvas/public_html/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:80:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-brotli-1.0.0/lib/rack/brotli/deflater.rb:34:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/chunked.rb:98:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
  /home/canvas/public_html/app/middleware/request_throttle.rb:66:in `block in call'
  /home/canvas/public_html/app/middleware/request_throttle.rb:323:in `reserve_capacity'
  /home/canvas/public_html/app/middleware/request_throttle.rb:61:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  /home/canvas/public_html/gems/request_context/lib/request_context/session.rb:28:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
  /home/canvas/public_html/app/middleware/load_account.rb:49:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:28:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
  /home/canvas/public_html/gems/request_context/lib/request_context/generator.rb:71:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /home/canvas/public_html/app/middleware/prevent_non_multipart_parse.rb:35:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `public_send'
  /home/canvas/public_html/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'CONTEXT: {:extra=>{:request_id=>"0274c92b-bbd8-4a36-a0d4-e0150b28203e", :session_id=>"f3c35167a5a41bf245b8d13fb04056f9", :meta_headers=>"o=accounts;n=show;t=Account;i=1;", :request_context_id=>"0274c92b-bbd8-4a36-a0d4-e0150b28203e", :request_method=>:get, :format=>#<Mime::Type:0x00005563cf7af278 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=1143305489879591716>, "HTTP_ACCEPT"=>"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "HTTP_ACCEPT_ENCODING"=>"gzip, deflate, br", "HTTP_HOST"=>"canvas.mygtis.com", "HTTP_REFERER"=>"https://canvas.ms.com/", "HTTP_USER_AGENT"=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.203", "PATH_INFO"=>"/accounts/1", "QUERY_STRING"=>"?", "REQUEST_METHOD"=>"GET", "REQUEST_URI"=>"https://canvas.mis.com/accounts/1", "SERVER_NAME"=>"canvas.mygtis.com", "SERVER_PORT"=>"443", "SERVER_PROTOCOL"=>"HTTP/1.1", "REMOTE_ADDR"=>"212.79.122.71", "path_parameters"=>"{:controller=>\"accounts\", :action=>\"show\", :id=>\"1\"}", "query_parameters"=>"{}", "request_parameters"=>"{}", :user_agent=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 OPR/77.0.4054.203"}, :tags=>{:account_id=>10000000000001, :user_id=>10000000000001, :type=>nil, :response_code=>500}}
```

**Comment by LordRatte** [comment]
Is there an official place we can go to see the latest working release. My Docker building workflow is broken because stable doesn't seem to be reliable any more.

**Comment by amg-web** [comment]
some migration in september 2020 create problem. I can not fix it myself

**Comment by amg-web** [comment]
by experiment on test server I found that running in console
`Role.where(root_account_id: 0).update_all(root_account_id: 1)`

can somebody confirm that it's corrcet solution ?

**Comment by Ardena** [comment]
There should be a set of built-in roles for for the Site_admin account as well as your main account, so probably root_account_id: 1 and root_account_id: 2.  All of the built-in roles had root_account_ids added to them, and we created multiple copies of each per root account instead of using just one set, but the migration doesn't seem to have accurately linked the copies to the correct root accounts.

**Comment by amg-web** [comment]
It was extra role added and due to this migrations was broken
