### ISSUE TITLE
Production Installation  : Error in Compiling- Generating Assets

### ISSUE THREAD

**Issue by ravieway** [instructure/canvas-lms#1938]
### Summary:
I am trying to deploy a Canvas-Production in a VM (8GB)
When I tried to compile using 
RAILS_ENV=production bundle exec rake canvas:compile_assets

I get the error : error Command failed with exit code 2.

### Steps to reproduce:

sudo yarn install
RAILS_ENV=production bundle exec rake canvas:compile_assets

### Actual behavior:

[webpack-cli] Error: webpack build had warnings. Failing.
    at /var/canvas/frontend_build/baseWebpackConfig.js:322:17
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/var/canvas/node_modules/tapable/lib/Hook.js:154:20)
    at /var/canvas/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/var/canvas/node_modules/webpack/lib/Compiler.js:499:39)
    at /var/canvas/node_modules/webpack/lib/Compiler.js:298:10
    at /var/canvas/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/var/canvas/node_modules/tapable/lib/Hook.js:154:20)
    at /var/canvas/node_modules/webpack/lib/Compiler.js:482:27
    at /var/canvas/node_modules/neo-async/async.js:2818:7
    at done (/var/canvas/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
    at /var/canvas/node_modules/webpack/lib/Compiler.js:464:33
    at /var/canvas/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:180:23)
error Command failed with exit code 2.

**Comment by dengcen** [comment]
maybe you nodes version is wrong-------- 原始邮件 --------发件人： ravieway ***@***.***>日期： 2021年9月17日周五 半夜11:01收件人： instructure/canvas-lms ***@***.***>抄送： Subscribed ***@***.***>主    题： [instructure/canvas-lms] Production Installation  : Error in Compiling- Generating Assets (#1938)

Summary:
I am trying to deploy a Canvas-Production in a VM (8GB)
When I tried to compile using
RAILS_ENV=production bundle exec rake canvas:compile_assets
I get the error : error Command failed with exit code 2.
Steps to reproduce:
sudo yarn install
RAILS_ENV=production bundle exec rake canvas:compile_assets
Actual behavior:
[webpack-cli] Error: webpack build had warnings. Failing.
at /var/canvas/frontend_build/baseWebpackConfig.js:322:17
at AsyncSeriesHook.eval [as callAsync] (:27:1)
at AsyncSeriesHook.lazyCompileHook (/var/canvas/node_modules/tapable/lib/Hook.js:154:20)
at /var/canvas/node_modules/webpack/lib/Compiler.js:304:22
at Compiler.emitRecords (/var/canvas/node_modules/webpack/lib/Compiler.js:499:39)
at /var/canvas/node_modules/webpack/lib/Compiler.js:298:10
at /var/canvas/node_modules/webpack/lib/Compiler.js:485:14
at AsyncSeriesHook.eval [as callAsync] (:15:1)
at AsyncSeriesHook.lazyCompileHook (/var/canvas/node_modules/tapable/lib/Hook.js:154:20)
at /var/canvas/node_modules/webpack/lib/Compiler.js:482:27
at /var/canvas/node_modules/neo-async/async.js:2818:7
at done (/var/canvas/node_modules/neo-async/async.js:3522:9)
at AsyncSeriesHook.eval [as callAsync] (:6:1)
at /var/canvas/node_modules/webpack/lib/Compiler.js:464:33
at /var/canvas/node_modules/graceful-fs/graceful-fs.js:61:14
at FSReqCallback.oncomplete (fs.js:180:23)
error Command failed with exit code 2.
Additional notes:

**Comment by ravieway** [comment]
Yes  @dengcen it might be the issue. I used an Ubuntu 20.04 LTS instance. Rolled back to Ubuntu 10.04 LTS and it worked like a charm. Still I had to use a network timeout while installing yarn.
