### ISSUE TITLE
db:migrate:predeploy Error

### ISSUE THREAD

**Issue by damianoognissanti** [instructure/canvas-lms#2001]
### Summary:
I try to run db:migrate:predeploy but it doesn't work.

### Steps to reproduce:

 1. Run `RAILS_ENV=production bundle exec rake db:migrate:predeploy`

### Expected behavior:

 Migration to work

### Actual behavior:

** Invoke db:migrate:predeploy (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Invoke environment
** Execute db:load_config
** Execute db:migrate:predeploy
1: production:public
rake aborted!
Errno::EAFNOSUPPORT: Failed to open TCP connection to localhost:8500 (Address family not supported by protocol - socket(2) for "localhost" port 8500)
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:958:in `connect'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:88:in `perform_request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:44:in `block in call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:93:in `with_net_http_connection'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:39:in `call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/response.rb:8:in `call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/rack_builder.rb:143:in `build_response'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:387:in `run_request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:175:in `put'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/diplomat-2.5.1/lib/diplomat/rest_client.rb:272:in `send_put_request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/diplomat-2.5.1/lib/diplomat/event.rb:25:in `fire'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/diplomat-2.5.1/lib/diplomat/rest_client.rb:57:in `method_missing'
/usr/local/canvas/lib/active_support/cache/ha_store.rb:75:in `block in delete_entry'
/usr/local/canvas/lib/active_support/cache/ha_store.rb:74:in `each'
/usr/local/canvas/lib/active_support/cache/ha_store.rb:74:in `delete_entry'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:476:in `block in delete'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:686:in `block in instrument'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb:182:in `instrument'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:686:in `instrument'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:475:in `delete'
/usr/local/canvas/config/initializers/active_support.rb:30:in `delete'
/usr/local/canvas/lib/multi_cache.rb:23:in `delete'
/usr/local/canvas/lib/tasks/db.rake:11:in `block (2 levels) in <top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2) for "localhost" port 8500
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:958:in `connect'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/local/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:88:in `perform_request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:44:in `block in call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:93:in `with_net_http_connection'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:39:in `call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/response.rb:8:in `call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/rack_builder.rb:143:in `build_response'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:387:in `run_request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:175:in `put'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/diplomat-2.5.1/lib/diplomat/rest_client.rb:272:in `send_put_request'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/diplomat-2.5.1/lib/diplomat/event.rb:25:in `fire'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/diplomat-2.5.1/lib/diplomat/rest_client.rb:57:in `method_missing'
/usr/local/canvas/lib/active_support/cache/ha_store.rb:75:in `block in delete_entry'
/usr/local/canvas/lib/active_support/cache/ha_store.rb:74:in `each'
/usr/local/canvas/lib/active_support/cache/ha_store.rb:74:in `delete_entry'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:476:in `block in delete'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:686:in `block in instrument'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/notifications.rb:182:in `instrument'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:686:in `instrument'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/cache.rb:475:in `delete'
/usr/local/canvas/config/initializers/active_support.rb:30:in `delete'
/usr/local/canvas/lib/multi_cache.rb:23:in `delete'
/usr/local/canvas/lib/tasks/db.rake:11:in `block (2 levels) in <top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/bin/rake:23:in `load'
/usr/local/canvas/vendor/bundle/ruby/2.7.0/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:migrate:predeploy

**Comment by damianoognissanti** [comment]
I have tried to open port 8500, but it still doesn't work.

**Comment by damianoognissanti** [comment]
Fixed it by changing the dynamic settings 

`cp config/dynamic_settings.yml.example config/dynamic_settings.yml`

and rerunning the rake canvas:compile_assets.
