### ISSUE TITLE
gradebook page: Uncaught Error: SlickGrid requires a valid container, null does not exist in the DOM.

### ISSUE THREAD

**Issue by akaDJon** [instructure/canvas-lms#2013]
### Summary:  
When opening gradebook page happens JS fail. 
log in console: Uncaught Error: SlickGrid requires a valid container, null does not exist in the DOM.
    at init (74-c-337638ddcd.js:423:35)
    at new SlickGrid (74-c-337638ddcd.js:1346:1)
    at Qi.initialize (gradebook-c-7f9290dc2a.js:1603:11)
    at $a.createGrid (gradebook-c-7f9290dc2a.js:2939:20)
    at $a.initGrid (gradebook-c-7f9290dc2a.js:2938:13)
    at $a.finishRenderingUI (gradebook-c-7f9290dc2a.js:2598:113)
    at Object.<anonymous> (gradebook-c-7f9290dc2a.js:909:130)
    at m (main-e-5a83ede1fb.js:6010:33)
    at Object.fireWith [as resolveWith] (main-e-5a83ede1fb.js:6026:104)
    at Object.<anonymous> (main-e-5a83ede1fb.js:6042:87)

![photo_2022-02-07_09-19-12](https://user-images.githubusercontent.com/19344497/152719254-1b9782ce-3e60-4d3f-a016-d1b4abad4b54.jpg)
![photo_2022-02-07_09-18-53](https://user-images.githubusercontent.com/19344497/152719282-bb717e61-a507-4e4a-bb7a-a7fc4000866e.jpg)

### Steps to reproduce:

no stable reproduce, sorry
most people everything ok, but several have this problem
 1. 
 2.
 3.

### Expected behavior:
successful load gradebook results

### Actual behavior:
js fail and infinity loading page

**Comment by aaronshaf** [comment]
Troubleshooting:

* Does the error persist on reload?
* What does `document.getElementById('gradebook_grid')` return in the browser console?

**Comment by aaronshaf** [comment]
@akaDJon Ah, you're on `release/2020-11-18.29`. Try the latest release?

**Comment by akaDJon** [comment]
> Troubleshooting:
> 
> * Does the error persist on reload?
> * What does `document.getElementById('gradebook_grid')` return in the browser console?

not persist. one load everything ok, the next load fail, and next again ok
![image](https://user-images.githubusercontent.com/19344497/152909093-75f3484e-10e3-4f36-a0d1-670d203cc7b8.png)

**Comment by akaDJon** [comment]
> @akaDJon Ah, you're on `release/2020-11-18.29`. Try the latest release?

no. it's difficult. but this error appeared recently. whole a year everything was ok

**Comment by jmm-podium** [comment]
We're seeing this issue as well on `origin/stable/2021-08-18` of the code when using Chrome.

**Comment by jmm-podium** [comment]
@akaDJon  - Looking the Canvas Release Notes it appears to be an issue that they've fixed in a more recent version.

https://community.canvaslms.com/t5/Known-Issues/Various-pages-fail-to-load-completely-in-Canvas-when-using/ta-p/500973

> This behavior is resolved in the 2021-12-15 deploy.

I was able to deploy a newer version of canvas `origin/stable/2022-02-16` and I am not able to reproduce the issue any longer.
