### ISSUE TITLE
Error during step 3 of LTI 1.3 launch "The launch has either expired or already been consumed"

### ISSUE THREAD

**Issue by drscottlobo** [instructure/canvas-lms#2050]
### Summary: 

I'm receiving an error at Step 3 of the LTI 1.3 flow with my LTI running an express server. Canvas is running on localhost:3000 and my LTI is running with a self-signed certificate on https://localhost:8000. The OIDC launch successfully launches the tool and then I send a redirect back to my local instance of Canvas http://localhost:3000/api/lti/authorize_redirect with the response body. Instead of receiving a JWT back from Canvas my auth route gets a JSON response with an error 'The launch has either expired or already been consumed'. I'm having trouble figuring out what's going wrong as that error is not very informative. Has anyone encountered this one? 

### Additional notes:

Here is my oidc route: 

`router.post('/openid', async (req, res) => {
    req.session.login_request = req.body;
    const errors = isValidLogin(req);

    if (errors.length === 0) {
        //// TODO check for platform in DB
        const response = {
            scope: 'openid',
            response_type: 'id_token',
            client_id: req.body.client_id,
            redirect_uri: 'https://localhost:8000/lti3/auth', /// local LTI app 
            login_hint: req.body.login_hint,
            state: uuidv4(),
            response_mode: 'form_post',
            nonce: uuidv4(),
            prompt: 'none',
        };
        if (req.body.hasOwnProperty('lti_message_hint')) {
            response.lti_message_hint = req.body.lti_message_hint;
        }
        req.session.login_response = response;
            const redirectUrl = url.format({
                pathname: 'http://localhost:3000/api/lti/authorize_redirect', //// local canvas instance 
                query: response,
            });
            return res.redirect(redirectUrl);
    }
});`

And here is my JSON for the JWK on my lti's side:

`{
keys: [
{
kty: "RSA",
kid: "TTO0gkzQ2naFR-pB96xtlWUm8hCztcQBm-X-Krm0F8E",
use: "sig",
alg: "RS256",
e: "AQAB",
n: "pTfYEdOhIwgBQrF-Y6CkhoLr7YrJU4Od7jfFAFa1pvq-wSXQXNFza6Tn5AapKYQ47DRr9aRVd4OlK7LCyFqupBm02yhVctR0sqyb9YXLlh8pjkqyP_wMQGk7mdZjA2fUiNjuD5FtyxMXUjdCA-SzuHq42CWUF66vh8Ca0M4tG73j03GWJnyJ_QscxSOes3OGXrMbkdUf49kACB32VYHRIVsIbWKbxosYV5vaqOyNFRJNPbTaRh5AnvJ3TYzPCVb1jnWVriuibKs75c0_R21eckPWxacpDsTawyNVZpT6UhEdF3EbqAaUXI8pORp4roZkTtvat69SgyngRtDbGieopw"
}
]
}`

Would really appreciate some help!

Thanks.

**Comment by drscottlobo** [comment]
Hi ymaerschalck! No word on exactly what the issue is, but my suspicion is that is has something to do with the quickstart version not having the Redis cache set up and I couldn't get it working even after following the directions here: https://github.com/instructure/canvas-lms/wiki/Quick-Start#performance-tweaks 

But this might help: I was able to get the Docker version of Canvas up and running using [these instructions](https://github.com/instructure/canvas-lms/blob/master/doc/docker/developing_with_docker.md) with a few additional tweaks from a more experienced developer and that version of Canvas did NOT throw the error(!), I'm guessing because it has the Redis cache (and who knows what else) already configured correctly to send back the correct JWTs.

I'm on a Mac so here's the changes I had to make for the Docker setup to work: 

1. Download the repo and Docker 
2. Install Docker Desktop and run it, make sure Preferences > Resources > Memory is set to 8 gigs or higher
3. Then run the setup script from the Terminal. If the setup script doesn't recognize Docker from the terminal (it couldn't find it on mine), this hack from my friend worked: Comment out line 52 of docker_desktop_setup.sh like this: # exit 1

4. Now you should be able to successfully run the setup script from the repo directory: ./script/docker_dev_setup.sh (note: it takes forever to build)
5. Then run 'mutagen-compose up -d' and visit http://canvas.docker in your browser- this also took a good 30 seconds to a minute to load the page the first time...But this version should work for LTI 1.3 launches! 

Hope this works for you, it was a serious week of hair-pulling trying to get it to work!

**Comment by drscottlobo** [comment]
I believe I am running the master branch from less than a month ago. 

I did get a Bitnami package working on Google Cloud through Bitnami's cloud integrations, but I think the package on Bitnami is built from the quickstart (and was pretty old), so if I remember correctly it had the exact same error I was getting originally.

**Comment by ymaerschalck** [comment]
Ok, I also tried the Bitnami package on AWS and got it running succesfully.
When comparing to our own hosted version, we were able to correct everything there by installing the latest version of redis and fixing the redis and cache config files for canvas. 
Then the only error that remained was fixed by implementing the fix from https://community.canvaslms.com/t5/Canvas-Developers-Group/Canvas-LTI-1-3-Error-Unknown-Key-Type/m-p/390285/highlight/true#M6345

Now we've got a working LTI1.3 implementation

**Comment by jtong99** [comment]
@drscottlobo Hi, I am facing with this issue. Have you found any solutions? Thanks.

**Comment by AwesomeDummy** [comment]
I faced the exact same problem with the same exact error message.

I was running Canvas LMS using docker and used to launch the canvas LMS container with redis and postgres containers. They were in the same network so they were able to communicate.

The solutions of @drscottlobo @ymaerschalck pointed me in the direction of checking if my canvas LMS instance was able to talk to the redis instance.

Turns out, it wasn't. So when I fixed the config, the error was resolved.

So folks in the future, if this issue haunts you better check your redis configs.

**Comment by AwesomeDummy** [comment]
For my case, canvas LMS and redis were two different docker containers in the same network. I debugged and found out that I was missing properly config for development mode inside `config/redis.yml`.

So at the end of the day it was a issue that arose out of misconfiguration for me.

In hindsight, I guess I should have read the canvas-lms code better to avoid misconfiguration. Will keep this is mind for future projects at least. 😄

**Comment by rutvikgadhiya** [comment]
Anyone get the solution for this?.
Because I'm facing same issue. 
Thanks.

**Comment by AwesomeDummy** [comment]
What is your setup? If you elaborate probably can help.

First check if your canvas is able to talk to postgres db. In my case it wasn't and that was the reason I faced this issue.

@rutvikgadhiya

**Comment by ghost** [comment]
@rutvikgadhiya 

Given that you're able to login in to the canvas application that you've setup most likely means you've set it up correctly and database connectivity is fine.

1. But to be able to tell you if canvas is properly communicating with the PostgreSQL I need to know what the setup is. Is the 
PostgreSQL another docker container and are they in the same docker network?

2. Yes, you need to check `redis.yml` and verify the redis configuration. (In my case, the redis connection was misconfigured because of which I faced the above issue of LTI launch failure because Canvas uses redis to keep track of LTI launch keys)

3. If database connection is misconfigured you won't be able to login to Canvas, as simple as that or any other page you go to will result in an exception being thrown because data won't be properly fetched.

**Comment by rutvikgadhiya** [comment]
@AwesomeDummy , I have check the production.log file & found following thing into logs.

Lti::IMS::InvalidLaunch (no payload found in cache):
  /var/canvas/app/controllers/lti/ims/authentication_controller.rb:204:in `cached_launch_with_nonce'
  /var/canvas/app/controllers/lti/ims/authentication_controller.rb:224:in `id_token'
  /var/canvas/app/controllers/lti/ims/authentication_controller.rb:162:in `validate_launch_eligibility!'

**Comment by ghost** [comment]
@rutvikgadhiya you didn't tell me if your redis config is fine or not.

The logs you pasted are justifying my suspicion of redis misconfiguration. 

To verify do the following:-

1. Pull the canvas source-code to your local.
2. In `redis_message_client.rb`, inside function `fetch_and_delete_launch` check what does `Canvas.redis_enabled` return.

Pretty sure its returning false, which means your redis configuration is bad.

I debugged in this way and found my redis config was bad, once I fixed it. I was able to get rid of the issue.
