### ISSUE TITLE
Error Compile Assets

### ISSUE THREAD

**Issue by robertoromeroGA** [instructure/canvas-lms#2077]
It was installed and configured correctly, today we have no problem in production but we need to compile the assets and I have this error.

The server has 16gb of RAM and I have tried stopping processes in case the problem was the RAM and nothing. No matter the way, this problem always appears

When you perform the following command to compile the assets in production: `sudo RAILS_ENV=production bundle exec rake canvas:compile_assets --trace`, you get the following error:

```
rake aborted!
Parallel::DeadWorker: Parallel::DeadWorker
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:86:in 'rescue in work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:83:in 'work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:411:in 'block (4 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:527:in 'with_instrumentation'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:410:in 'block (3 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'loop'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'block (2 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222:in 'block (4 levels) in in_threads'

Caused by:
EOFError: end of file reached
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/core_ext/marshal.rb:6:in 'load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/core_ext/marshal.rb:6:in 'load'
/opt/bitnami/canvaslms/gems/canvas_ext/lib/canvas_ext/marshal.rb:27:in 'load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:84:in 'work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:411:in 'block (4 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:527:in 'with_instrumentation'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:410:in 'block (3 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'loop'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'block (2 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222:in 'block (4 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
```

**Comment by robertoromeroGA** [comment]
well really what I wanted was to compile the javascript elements, for that if you see the command from the package.json is: yarn run webpack-production, what is ruby on rails code most of the time with restarting the service works.

I hope it helps you with this :)

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
