### ISSUE TITLE
db:initial_setup - rake aborted, StandardError

### ISSUE THREAD

**Issue by huangdengpan** [instructure/canvas-lms#2123]
When run RAILS_ENV=production bundle exec rake db:initial_setup, meets errors as below.

Please help me o(╯□╰)o

`==  EnsureDummyEnrollmentTerm: migrated (0.0103s) =============================

==  EnsureDummyCourse: migrating ==============================================
==  EnsureDummyCourse: migrated (0.1440s) =====================================

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown attribute 'singleton' for Delayed::Backend::ActiveRecord::Job.
/opt/canvas/vendor/bundle/ruby/2.7.0/gems/activemodel-6.1.4.6/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
/opt/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/attribute_assignment.rb:13:in `each'
/opt/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.7.0/gems/activemodel-6.1.4.6/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/core.rb:510:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.7.0/gems/aroi-0.0.7/lib/ar`

<img width="898" alt="image" src="https://user-images.githubusercontent.com/16663404/203469322-8a9f3de2-2c48-482a-8d95-4a801f874725.png">

**Comment by Musicminion** [comment]
Me Too!

**Comment by huangdengpan** [comment]
@Musicminion 你已经参加工作了吗？

**Comment by huangdengpan** [comment]
@Musicminion 这个在部署文档里有说明，只不过被大家忽略了。重新看一下文档里的这个初始化数据库的地方有说明如何处理。

**Comment by Musicminion** [comment]
> @Musicminion 这个在部署文档里有说明，只不过被大家忽略了。重新看一下文档里的这个初始化数据库的地方有说明如何处理。

你好哇！感谢回复呜呜！看到这个名字瞬间就一股熟悉感了（是交大的老师嘛😂我记得在canvaslms的社区见到过！）

目前在读大三，当初部署的时候还是大二下学期（canvas应该是我部署的第一个app），当时很多东西还不太熟悉，其实现在看起来之前问的问题啊还有写的教程文档有点naive了😂 前些天刚试了一遍，虽然一些bug也能解决了！

非常感谢！

**Comment by huangdengpan** [comment]
它里面的组件版本会经常更新，ruby , bundler, nodejs之类的。官方文档有时候也是滞后的，得多尝试才行。

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
