### ISSUE TITLE
Issue during compilation in production installation

### ISSUE THREAD

**Issue by anirbandutta9** [instructure/canvas-lms#2138]
### Steps to reproduce:

 1.  Start Installing canvas as per production documentation
 2.  Run this to compile assets:  RAILS_ENV=production bundle exec rake canvas:compile_assets
 3.  It will show the below error: 

```

webpack 5.75.0 compiled with 2 errors in 127121 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
assets by status 35.5 MiB [cached] 1009 assets
orphan modules 35.5 MiB [orphan] 10208 modules
runtime modules 38 KiB 16 modules
built modules 47.8 MiB [built]
  modules by path ./node_modules/ 21.1 MiB 2166 modules
  modules by path ./ui/ 15.1 MiB
    javascript modules 14.6 MiB 902 modules
    json modules 484 KiB 48 modules
  modules by path ./packages/ 11.6 MiB
    javascript modules 11.1 MiB 349 modules
    json modules 475 KiB 55 modules
  modules by path ./app/stylesheets/base/*.css 4.45 KiB
    ./app/stylesheets/base/_custom_mediaelementplayer.css 1.14 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./app/stylesheets/base/_custom_mediaelementplayer.css 3.31 KiB [built] [code generated]
  + 5 modules

LOG from webpack.FileSystemInfo
<w> Managed item /var/canvas/node_modules/bundles-generated.js isn't a directory or doesn't contain a package.json (see snapshot.managedPaths option)
+ 12 hidden lines

ERROR in ./ui/features/outcome_alignments/index.js 32:33-48
export 'AlignmentButton' (imported as 'AlignmentButton') was not found in '@instructure/outcomes-ui' (possible exports: AlignmentWidget, OutcomeAlignments, Out                  comeCount, OutcomeList, OutcomesPerStudentReport)
 @ ./node_modules/bundles-generated.js
 @ ./ui/index.js 30:0-43 52:26-36 53:27-37 80:49-59

ERROR in ./node_modules/graphql-language-service-interface/esm/getDiagnostics.js 58:72-94
export 'NoDeprecatedCustomRule' (imported as 'NoDeprecatedCustomRule') was not found in 'graphql' (possible exports: BREAK, BreakingChangeType, DEFAULT_DEPRECA                  TION_REASON, DangerousChangeType, DirectiveLocation, ExecutableDefinitionsRule, FieldsOnCorrectTypeRule, FragmentsOnCompositeTypesRule, GraphQLBoolean, GraphQL                  DeprecatedDirective, GraphQLDirective, GraphQLEnumType, GraphQLError, GraphQLFloat, GraphQLID, GraphQLIncludeDirective, GraphQLInputObjectType, GraphQLInt, Gra                  phQLInterfaceType, GraphQLList, GraphQLNonNull, GraphQLObjectType, GraphQLScalarType, GraphQLSchema, GraphQLSkipDirective, GraphQLString, GraphQLUnionType, Kin                  d, KnownArgumentNamesRule, KnownDirectivesRule, KnownFragmentNamesRule, KnownTypeNamesRule, LoneAnonymousOperationRule, LoneSchemaDefinitionRule, NoFragmentCyc                  lesRule, NoUndefinedVariablesRule, NoUnusedFragmentsRule, NoUnusedVariablesRule, OverlappingFieldsCanBeMergedRule, PossibleFragmentSpreadsRule, PossibleTypeExt                  ensionsRule, ProvidedRequiredArgumentsRule, ScalarLeafsRule, SchemaMetaFieldDef, SingleFieldSubscriptionsRule, Source, TokenKind, TypeInfo, TypeKind, TypeMetaF                  ieldDef, TypeNameMetaFieldDef, UniqueArgumentNamesRule, UniqueDirectiveNamesRule, UniqueDirectivesPerLocationRule, UniqueEnumValueNamesRule, UniqueFieldDefinit                  ionNamesRule, UniqueFragmentNamesRule, UniqueInputFieldNamesRule, UniqueOperationNamesRule, UniqueOperationTypesRule, UniqueTypeNamesRule, UniqueVariableNamesR                  ule, ValidationContext, ValuesOfCorrectTypeRule, VariablesAreInputTypesRule, VariablesInAllowedPositionRule, __Directive, __DirectiveLocation, __EnumValue, __F                  ield, __InputValue, __Schema, __Type, __TypeKind, assertAbstractType, assertCompositeType, assertDirective, assertEnumType, assertInputObjectType, assertInputT                  ype, assertInterfaceType, assertLeafType, assertListType, assertNamedType, assertNonNullType, assertNullableType, assertObjectType, assertOutputType, assertSca                  larType, assertSchema, assertType, assertUnionType, assertValidName, assertValidSchema, assertWrappingType, astFromValue, buildASTSchema, buildClientSchema, bu                  ildSchema, coerceInputValue, coerceValue, concatAST, createLexer, createSourceEventStream, defaultFieldResolver, defaultTypeResolver, doTypesOverlap, execute,                   extendSchema, findBreakingChanges, findDangerousChanges, findDeprecatedUsages, formatError, getDescription, getDirectiveValues, getIntrospectionQuery, getLocat                  ion, getNamedType, getNullableType, getOperationAST, getOperationRootType, getVisitFn, graphql, graphqlSync, introspectionFromSchema, introspectionQuery, intro                  spectionTypes, isAbstractType, isCompositeType, isDefinitionNode, isDirective, isEnumType, isEqualType, isExecutableDefinitionNode, isInputObjectType, isInputT                  ype, isInterfaceType, isIntrospectionType, isLeafType, isListType, isNamedType, isNonNullType, isNullableType, isObjectType, isOutputType, isRequiredArgument,                   isRequiredInputField, isScalarType, isSchema, isSelectionNode, isSpecifiedDirective, isSpecifiedScalarType, isType, isTypeDefinitionNode, isTypeExtensionNode,                   isTypeNode, isTypeSubTypeOf, isTypeSystemDefinitionNode, isTypeSystemExtensionNode, isUnionType, isValidJSValue, isValidLiteralValue, isValidNameError, isValue                  Node, isWrappingType, lexicographicSortSchema, locatedError, parse, parseType, parseValue, print, printError, printIntrospectionSchema, printLocation, printSch                  ema, printSourceLocation, printType, responsePathAsArray, separateOperations, specifiedDirectives, specifiedRules, specifiedScalarTypes, stripIgnoredCharacters                  , subscribe, syntaxError, typeFromAST, validate, validateSchema, valueFromAST, valueFromASTUntyped, version, versionInfo, visit, visitInParallel, visitWithType                  Info)
 @ ./node_modules/graphql-language-service-interface/esm/index.js 4:0-33 4:0-33
 @ ./node_modules/codemirror-graphql/hint.js
 @ ./node_modules/graphiql/dist/components/QueryEditor.js 133:6-40
 @ ./node_modules/graphiql/dist/components/GraphiQL.js 30:19-43
 @ ./node_modules/graphiql/dist/index.js 12:0-58
 @ ./ui/features/graphiql/react/GraphiQLApp.js 21:0-32 92:41-49 100:25-41 100:73-88 104:26-41 108:26-41
 @ ./ui/features/graphiql/index.js 23:0-46 26:68-79
 @ ./node_modules/bundles-generated.js
 @ ./ui/index.js 30:0-43 52:26-36 53:27-37 80:49-59

webpack 5.75.0 compiled with 2 errors in 262829 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rake aborted!
Parallel::UndumpableException: RuntimeError: Error running js:webpack_production:
ABORTING
/var/canvas/lib/tasks/js.rake:17:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry/rake.rb:26:in `execute'
/var/canvas/lib/tasks/canvas.rake:79:in `block (6 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:12:in `log_time'
/var/canvas/lib/tasks/canvas.rake:82:in `block (5 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:587:in `call_with_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:557:in `process_incoming_jobs'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:537:in `block in worker'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:10:in `block in fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:8:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:8:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:528:in `worker'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:519:in `block in create_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:518:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:518:in `each_with_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:518:in `create_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:457:in `work_in_processes'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/parallel-1.22.0/lib/parallel.rb:294:in `map'
/var/canvas/lib/tasks/canvas.rake:75:in `block (4 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:74:in `each'
/var/canvas/lib/tasks/canvas.rake:74:in `block (3 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:73:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry/rake.rb:24:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

```

### Additional notes:
OS: ubuntu 18.04 LTS

**Comment by lephat08** [comment]
I can not compile_assets in production
OS: Ubuntu 22.04LTS
