### ISSUE TITLE
Error compiling assets in docker file on Ubuntu 22.04

### ISSUE THREAD

**Issue by sijpkes** [instructure/canvas-lms#2174]
### Summary:
./script/docker_dev_setup.sh fails on Ubuntu 22 Compiling assets

Compile assets fails

```bash
> Now we can set up Canvas!

> Copying Canvas docker configuration...
OK to run 'cp docker-compose/config/*.yml config/'? [y/n] y

> Setup override yaml and .env...

> docker-compose.override.yml already exists, skipping copy of default configuration!
.env file exists, would you like to reset it to default? [y/n] y

> Setting up default .env configuration

> Building docker images...    [DONE]

> Starting docker containers...[DONE]

> Building assets...

> > Bundle install...  [DONE]

> > Yarn install....   [DONE]

> > Compile assets.... [FAIL]

  /o\ Something went wrong. Check /home/paul/workspace/canvas-lms/log/docker_dev_setup.log for details.
```
Contents of docker_dev_setup.log
```bash
/home/docker/.gem/gems/spring-4.0.0/lib/spring/client.rb:30:in `run'
/home/docker/.gem/gems/spring-4.0.0/bin/spring:49:in `<top (required)>'
/home/docker/.gem/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `load'
/home/docker/.gem/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
/usr/src/app/bin/spring:21:in `require'
/usr/src/app/bin/spring:21:in `<top (required)>'
bin/rails:5:in `load'
bin/rails:5:in `<main>'
(See full trace by running task with --trace)
```
### Steps to reproduce:

 1. Run the ./script/docker_dev_setup.sh file from a bash prompt

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
