### ISSUE TITLE
problem with importing course

### ISSUE THREAD

**Issue by djspid1** [instructure/canvas-lms#2178]
Please, Any soultion for this error when trying to import course.
Error report : 
*************
No such file or directory - file
category: content_migration
created at: 2023-03-27 01:15:46 -0600

attempts: 0
handler: --- !ruby/struct:CC::Importer::CCWorker migration_id: 13
hostname: anappios
id: 1822388
job_tag: CC::Importer::CCWorker#perform
max_attempts: 1
pid: 1387
priority: 20
process_type: BackgroundJob
request_id: 1822388
run_at: 2023-03-27 07:15:46 UTC
session_id: anappios:1387
shard_id: 1
source:
strand: migrations:import_content/api_in_app_10000000000001
type: content_migration
worker_name:
`<pre>
No such file or directory - file

        /var/canvas/gems/canvas_mimetype_fu/lib/canvas_mimetype_fu/mimetype_fu.rb:28:in `popen'
/var/canvas/gems/canvas_mimetype_fu/lib/canvas_mimetype_fu/mimetype_fu.rb:28:in `mime_type?'
/var/canvas/gems/canvas_unzip/lib/canvas_unzip.rb:121:in `each_entry'
/var/canvas/gems/canvas_unzip/lib/canvas_unzip.rb:84:in `extract_archive'
/var/canvas/lib/canvas/migration/archive.rb:127:in `unzip_archive'
/var/canvas/lib/canvas/migration/migrator.rb:60:in `unzip_archive'
/var/canvas/lib/cc/importer/canvas/converter.rb:46:in `export'
/var/canvas/lib/cc/importer/cc_worker.rb:53:in `perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/backend/base.rb:312:in `block in invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-inst_jobs-1.0.2/lib/sentry/inst_jobs/plugin.rb:24:in `block (3 levels) in <class:Plugin>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry/hub.rb:58:in `with_scope'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry-ruby.rb:308:in `with_scope'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-inst_jobs-1.0.2/lib/sentry/inst_jobs/plugin.rb:14:in `block (2 levels) in <class:Plugin>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/backend/base.rb:309:in `invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/backend/base.rb:92:in `block in invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/backend/base.rb:92:in `invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:219:in `block (2 levels) in perform'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:213:in `block in perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:22:in `block (2 levels) in enable_perform_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing.rb:8:in `block in report_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst_statsd-2.2.0/lib/inst_statsd/statsd.rb:91:in `time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing.rb:8:in `report_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:21:in `block in enable_perform_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:13:in `block (2 levels) in enable_batching'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst_statsd-2.2.0/lib/inst_statsd/statsd.rb:97:in `batch'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:12:in `block in enable_batching'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/config/initializers/delayed_job.rb:165:in `block (2 levels) in <top (required)>'
/var/canvas/lib/temp_cache.rb:30:in `enable'
/var/canvas/config/initializers/delayed_job.rb:164:in `block in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:210:in `perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:180:in `block (2 levels) in run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:285:in `block in configure_for_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:54:in `running_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:281:in `configure_for_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:179:in `block in run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:171:in `run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:26:in `block in run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:26:in `run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:135:in `block in start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:134:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:19:in `block in start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:19:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:113:in `block in spawn_worker'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:125:in `block in fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:10:in `block in fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:8:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:8:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:27:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:121:in `fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:112:in `spawn_worker'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:92:in `block (2 levels) in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:92:in `times'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:92:in `block in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:91:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:91:in `spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:48:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/cli.rb:111:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/cli.rb:36:in `run'
/var/canvas/script/delayed_job:11:in `<main>'
</pre>`

**Comment by dqcuong93** [comment]
Try installing "file" package. If you are using Ubuntu system, try this:
`sudo apt install file -y`

After successfully install, importing function should work properly.

**Comment by djspid1** [comment]
Thanks for your reply but i got another issue :
  Permission denied @ dir_s_mkdir - /var/canvas/tmp/files/0000/0169

        /usr/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'
/usr/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
/usr/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
/usr/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
/usr/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
/usr/lib/ruby/2.7.0/fileutils.rb:211:in `each'
/usr/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
/var/canvas/gems/attachment_fu/lib/attachment_fu/backends/file_system_backend.rb:130:in `save_to_storage'
/var/canvas/gems/attachment_fu/lib/attachment_fu.rb:566:in `block in after_process_attachment'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/after_transaction_commit-2.2.2/lib/after_transaction_commit/transaction.rb:22:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/after_transaction_commit-2.2.2/lib/after_transaction_commit/transaction.rb:22:in `commit_records'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:304:in `block in commit_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/transaction.rb:294:in `commit_transaction'
/var/canvas/config/initializers/active_record.rb:2211:in `block in within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/canvas/config/initializers/active_record.rb:2182:in `within_new_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/active_record/base.rb:219:in `block (2 levels) in with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/database_server.rb:153:in `unguard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/active_record/base.rb:219:in `block in with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/active_record/base.rb:217:in `with_transaction_returning_status'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/transactions.rb:298:in `save'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/suppressor.rb:44:in `save'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/active_record/base.rb:189:in `save'
/var/canvas/lib/cc/cc_exporter.rb:106:in `export'
/var/canvas/app/models/content_export.rb:199:in `export_course'
/var/canvas/app/models/content_export.rb:153:in `block in export'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/app/models/content_export.rb:141:in `export'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/message_sending.rb:125:in `block (2 levels) in handle_asynchronously'
/var/canvas/lib/canvas/migration/worker/course_copy_worker.rb:45:in `block (2 levels) in perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/lib/canvas/migration/worker/course_copy_worker.rb:44:in `block in perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/lib/canvas/migration/worker/course_copy_worker.rb:32:in `perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/backend/base.rb:312:in `block in invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-inst_jobs-1.0.2/lib/sentry/inst_jobs/plugin.rb:24:in `block (3 levels) in <class:Plugin>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry/hub.rb:58:in `with_scope'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry-ruby.rb:308:in `with_scope'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-inst_jobs-1.0.2/lib/sentry/inst_jobs/plugin.rb:14:in `block (2 levels) in <class:Plugin>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/backend/base.rb:309:in `invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/backend/base.rb:92:in `block in invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/backend/base.rb:92:in `invoke_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:219:in `block (2 levels) in perform'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:213:in `block in perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:22:in `block (2 levels) in enable_perform_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing.rb:8:in `block in report_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst_statsd-2.2.0/lib/inst_statsd/statsd.rb:91:in `time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing.rb:8:in `report_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:21:in `block in enable_perform_timing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:13:in `block (2 levels) in enable_batching'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst_statsd-2.2.0/lib/inst_statsd/statsd.rb:97:in `batch'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-statsd-2.2.0/lib/inst_jobs_statsd/stats/timing/perform.rb:12:in `block in enable_batching'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/config/initializers/delayed_job.rb:165:in `block (2 levels) in <top (required)>'
/var/canvas/lib/temp_cache.rb:30:in `enable'
/var/canvas/config/initializers/delayed_job.rb:164:in `block in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:98:in `block in add'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:210:in `perform'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:180:in `block (2 levels) in run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:285:in `block in configure_for_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:54:in `running_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:281:in `configure_for_job'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:179:in `block in run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:171:in `run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:26:in `block in run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:26:in `run'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:135:in `block in start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:74:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:79:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/worker.rb:134:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:19:in `block in start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.1.3/lib/switchman/shard.rb:474:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/delayed/worker.rb:19:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:113:in `block in spawn_worker'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:125:in `block in fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:10:in `block in fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:8:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:8:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/fork_tracker.rb:27:in `fork'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:121:in `fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:112:in `spawn_worker'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:92:in `block (2 levels) in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:92:in `times'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:92:in `block in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:91:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:91:in `spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/pool.rb:48:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/cli.rb:111:in `start'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/inst-jobs-3.1.5/lib/delayed/cli.rb:50:in `run'
/var/canvas/script/delayed_job:11:in `<main>'

**Comment by jlmbaka** [comment]
> Try installing "file" package. If you are using Ubuntu system, try this: `sudo apt install file -y`
> 
> After successfully install, importing function should work properly.

Also works on Debian. Thanks
