### ISSUE TITLE
collation "public.und-u-kn-true" for encoding "UTF8" does not exist

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#2197]
while update canvas instance get this error:
Any suggestions?

```
RAILS_ENV=production bundle exec rake db:migrate:predeploy
1: production:public
==  AddPg12CollationIndexes: migrating ========================================
-- add_index(:users, "(sortable_name COLLATE public.\"und-u-kn-true\"), id", {:name=>:index_users_on_sortable_name, :algorithm=>:concurrently, :if_not_exists=>true})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::UndefinedObject: ERROR:  collation "public.und-u-kn-true" for encoding "UTF8" does not exist
LINE 1: ...ortable_name" ON "public"."users" ((sortable_name COLLATE pu...
                                                             ^
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/sharded_instrumenter.rb:22:in `instrument'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/abstract_adapter.rb:37:in `log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `execute'
/var/canvas/config/initializers/postgresql_adapter.rb:343:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:448:in `add_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-pg-extensions-0.4.4/lib/active_record/pg_extensions/pessimistic_migrations.rb:95:in `add_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:932:in `block in method_missing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `block in say_with_time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `say_with_time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:921:in `method_missing'
/var/canvas/db/migrate/20230330205029_add_pg12_collation_indexes.rb:34:in `up'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `public_send'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:853:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:852:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:665:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1046:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1360:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1413:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1359:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1659:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1432:in `block in with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/migration.rb:40:in `block in with_advisory_lock_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/migration.rb:40:in `with_advisory_lock_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1428:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `migrate'
/var/canvas/lib/tasks/canvas.rake:190:in `block (3 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/database_server.rb:153:in `unguard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:83:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:214:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:484:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:208:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/relation/delegation.rb:88:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/relation/delegation.rb:88:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:204:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:79:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/database_server.rb:153:in `unguard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:77:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/guardrail-3.0.2/lib/guard_rail.rb:11:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:374:in `with_role_and_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:156:in `connected_to'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/guardrail-3.0.2/lib/guard_rail.rb:11:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/guard_rail.rb:13:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:76:in `block in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry/rake.rb:26:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  collation "public.und-u-kn-true" for encoding "UTF8" does not exist
LINE 1: ...ortable_name" ON "public"."users" ((sortable_name COLLATE pu...
                                                             ^
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/sharded_instrumenter.rb:22:in `instrument'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/abstract_adapter.rb:37:in `log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `execute'
/var/canvas/config/initializers/postgresql_adapter.rb:343:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:448:in `add_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-pg-extensions-0.4.4/lib/active_record/pg_extensions/pessimistic_migrations.rb:95:in `add_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:932:in `block in method_missing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `block in say_with_time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `say_with_time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:921:in `method_missing'
/var/canvas/db/migrate/20230330205029_add_pg12_collation_indexes.rb:34:in `up'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `public_send'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:853:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:852:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:665:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1046:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1360:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1413:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1359:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1659:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1432:in `block in with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/migration.rb:40:in `block in with_advisory_lock_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/migration.rb:40:in `with_advisory_lock_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1428:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `migrate'
/var/canvas/lib/tasks/canvas.rake:190:in `block (3 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/database_server.rb:153:in `unguard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:83:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:214:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:484:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:208:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/relation/delegation.rb:88:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/relation/delegation.rb:88:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:204:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:79:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/database_server.rb:153:in `unguard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:77:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/guardrail-3.0.2/lib/guard_rail.rb:11:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:374:in `with_role_and_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:156:in `connected_to'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/guardrail-3.0.2/lib/guard_rail.rb:11:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/guard_rail.rb:13:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:76:in `block in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry/rake.rb:26:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
PG::UndefinedObject: ERROR:  collation "public.und-u-kn-true" for encoding "UTF8" does not exist
LINE 1: ...ortable_name" ON "public"."users" ((sortable_name COLLATE pu...
                                                             ^
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block in execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/sharded_instrumenter.rb:22:in `instrument'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/abstract_adapter.rb:37:in `log'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `execute'
/var/canvas/config/initializers/postgresql_adapter.rb:343:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql/schema_statements.rb:448:in `add_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-pg-extensions-0.4.4/lib/active_record/pg_extensions/pessimistic_migrations.rb:95:in `add_index'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:932:in `block in method_missing'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `block in say_with_time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:900:in `say_with_time'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:921:in `method_missing'
/var/canvas/db/migrate/20230330205029_add_pg12_collation_indexes.rb:34:in `up'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `public_send'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:873:in `exec_migration'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:853:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:852:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/active_record/migration.rb:16:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:665:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1046:in `migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1360:in `block in execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1413:in `ddl_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1359:in `execute_migration_in_transaction'
/var/canvas/config/initializers/active_record.rb:1659:in `execute_migration_in_transaction'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1333:in `migrate_without_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `block in migrate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1432:in `block in with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/migration.rb:40:in `block in with_advisory_lock_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/active_record/migration.rb:40:in `with_advisory_lock_connection'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1428:in `with_advisory_lock'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/migration.rb:1282:in `migrate'
/var/canvas/lib/tasks/canvas.rake:190:in `block (3 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `block (6 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:84:in `block (5 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/database_server.rb:153:in `unguard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:83:in `block (4 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:214:in `block (2 levels) in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:62:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:484:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:208:in `block in with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/relation/delegation.rb:88:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/relation/delegation.rb:88:in `each'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/shard.rb:204:in `with_each_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:79:in `block (3 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/database_server.rb:153:in `unguard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:77:in `block (2 levels) in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/guardrail-3.0.2/lib/guard_rail.rb:11:in `block in activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:374:in `with_role_and_shard'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_handling.rb:156:in `connected_to'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/guardrail-3.0.2/lib/guard_rail.rb:11:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/switchman/guard_rail.rb:13:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-inst-jobs-4.0.13/lib/switchman_inst_jobs/guard_rail.rb:8:in `activate'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/switchman-3.3.7/lib/tasks/switchman.rake:76:in `block in shardify_task'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.0/lib/sentry/rake.rb:26:in `execute'
/var/canvas/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate:predeploy
(See full trace by running task with --trace)
```

**Comment by amg-web** [comment]
looks like this problem is postgres side
this code https://github.com/instructure/canvas-lms/blob/1c41ece33b44a694c796ff30a2c24f95f5e8784a/config/initializers/postgresql_adapter.rb#L327
is not working on this system, but works successfully on other systems at least manually.
