### ISSUE TITLE
 RAILS_ENV=production bundle exec rake canvas:compile_assets  error

### ISSUE THREAD

**Issue by lujiasoft** [instructure/canvas-lms#2229]
error info：
rake aborted!
NameError: uninitialized constant UploadIO
/var/canvas/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.6/lib/faraday/upload_io.rb:74:in `<module:Faraday>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.6/lib/faraday/upload_io.rb:15:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.6/lib/faraday.rb:79:in `block in require_libs'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.6/lib/faraday.rb:78:in `each'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.6/lib/faraday.rb:78:in `require_libs'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.6/lib/faraday.rb:241:in `<module:Faraday>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/faraday-0.17.6/lib/faraday.rb:16:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/ims-lti-2.3.0/lib/ims/lti.rb:3:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/ims-lti-2.3.0/lib/ims.rb:2:in `<module:IMS>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/ims-lti-2.3.0/lib/ims.rb:1:in `<top (required)>'
/var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
/var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
/var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
/var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
/var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
/var/lib/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
/var/canvas/config/application.rb:36:in `<top (required)>'
/var/canvas/Rakefile:4:in `require'
/var/canvas/Rakefile:4:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by nosadcoder** [comment]
Please qq me.  May i help you.

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
