### ISSUE TITLE
Error: Can't resolve '@instructure/outcomes-ui' in '/var/canvas/ui/features/outcome_alignments'

### ISSUE THREAD

**Issue by Maclenn77** [instructure/canvas-lms#2311]
### Summary:

When running  `RAILS_ENV=production bundle exec rake canvas:compile_assets`, task exits after error messages related with webpack.

```
$ NODE_ENV=production NODE_OPTIONS="--openssl-legacy-provider --max_old_space_size=5120" webpack --color
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@instructure/outcomes-ui' in '/var/canvas/ui/features/outcome_alignments'
```

### Steps to reproduce:

 1. Create VM with Ubuntu 20.04 LTS
 2. Follow production start using prod branch
 3. Run task `canvas:compile_assets`

### Expected behavior:

Compile successfully

### Actual behavior:

Shows error message
### Additional notes:

Compute Engine Instance on Google Cloud Platform

OS: Ubuntu 20.04 LTS
RAM: 8 GB

Full Error Message:

```
--> Finished: 'css:compile' in 2.23s
--> Starting: 'js:webpack_production'
--> Building PRODUCTION webpack bundles
yarn run v1.22.19
$ NODE_ENV=production NODE_OPTIONS="--openssl-legacy-provider --max_old_space_size=5120" webpack --color
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@instructure/outcomes-ui' in '/var/canvas/ui/features/outcome_alignments'
    at /var/canvas/node_modules/webpack/lib/Compilation.js:2016:28
    at /var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/var/canvas/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/var/canvas/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /var/canvas/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve '@instructure/outcomes-ui' in '/var/canvas/ui/features/outcome_alignments'
  Parsed request is a module
  using description file: /var/canvas/ui/features/outcome_alignments/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /var/canvas/public/javascripts
        single file module
          using description file: /var/canvas/package.json (relative path: ./public/javascripts/@instructure/outcomes-ui)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/public/javascripts/@instructure/outcomes-ui doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/public/javascripts/@instructure/outcomes-ui.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/public/javascripts/@instructure/outcomes-ui.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/public/javascripts/@instructure/outcomes-ui.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/public/javascripts/@instructure/outcomes-ui.tsx doesn't exist
        /var/canvas/public/javascripts/@instructure/outcomes-ui doesn't exist
      /var/canvas/ui/features/outcome_alignments/node_modules doesn't exist or is not a directory
      /var/canvas/ui/features/node_modules doesn't exist or is not a directory
      /var/canvas/ui/node_modules doesn't exist or is not a directory
      looking for modules in /var/canvas/node_modules
        single file module
          using description file: /var/canvas/package.json (relative path: ./node_modules/@instructure/outcomes-ui)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/node_modules/@instructure/outcomes-ui is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/node_modules/@instructure/outcomes-ui.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/node_modules/@instructure/outcomes-ui.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/node_modules/@instructure/outcomes-ui.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /var/canvas/node_modules/@instructure/outcomes-ui.tsx doesn't exist
        existing directory /var/canvas/node_modules/@instructure/outcomes-ui
          using description file: /var/canvas/node_modules/@instructure/outcomes-ui/package.json (relative path: .)
            using description file: /var/canvas/package.json (relative path: ./node_modules/@instructure/outcomes-ui)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /var/canvas/node_modules/@instructure/outcomes-ui is not a file
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /var/canvas/node_modules/@instructure/outcomes-ui.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /var/canvas/node_modules/@instructure/outcomes-ui.jsx doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /var/canvas/node_modules/@instructure/outcomes-ui.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /var/canvas/node_modules/@instructure/outcomes-ui.tsx doesn't exist
              as directory
                existing directory /var/canvas/node_modules/@instructure/outcomes-ui
                  using description file: /var/canvas/node_modules/@instructure/outcomes-ui/package.json (relative path: .)
                    use ./es/index.js from module in package.json
                      using description file: /var/canvas/node_modules/@instructure/outcomes-ui/package.json (relative path: ./es/index.js)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/es/index.js doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/es/index.js.js doesn't exist
                        .jsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/es/index.js.jsx doesn't exist
                        .ts
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/es/index.js.ts doesn't exist
                        .tsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/es/index.js.tsx doesn't exist
                        as directory
                          /var/canvas/node_modules/@instructure/outcomes-ui/es/index.js doesn't exist
                    use ./lib/index.js from main in package.json
                      using description file: /var/canvas/node_modules/@instructure/outcomes-ui/package.json (relative path: ./lib/index.js)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/lib/index.js doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/lib/index.js.js doesn't exist
                        .jsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/lib/index.js.jsx doesn't exist
                        .ts
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/lib/index.js.ts doesn't exist
                        .tsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/lib/index.js.tsx doesn't exist
                        as directory
                          /var/canvas/node_modules/@instructure/outcomes-ui/lib/index.js doesn't exist
                    using path: /var/canvas/node_modules/@instructure/outcomes-ui/index
                      using description file: /var/canvas/node_modules/@instructure/outcomes-ui/package.json (relative path: ./index)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/index doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/index.js doesn't exist
                        .jsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/index.jsx doesn't exist
                        .ts
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/index.ts doesn't exist
                        .tsx
                          Field 'browser' doesn't contain a valid alias configuration
                          /var/canvas/node_modules/@instructure/outcomes-ui/index.tsx doesn't exist
      /var/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rake aborted!
Parallel::UndumpableException: RuntimeError: Error running js:webpack_development: 
```

**Comment by Maclenn77** [comment]
I run `yarn add @instructure/outcomes-ui -W`, then I run the task again and that solved the issue. Not sure if it was best solution, but it worked.
