### ISSUE TITLE
Error creating container in Codespaces

### ISSUE THREAD

**Issue by basztech** [instructure/canvas-lms#2324]
### Summary:
Building a fork fails to create a container in Codespaces. After failure, the codespace is in recovery mode and will not rebuild.

### Steps to reproduce:

 "To start, you will need to [fork this repository](https://github.com/instructure/canvas-lms/fork) so you can create a codespace. Once complete, press the "code" button on the repo, select "Open with Codespaces" and then create a new codespace. GitHub will then start building your codespace for you, which might take a minute the first time."

### Error message
```
2024-03-01 23:07:45.840Z: Creating container...
2024-03-01 23:07:45.850Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/canvas-lms --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/canvas-lms/.devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-03-01 23:07:46.371Z: @devcontainers/cli 0.56.1. Node.js v18.19.0. linux 6.2.0-1019-azure x64.
2024-03-01 23:07:46.741Z: $ docker-compose -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml --profile * config
2024-03-01 23:07:46.911Z: Stop: Run: docker-compose -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml --profile * config
2024-03-01 23:07:46.917Z: 
2024-03-01 23:07:46.919Z: service "web" has neither an image nor a build context specified: invalid compose project


2024-03-01 23:07:46.927Z: Exit code 15
2024-03-01 23:07:46.936Z: Error: Command failed: docker-compose -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml --profile * config
2024-03-01 23:07:46.945Z:     at _g (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:889)
2024-03-01 23:07:46.947Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-01 23:07:46.950Z: {"outcome":"error","message":"Command failed: docker-compose -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml --profile * config","description":"An error occurred retrieving the Docker Compose configuration."}
2024-03-01 23:07:46.953Z:     at async J$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:429:1484)
2024-03-01 23:07:46.955Z:     at async x$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:409:3165)
2024-03-01 23:07:46.959Z:     at async gAA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:3833)
2024-03-01 23:07:46.963Z:     at async BC (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:4775)
2024-03-01 23:07:46.967Z:     at async xeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11265)
2024-03-01 23:07:46.972Z:     at async UeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11006)
```

**Comment by s1050613** [comment]
Hi, has anyone here found a fix?

**Comment by drscottlobo** [comment]
Same issue! No fixes still?

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
