### ISSUE TITLE
uninitialized constant Attachment::GarbageCollector  - all versions at least since December affected

### ISSUE THREAD

**Issue by amg-web** [instructure/canvas-lms#2326]
uninitialized constant Attachment::GarbageCollector  - all versions at least since December affected.

2 errors daily on delayed_jobs
handler: --- !ruby/Delayed::Periodic Attachment::GarbageCollector::ContentExportContextType.delete_content
handler: --- !ruby/Delayed::Periodic Attachment::GarbageCollector::ContentExportContextType.delete_content

logs:
```
        uninitialized constant Attachment::GarbageCollector

      with_each_shard_by_database(Attachment::GarbageCollector::ContentExportContextType, :delete_content, jitter: 30.minutes, local_offset: true)
                                            ^^^^^^^^^^^^^^^^^^

        /home/canvas/public_html/config/initializers/periodic_jobs.rb:190:in `block (2 levels) in <top (required)>'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/periodic.rb:73:in `perform'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/backend/base.rb:313:in `block in invoke_job'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/sentry-inst_jobs-5.10.0/lib/sentry/inst_jobs/plugin.rb:25:in `block (3 levels) in <class:Plugin>'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.16.1/lib/sentry/hub.rb:59:in `with_scope'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.16.1/lib/sentry-ruby.rb:371:in `with_scope'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/sentry-inst_jobs-5.10.0/lib/sentry/inst_jobs/plugin.rb:15:in `block (2 levels) in <class:Plugin>'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:74:in `block in initialize'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block in add'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:79:in `execute'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/backend/base.rb:310:in `invoke_job'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-inst-jobs-4.0.16/lib/switchman_inst_jobs/delayed/backend/base.rb:94:in `block in invoke_job'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-3.5.18/lib/switchman/shard.rb:105:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-3.5.18/lib/switchman/shard.rb:585:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-inst-jobs-4.0.16/lib/switchman_inst_jobs/delayed/backend/base.rb:94:in `invoke_job'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:225:in `block (2 levels) in perform'
/usr/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:219:in `block in perform'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-statsd-3.0.2/lib/inst_jobs_statsd/stats/timing/perform.rb:24:in `block (2 levels) in enable_perform_timing'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst_statsd-3.0.4/lib/inst_statsd/statsd.rb:96:in `time'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-statsd-3.0.2/lib/inst_jobs_statsd/stats/timing.rb:10:in `report_timing'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-statsd-3.0.2/lib/inst_jobs_statsd/stats/timing/perform.rb:23:in `block in enable_perform_timing'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-statsd-3.0.2/lib/inst_jobs_statsd/stats/timing/perform.rb:15:in `block (2 levels) in enable_batching'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst_statsd-3.0.4/lib/inst_statsd/statsd.rb:102:in `batch'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-statsd-3.0.2/lib/inst_jobs_statsd/stats/timing/perform.rb:14:in `block in enable_batching'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/home/canvas/public_html/config/initializers/delayed_job.rb:153:in `block (2 levels) in <top (required)>'
/home/canvas/public_html/lib/base/temp_cache.rb:30:in `enable'
/home/canvas/public_html/config/initializers/delayed_job.rb:152:in `block in <top (required)>'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block (2 levels) in add'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:74:in `block in initialize'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block in add'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block in add'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:98:in `block in add'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:79:in `execute'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:216:in `perform'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:186:in `block (2 levels) in run'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:296:in `block in configure_for_job'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:54:in `running_job'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:292:in `configure_for_job'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:185:in `block in run'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:74:in `block in initialize'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:79:in `execute'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:177:in `run'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-inst-jobs-4.0.16/lib/switchman_inst_jobs/delayed/worker.rb:31:in `block in run'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-3.5.18/lib/switchman/shard.rb:105:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-3.5.18/lib/switchman/shard.rb:585:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-inst-jobs-4.0.16/lib/switchman_inst_jobs/delayed/worker.rb:31:in `run'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:141:in `block in start'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:74:in `block in initialize'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:79:in `execute'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/lifecycle.rb:52:in `run_callbacks'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/worker.rb:140:in `start'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-inst-jobs-4.0.16/lib/switchman_inst_jobs/delayed/worker.rb:24:in `block in start'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-3.5.18/lib/switchman/shard.rb:105:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-3.5.18/lib/switchman/shard.rb:585:in `activate'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/switchman-inst-jobs-4.0.16/lib/switchman_inst_jobs/delayed/worker.rb:24:in `start'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:113:in `block in spawn_worker'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:125:in `block in fork_with_reconnects'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:121:in `fork'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:121:in `fork_with_reconnects'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:112:in `spawn_worker'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:92:in `block (2 levels) in spawn_all_workers'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:92:in `times'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:92:in `block in spawn_all_workers'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:91:in `each'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:91:in `spawn_all_workers'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/pool.rb:48:in `start'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/cli.rb:112:in `start'
/home/canvas/public_html/vendor/bundle/ruby/3.1.0/gems/inst-jobs-3.1.14/lib/delayed/cli.rb:36:in `run'
script/delayed_job:11:in `<main>'
```

**Comment by huangdengpan** [comment]
Same problem , need help!

**Comment by amg-web** [comment]
seems to be fixed in last versions

**Comment by huangdengpan** [comment]
> seems to be fixed in last versions

not yet in stable branch, master branch has few unknown bugs.

**Comment by amg-web** [comment]
@huangdengpan 
do you still seee it? I do not see this error in jobs any more

**Comment by huangdengpan** [comment]
> @huangdengpan do you still seee it? I do not see this error in jobs any more

still exist, i will try new version after 2 months.

**Comment by amg-web** [comment]
@huangdengpan 
I do not see this error in last vesions. I do not know why you still see it.
