### ISSUE TITLE
 The application encountered the following error: unknown keyword: :servers (ArgumentError)

### ISSUE THREAD

**Issue by x7l7y7** [instructure/canvas-lms#2330]
### Summary:
When I go to the last step "sudo /etc/init.d/apache2 restart", the webpage shows 500 ERROR. Looking at the Apache error logs, you can find the following:

App 123840 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 123840 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2024-03-19 14:14:39.2845 123704/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/canvas: The application encountered the following error: unknown keyword: :servers (ArgumentError)

### Steps to reproduce:
 1.sudo /etc/init.d/apache2 restart

### Additional notes:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]

**Comment by ccutrer** [comment]
Without a full stack trace, the cause cannot be identified.
