### ISSUE TITLE
[Bundler::GitError]  Error: The application encountered the following error: https://github.com/kreynolds/cassandra-cql.git (at 02b5abb@02b5abb) is not yet checked out. Run `bundle install` first. (Bundler::GitError)

### ISSUE THREAD

**Issue by rs-phunt** [instructure/canvas-lms#2333]
### Summary:
  - OS: Ubuntu 20.04.6 LTS
  - Architecture: `Linux 6f294b78cab3 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

### Steps to reproduce:

 1. Start Passenger
 2. Start Apache2
 3. Error logs (`/var/log/apache2/error.log`)

```log
App 5600 output:  [passenger_native_support.so] trying to compile for the current user (nobody) and Ruby interpreter...
App 5600 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 5600 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 5600 output:      /tmp/passenger_native_support-mx5yo1.log
App 5600 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 5600 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 5600 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.20/rubyext-ruby-3.1.2-aarch64-linux.tar.gz: The requested URL returned error: 404
App 5600 output:      Trying next mirror...
App 5600 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.20/rubyext-ruby-3.1.2-aarch64-linux.tar.gz: The requested URL returned error: 404
App 5600 output:      Trying next mirror...
App 5600 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.20/rubyext-ruby-3.1.2-aarch64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 5600 output:  [passenger_native_support.so] will not be used (can't compile or download)
App 5600 output:   --> Passenger will still operate normally.
App 5600 output: Error: The application encountered the following error: https://github.com/kreynolds/cassandra-cql.git (at 02b5abb@02b5abb) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/source/git.rb:222:in `rescue in load_spec_files'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/source/git.rb:218:in `load_spec_files'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/source/path.rb:108:in `local_specs'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/source/git.rb:185:in `specs'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/lazy_specification.rb:97:in `materialize_for_installation'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:281:in `map!'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:281:in `specs_for_dependency'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:34:in `block in for'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:22:in `loop'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:22:in `for'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:121:in `materialize'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/definition.rb:579:in `materialize'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/definition.rb:203:in `specs'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/definition.rb:270:in `specs_for'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:18:in `setup'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler.rb:162:in `setup'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `block in <top (required)>'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:159:in `with_level'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:111:in `silence'
App 5600 output:     /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `<top (required)>'
App 5600 output:     <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
App 5600 output:     <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
App 5600 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:382:in `activate_gem'
App 5600 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
App 5600 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:546:in `running_bundler'
App 5600 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
App 5600 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:91:in `preload_app'
App 5600 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 5600 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:399:in `run_block_and_record_step_progress'
App 5600 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 5600 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 5600 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2024-03-20 11:53:26.8887 5500/Tp age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/canvas: The application encountered the following error: https://github.com/kreynolds/cassandra-cql.git (at 02b5abb@02b5abb) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
  Error ID: 1e93cfe6
  Error details saved to: /tmp/passenger-error-lvMlJ5.html

[ E 2024-03-20 11:53:26.8908 5500/T8 age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1e93cfe6. Please see earlier logs for details about the error.
```

Maybe `cassandra-cql` gem unable to download `1.2.3` version?
Thank you!!!

**Comment by pocketcolin** [comment]
I'm seeing this same thing. You find a solution?

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
