### ISSUE TITLE
 [AUTH] Authlogic Validation Error: You did not provide any details for authentication.

### ISSUE THREAD

**Issue by osetu** [instructure/canvas-lms#2354]
### Summary:

Hi, I'm building CanvasLMS locally in Production Start mode. 
※OS: Ubuntu 20.04
※AP Server: Apache2 + Passenger

Last December, I built CanvasLMS locally for my first time using the master branch at that time, and it has been working properly.

I am trying to recreate the environment using the same resources and the same procedures (I think) this month.
However, when I tried to login to the new CanvasLMS with the email address and password that I entered during the initial DB Initial Setup, I got an "Invalid Authentication Token" error. 

I'm struggling for 3 days but haven't resolve the error.
I have attached the error log（found in log/production.log）. If anyone has this experience, could you please... tell me the possible cause of the error? 

>Processing by Login::CanvasController#create as HTML
>Parameters: {"utf8"=>"✓", "authenticity_token"=>"tokenWasEmpty", "redirect_to_ssl"=>"1", "pseudonym_session"=>{"unique_id"=>"wangxuemeng1027@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"0"}}
>[AUTH] Authlogic Validation Error: You did not provide any details for authentication.
>[AUTH] Authlogic Failed Find
>[AUTH] inital load: pseud -> , user ->
>[AUTH] final user: 
>[1m[36mSQL AuthenticationProvider Load (0.5ms)[0m  [1m[34mSELECT "authentication_providers".* FROM "public"."authentication_providers" WHERE "authentication_providers"."account_id" = 1 AND "authentication_providers"."auth_type" = 'canvas' AND (workflow_state <> 'deleted') ORDER BY "authentication_providers"."position" ASC, "authentication_providers"."id" ASC LIMIT 1[0m  [production:1 primary]
>Can't verify CSRF token authenticity.

### Steps to reproduce:

 1. Run "RAILS_ENV=production bundle exec rake db:migrate"
 2. Run "RAILS_ENV=production bundle exec rake canvas:compile_assets"
 3. Configure apache2 and Run "sudo service apache2 start"
 4. Access to "http://localhost:3000"
 5. Login

### Expected behavior:
Login Successfully and Dashboard be shown.

### Actual behavior:
Invalid Authentication Error.

### Additional notes:
![image](https://github.com/instructure/canvas-lms/assets/106966564/601288c5-8017-4a35-b986-c10fa73fbc1f)

**Comment by nosadcoder** [comment]
On the image, you can see some keywords,```tokenWasEmpty```,  ```Can't verify CSRF token authenticity```
So, I think the cookie is invalid.

**Comment by GlenSoftware** [comment]
have you found a fix to this yet?

**Comment by GlenSoftware** [comment]
I have somthing similar to me, what worked for me by accessing the website via https instead of just http.

**Comment by brookesia** [comment]
It’s not that for me unfortunately, I’m accessing via https. Thanks anyway.

**Comment by bhagwandas** [comment]
I am trying to get access token for LTI 1.3 integration and facing same error. It was working fine couple of months earlier (no update was done on Canvas LMS).
As per documentation, we are providing all the params correctly.

Endpoint: https://<canvas url>/login/oauth2/token
Post data:
```
{
  'grant_type': 'client_credentials', 
  'client_assertion_type': 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
  'client_assertion': '.......', 
  'scope': 'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly https://purl.imsglobal.org/spec/lti-ags/scope/score'
}
```

Relevant canvas server log:
[- 41502deb-1154-4a0a-8979-3c8d04100095] Started POST "/login/oauth2/token" for 10.8.0.78 at 2024-08-18 04:07:28 +0000
[- 41502deb-1154-4a0a-8979-3c8d04100095] Processing by OAuth2ProviderController#token as */*
[- 41502deb-1154-4a0a-8979-3c8d04100095]   Parameters: {"grant_type"=>"client_credentials", "client_assertion_type"=>"urn:ietf:params:oauth:client-assertion-type:jwt-bearer", "client_assertion"=>"", "scope"=>"https://purl.imsglobal.org/spec/lti-ags/scope/lineitem https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly https://purl.imsglobal.org/spec/lti-ags/scope/score"}
[- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] Authlogic Validation Error: You did not provide any details for authentication.
[- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] Authlogic Failed Find
[- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] inital load: pseud -> , user ->
[- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] final user:


And after this error, it takes more than 2 minutes to send back error page.

/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception''', 'Net::ReadTimeout', '2024-08-18 04:09:29.842340', '2024-08-18 04:09:29.842340', 'unknown-canvas-lab-computer@instructure.example.com', 'PyLTI1p3-client', 'post', '41502deb-1154-4a0a-8979-3c8d04100095', 1, '---

**Comment by brookesia** [comment]
In case it helps anybody else, the cause of the issue for me was Rack 3.0 being incompatible with passenger, it makes the cookies malformed (something like"[_csrf_token, rather than _csrf_token), see this issue for more info https://github.com/rails/rails/issues/49422, it's a general Rails issue, not limited to Canvas.

I've got it working temporarily by changing the Rack version to 2.2 in the Gemfile, commented out the rack3-brotli gem in the Gemfile (because it depends on Rack 3), commenting out the brotli middleware in config/application.rb, and ran bundle install.

**Comment by CelaldoganGunes** [comment]
I installed passenger from this and problem is gone:
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger $(lsb_release -cs) main > /etc/apt/sources.list.d/passenger.list';

**Comment by bhagwandas** [comment]
> I am trying to get access token for LTI 1.3 integration and facing same error. It was working fine couple of months earlier (no update was done on Canvas LMS). As per documentation, we are providing all the params correctly.
> 
> Endpoint: https:///login/oauth2/token Post data:
> 
> ```
> {
>   'grant_type': 'client_credentials', 
>   'client_assertion_type': 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
>   'client_assertion': '.......', 
>   'scope': 'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly https://purl.imsglobal.org/spec/lti-ags/scope/score'
> }
> ```
> 
> Relevant canvas server log:
> 
> ```
> [- 41502deb-1154-4a0a-8979-3c8d04100095] Started POST "/login/oauth2/token" for 10.8.0.78 at 2024-08-18 04:07:28 +0000
> [- 41502deb-1154-4a0a-8979-3c8d04100095] Processing by OAuth2ProviderController#token as */*
> [- 41502deb-1154-4a0a-8979-3c8d04100095]   Parameters: {"grant_type"=>"client_credentials", "client_assertion_type"=>"urn:ietf:params:oauth:client-assertion-type:jwt-bearer", "client_assertion"=>"", "scope"=>"https://purl.imsglobal.org/spec/lti-ags/scope/lineitem https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly https://purl.imsglobal.org/spec/lti-ags/scope/score"}
> [- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] Authlogic Validation Error: You did not provide any details for authentication.
> [- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] Authlogic Failed Find
> [- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] inital load: pseud -> , user ->
> [- 41502deb-1154-4a0a-8979-3c8d04100095] [AUTH] final user:
> ```
> 
> And after this error, it takes more than 2 minutes to send back error page.
> 
> /opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception''', 'Net::ReadTimeout', '2024-08-18 04:09:29.842340', '2024-08-18 04:09:29.842340', '[unknown-canvas-computer@instructure.example.com](mailto:unknown-canvas-computer@instructure.example.com)', 'PyLTI1p3-client', 'post', '41502deb-1154-4a0a-8979-3c8d04100095', 1, '---

This issue was on LTI tool side, not on Canvas LMS.
I was running LTI tool on single thread, so when Canvas LMS asked back for jwks, there was not any response. Hence it timed out and gave error.

**Comment by blackerhand** [comment]
please modify config/environments/xx.rb config.force_ssl = true  to false, It works!

**Comment by damarizz** [comment]
> please modify config/environments/xx.rb config.force_ssl = true to false, It works!

worked for me, too, on production setup. thanks!

**Comment by vhlt** [comment]
I follow all your guides, I am using rack 2.2.7, set config.force_ssl = false in config/environments/production.rb. But it still does not work.
Could you please give me your current config @blackerhand, @damarizz, @brookesia? Many thanks.

**Comment by vhvuongorigin** [comment]
I follow all your guides, I am using rack 2.2.7, set config.force_ssl = false in config/environments/production.rb. But it still does not work.
Could you please give me your current config @blackerhand, @damarizz, @brookesia? Many thanks.

**Comment by ccutrer** [comment]
Please use [the mailing list](https://groups.google.com/g/canvas-lms-users) for installation and operational issues.
