### ISSUE TITLE
Gradebook and Grading Scheme Not Working Properly Upon Update

### ISSUE THREAD

**Issue by jenniferhelbley** [instructure/canvas-lms#2423]
### Summary:
I am using the community edition of Canvas (not hosted by Instructure) and we recently did an update from an older version. (I know we should have been doing incremental updates, but I only have so much time in my life.) Nearly everything is working or working super good enough but I have two problems that I just can't track down the why or how. I'm not sure if they are connected but it _feels_ like they are.

1. Instructor view of gradebook works most of the time, but every now and again something gets saved in an instructors profile that sets the gradebook to view from external source and then the instructor can't view the gradebook. I thought it was due to an external tool being used but then I had one of my instructors that most definitely does not use any external tools and (as far as I know) also has never updated grades by importing a csv so I am stumped what could possibly be changing this setting. It works if I delete their gradebook view profile using ssh, but that isn't very practical long term.  (View below.)
![gradebook view not working](https://github.com/user-attachments/assets/ec58e990-53eb-41d5-9747-4d01f987e1ec)

3. Grading schemes no longer work. It seems to be stuck somewhere in the old view and new grade schemes view. I can create a new grade scheme but it isn't selectable in a course. I tried all (I think) of the various permutations of order of operations setting the grading scheme/editing the grading scheme/update course details/going to manage grading schemes. But I still can't get it to apply to a course or even let me search grading schemes. When I do go looking at the grading schemes for a course, I find all the ones I created, but none can be applied.
![grade scheme set](https://github.com/user-attachments/assets/0c2ac81d-c324-42e9-b9de-3d497a6e3928)

If anyone has any thoughts on where to look to trace these errors that would be great. Thanks in advance!

**Comment by amg-web** [comment]
same to me
i see following in browser's console while trying to get list of custom grades.
```
jquery.js:1489 Uncaught Error: Syntax error, unrecognized expression: .assessed_assignment?
    at et.error (jquery.js:1489:12)
    at ef (jquery.js:2155:8)
    at e_ (jquery.js:2614:20)
    at Function.et (jquery.js:941:9)
    at Function.<anonymous> (jquery-migrate.js:266:17)
    at t.<computed> [as find] (jquery-migrate.js:181:20)
    at t.<computed>.find (jquery.js:2824:11)
    at i (templateData.js:63:33)
    at a.fn.fillTemplateData (templateData.js:52:38)
    at index.js:226:20
```

**Comment by jenniferhelbley** [comment]
Thanks amg-web for confirming I'm not the only one with a problem with gradebook.
In the browser console I get the very vague error:
`Failed to load resource: the server responded with a status of 500 ()`

**Comment by DoctorOgg** [comment]
> @jenniferhelbley it's related to this i think #2331

not sure it is, as the security.yml looks correct

```yaml
production:
  encryption_key: [REDACTED]
  lti_iss: 'https://lms.[REDACTED]'

```

**Comment by DoctorOgg** [comment]
i should clarify that my comments are specifically to @jenniferhelbley conserns, as i am also helping her with her install.

**Comment by jenniferhelbley** [comment]
With the Thanksgiving Break, I had some time to do a little bit more digging on the gradebook view issue.  I still need to do some more work on the Grade Scheme issue.
What I know for sure now is that gradebook_settings->:external is the problem.
I can duplicate that getting set to external by doing the following in the gradebook: 
1. sort the grades by total (either high to low or low to high) 
2. refresh the grades page
This triggers the following tow items being set in the user preferences file
`:gradebook_column_order=>:external,
 :gradebook_settings=>:external}`
But I only need to delete the gradebook_settings for the gradebook to load correctly.

**Comment by amg-web** [comment]
I checked even February 2024 canvas version - issue exists.
I could not find why js  looks for key `.assessed_assignment?` with dot as first symbol, while json data returned does not have it in a key name.
Any Ideas where to fix?
![Screenshot from 2024-11-26 13-29-26](https://github.com/user-attachments/assets/814b194b-bb0b-453a-8c76-00e1334fb557)

**Comment by va7map** [comment]
@jenniferhelbley The Gradebook bug has something to do with the submissions data being incomplete at the time it's loaded asynchronously, shortly after the initial page load. I didn't dig too deep as I found that enabling [Enhanced Gradebook Filters](https://community.canvaslms.com/t5/The-Product-Blog/Say-Hello-to-quot-Enhanced-Gradebook-Filters-quot-as-the-New/ba-p/573315) avoids the bug altogether.

@amg-web At some point, the object keys are converted into CSS class selectors, and anything with a question mark triggers an unrecognized expression syntax error. You can try deleting `standard["assessed_assignment?"]` before the object is used in _ui/shared/grading-standards/jquery/index.js_ on [line 235](https://github.com/instructure/canvas-lms/blob/49cb28f9a3d094b5232736299e60dff1b0b087df/ui/shared/grading-standards/jquery/index.js#L235) and [line 447](https://github.com/instructure/canvas-lms/blob/49cb28f9a3d094b5232736299e60dff1b0b087df/ui/shared/grading-standards/jquery/index.js#L447). You'd also want to remove the unnecessary comma following `input.grading_standard_id` on [line 378](https://github.com/instructure/canvas-lms/blob/49cb28f9a3d094b5232736299e60dff1b0b087df/ui/shared/grading-standards/jquery/index.js#L378) to avoid another syntax error.

**Comment by amg-web** [comment]
i'm not strong in js, but
here it calls a function to pars json https://github.com/instructure/canvas-lms/blob/a796039d7c61565d0002f8a587b9e136821b5ed8/ui/shared/grading-standards/jquery/index.js#L207
then here this data is processed https://github.com/instructure/canvas-lms/blob/a796039d7c61565d0002f8a587b9e136821b5ed8/ui/shared/util/templateData.js#L63

is the data processed as html class? or I do not understand what happened here?

**Comment by amg-web** [comment]
@va7map 
i do not see class similar to assessed_assignment at all
I see json data, which is not processed correctly

**Comment by amg-web** [comment]
grading scheme selector works on origin/stable/2023-12-06
oh Feb 2024  or newer it's not working

**Comment by jenniferhelbley** [comment]
I noticed today that one of the courses that I had imported from before with very few changes, retained it's ability, kinda, to have a grade scheme. 
I cannot modify it directly in the settings interface, but I can make my way over to the manage schemes page and edit it there. So for now I can help faculty get that working for end of quarter grades, but would be nice to have a fix faculty can easily use.

**Comment by amg-web** [comment]
@jenniferhelbley 
I think part 1 should be fixed on prod by this pull request https://github.com/instructure/canvas-lms/commit/7c6dc824725a9636262871c5d7d34177135831a8

**Comment by jenniferhelbley** [comment]
thanks amg-web! I'll give it a shot and post results

**Comment by amg-web** [comment]
I added replacement code in a line
https://github.com/instructure/canvas-lms/blob/cfeb24f6021ac7f76bff6f6b721c5d26ebc63f52/ui/shared/util/templateData.js#L63

```
const $found_all = this.find('.' + item.replace(/\?/g, '\\?'))
```

Now I see the list of custom grades but can not apply to the course. 
error in browser's console:
```
Uncaught Error: Syntax error, unrecognized expression: input.grading_standard_id,
    at et.error (jquery.js:1489:12)
    at ef (jquery.js:2155:8)
    at e_ (jquery.js:2614:20)
    at Function.et (jquery.js:941:9)
    at Function.<anonymous> (jquery-migrate.js:266:17)
    at t.<computed> [as find] (jquery-migrate.js:181:20)
    at S.fn.init.find (jquery.js:2824:11)
    at S.fn.init (jquery.js:2934:32)
    at t.<computed>.<anonymous> (jquery-migrate.js:226:17)
    at new t.<computed> (jquery-migrate.js:181:20)
```

**Comment by amg-web** [comment]
@va7map 
I manage get it working.
I used your advise about  comma on https://github.com/instructure/canvas-lms/blob/49cb28f9a3d094b5232736299e60dff1b0b087df/ui/shared/grading-standards/jquery/index.js#L378 
in addition to the place reported previous message.

Is there a way to know if i did not brake anything for other places?

**Comment by huangdengpan** [comment]
Does it has been fixed ?

**Comment by huangdengpan** [comment]
same as my canvas, i am using the version 2024-11-20

**Comment by huangdengpan** [comment]
fixed !

![Image](https://github.com/user-attachments/assets/5728a3f4-12a7-4ad2-8a85-dd6f20b16b7a)

**Comment by huangdengpan** [comment]
https://github.com/huangdengpan/canvas-lms/blob/prod/ui/shared/grading-standards/jquery/index.js
https://github.com/huangdengpan/canvas-lms/blob/prod/app/controllers/grading_standards_controller.rb

**Comment by huangdengpan** [comment]
@amg-web @jenniferhelbley

**Comment by jenniferhelbley** [comment]
> https://github.com/huangdengpan/canvas-lms/blob/prod/ui/shared/grading-standards/jquery/index.js https://github.com/huangdengpan/canvas-lms/blob/prod/app/controllers/grading_standards_controller.rb

thanks!!! I'll give this a try after term ends and I have time to implement
