### ISSUE TITLE
`define_method_global_attribute': unknown keyword: :as (ArgumentError)

### ISSUE THREAD

**Issue by Mrzhiyao** [instructure/canvas-lms#2432]
:~/canvas$ bundle exec rails db:initial_setup
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.2
      - 3.1.0
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.2
      - 3.1.0
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.2
      - 3.1.0
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'

_**Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/3.3.0/gems/rack-3.0.11/lib/rack/chunked.rb:6: warning: Rack::Chunked is deprecated and will be removed in Rack 3.1
/usr/local/lib/ruby/gems/3.3.0/gems/switchman-3.6.7/lib/switchman/active_record/attribute_methods.rb:68:in `define_method_global_attribute': unknown keyword: :as (ArgumentError)**_

        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:351:in `define_attribute_method_pattern'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:330:in `block (2 levels) in define_attribute_method'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:329:in `each'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:329:in `block in define_attribute_method'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/code_generator.rb:43:in `batch'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:328:in `define_attribute_method'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:291:in `block (2 levels) in define_attribute_methods'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:290:in `each'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:290:in `block in define_attribute_methods'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/code_generator.rb:46:in `batch'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/attribute_methods.rb:289:in `define_attribute_methods'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/attribute_methods.rb:138:in `block in define_attribute_methods'
        from /usr/local/lib/ruby/gems/3.3.0/gems/mutex_m-0.3.0/lib/mutex_m.rb:82:in `synchronize'
        from /usr/local/lib/ruby/gems/3.3.0/gems/mutex_m-0.3.0/lib/mutex_m.rb:82:in `mu_synchronize'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/attribute_methods.rb:135:in `define_attribute_methods'
        from /usr/local/lib/ruby/gems/3.3.0/gems/switchman-3.6.7/lib/switchman/active_record/attribute_methods.rb:29:in `define_attribute_methods'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/core.rb:791:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/persistence.rb:1142:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/validations.rb:435:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activemodel-7.1.5/lib/active_model/dirty.rb:366:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/attribute_methods/dirty.rb:197:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/timestamp.rb:103:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/associations.rb:338:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/autosave_association.rb:277:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/transactions.rb:380:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/touch_later.rb:50:in `init_internals'
        from /home/b410-2070s-4/canvas/config/initializers/active_record.rb:1867:in `init_internals'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/core.rb:450:in `initialize'
        from /usr/local/lib/ruby/gems/3.3.0/gems/aroi-1.0.0/lib/aroi/instrumentation/active_record.rb:35:in `block in initialize'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/notifications.rb:206:in `block in instrument'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/notifications.rb:206:in `instrument'
        from /usr/local/lib/ruby/gems/3.3.0/gems/aroi-1.0.0/lib/aroi/instrumentation/active_record.rb:34:in `initialize'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/inheritance.rb:76:in `new'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/inheritance.rb:76:in `new'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/relation.rb:920:in `_new'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/relation.rb:74:in `block in new'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/relation.rb:939:in `_scoping'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/relation.rb:467:in `scoping'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/relation.rb:74:in `new'
        from /usr/local/lib/ruby/gems/3.3.0/gems/switchman-3.6.7/lib/switchman/active_record/relation.rb:32:in `block in new'
        from /usr/local/lib/ruby/gems/3.3.0/gems/switchman-3.6.7/lib/switchman/default_shard.rb:11:in `activate'
        from /usr/local/lib/ruby/gems/3.3.0/gems/switchman-3.6.7/lib/switchman/active_record/relation.rb:32:in `new'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activerecord-7.1.5/lib/active_record/relation.rb:131:in `first_or_initialize'
        from /home/b410-2070s-4/canvas/app/models/setting.rb:54:in `set'
        from /home/b410-2070s-4/canvas/gems/canvas_security/lib/canvas_security.rb:326:in `validate_encryption_key'
        from /home/b410-2070s-4/canvas/config/initializers/canvas_security.rb:23:in `block in <main>'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:448:in `instance_exec'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:448:in `block in make_lambda'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:706:in `catch'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:706:in `block in default_terminator'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:203:in `block in halting'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:598:in `block in invoke_before'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:598:in `each'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:598:in `invoke_before'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/callbacks.rb:109:in `run_callbacks'
        from /usr/local/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5/lib/active_support/reloader.rb:96:in `prepare!'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:32:in `run'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
        from /usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/application.rb:426:in `initialize!'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/railtie.rb:226:in `public_send'
        from /usr/local/lib/ruby/gems/3.3.0/gems/railties-7.1.5/lib/rails/railtie.rb:226:in `method_missing'
        from /home/b410-2070s-4/canvas/config/environment.rb:24:in `<main>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /usr/local/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from /usr/local/lib/ruby/gems/3.3.0/gems/spring-4.2.1/lib/spring/application.rb:112:in `preload'
        from /usr/local/lib/ruby/gems/3.3.0/gems/spring-4.2.1/lib/spring/application.rb:171:in `serve'
        from /usr/local/lib/ruby/gems/3.3.0/gems/spring-4.2.1/lib/spring/application.rb:153:in `block in run'
        from <internal:kernel>:187:in `loop'
        from /usr/local/lib/ruby/gems/3.3.0/gems/spring-4.2.1/lib/spring/application.rb:147:in `run'
        from /usr/local/lib/ruby/gems/3.3.0/gems/spring-4.2.1/lib/spring/application/boot.rb:25:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from -e:1:in `<main>'

This problem has been bothering me for a long time, and I would like to ask if anyone has a solution. I am currently using switchman 3.6.7 in the gemfile, but I will encounter the following issue during initialization and cannot continue to use it. I manually configured it

**Comment by kevinroleke** [comment]
I am encountering the same issue.
