### ISSUE TITLE
super: no superclass method `password=' 

### ISSUE THREAD

**Issue by cvong** [instructure/canvas-lms#455]
Dear Sir/Madam,

I tried to import students through SIS import but got the following errors. Could you tell me what might be the problem? Thanks.

Chi-Hou

```
super: no superclass method `password=' for #<Pseudonym:0x0000001722c768>

/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/attribute_methods.rb:270:in `method_missing'
/var/canvas/app/models/pseudonym.rb:135:in `password='
/var/canvas/lib/sis/user_importer.rb:154:in `block in process_batch'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/var/canvas/vendor/bundle/ruby/1.9.1/bundler/gems/rails-e86daf8ff727/activerecord/lib/active_record/transactions.rb:182:in `transaction'
/var/canvas/lib/sis/user_importer.rb:83:in `process_batch'
/var/canvas/lib/sis/user_importer.rb:73:in `add_user'
/var/canvas/lib/sis/csv/user_importer.rb:36:in `block (2 levels) in process'
/var/canvas/lib/sis/csv/csv_base_importer.rb:59:in `block in csv_rows'
/usr/lib/ruby/1.9.1/csv.rb:1792:in `each'
/usr/lib/ruby/1.9.1/csv.rb:1208:in `block in foreach'
/usr/lib/ruby/1.9.1/csv.rb:1354:in `open'
/usr/lib/ruby/1.9.1/csv.rb:1207:in `foreach'
/var/canvas/lib/sis/csv/csv_base_importer.rb:58:in `csv_rows'
/var/canvas/lib/sis/csv/user_importer.rb:32:in `block in process'
/var/canvas/lib/sis/user_importer.rb:28:in `block (3 levels) in process'
/var/canvas/lib/sticky_sis_fields.rb:125:in `block in process_as_sis'
/var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:41:in `suspend_callbacks'
/var/canvas/lib/sticky_sis_fields.rb:124:in `process_as_sis'
/var/canvas/lib/sis/user_importer.rb:27:in `block (2 levels) in process'
/var/canvas/lib/sticky_sis_fields.rb:125:in `block in process_as_sis'
/var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:41:in `suspend_callbacks'
/var/canvas/lib/sticky_sis_fields.rb:124:in `process_as_sis'
/var/canvas/lib/sis/user_importer.rb:26:in `block in process'
/var/canvas/app/models/user.rb:366:in `call'
/var/canvas/app/models/user.rb:366:in `skip_updating_account_associations'
/var/canvas/lib/sis/user_importer.rb:25:in `process'
/var/canvas/lib/sis/csv/user_importer.rb:31:in `process'
/var/canvas/lib/sis/csv/import.rb:165:in `block (2 levels) in process'
/var/canvas/lib/sis/csv/import.rb:165:in `each'
/var/canvas/lib/sis/csv/import.rb:165:in `block in process'
/var/canvas/lib/sis/csv/import.rb:163:in `each'
/var/canvas/lib/sis/csv/import.rb:163:in `process'
/var/canvas/lib/sis/csv/import.rb:88:in `process'
/var/canvas/app/models/sis_batch.rb:158:in `process_instructure_csv_zip'
/var/canvas/app/models/sis_batch.rb:44:in `block in valid_import_types'
/var/canvas/app/models/sis_batch.rb:125:in `call'
/var/canvas/app/models/sis_batch.rb:125:in `process_without_send_later'
/var/canvas/app/models/sis_batch.rb:142:in `block (2 levels) in process_all_for_account'
/var/canvas/app/models/sis_batch.rb:142:in `each'
/var/canvas/app/models/sis_batch.rb:142:in `block in process_all_for_account'
/var/canvas/app/models/sis_batch.rb:139:in `loop'
/var/canvas/app/models/sis_batch.rb:139:in `process_all_for_account'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/performable_method.rb:21:in `perform'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/backend/base.rb:230:in `invoke_job'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:139:in `block (2 levels) in perform'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:133:in `block in perform'
/var/canvas/config/initializers/delayed_job.rb:41:in `call'
/var/canvas/config/initializers/delayed_job.rb:41:in `block in <top (required)>'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:72:in `call'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:72:in `block (2 levels) in add'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:54:in `call'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:54:in `block in initialize'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:72:in `call'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:72:in `block in add'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:59:in `call'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:59:in `execute'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/lifecycle.rb:32:in `run_callbacks'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:130:in `perform'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:105:in `block in run'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:204:in `block in configure_for_job'
/usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:202:in `configure_for_job'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:103:in `run'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:78:in `block in start'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:77:in `loop'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/worker.rb:77:in `start'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:153:in `block in spawn_worker'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:164:in `block in fork_with_reconnects'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:161:in `fork'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:161:in `fork_with_reconnects'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:151:in `spawn_worker'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:212:in `block in join'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:199:in `loop'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:199:in `join'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:100:in `start'
/var/canvas/vendor/plugins/delayed_job/lib/delayed/pool.rb:51:in `run'
/var/canvas/script/delayed_job:5:in `<main>'
```

**Comment by claydiffrient** [comment]
@cvong Sorry it's been a while.  Is this still happening for you?

**Comment by cvong** [comment]
No. Thanks.
