### ISSUE TITLE
[BUG] Number to human size helper error

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#528]
Hi everyone, 

We've discovered a new issue today, the error report is quite usefull here so here it is:

``` ruby
 wrong argument type nil (expected Fixnum)
account: Root
category: TypeError
created at: 2014-10-24 12:16:37 +0200
user: user@mail.com
url: http://domain.com/courses/1/statistics
request context id: c254fdd0-3d94-0132-5f1a-002590a4180a
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_ACCEPT_ENCODING: gzip, deflate
HTTP_HOST: domain.com
HTTP_REFERER: http://domain.com/courses/1/settings
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0
PATH_INFO: /courses/1/statistics
QUERY_STRING: ?
REMOTE_ADDR: 90.38.5.181
REQUEST_METHOD: GET
REQUEST_URI: http://domain.com/courses/1/statistics
SERVER_NAME: domain.com
SERVER_PORT: 80
SERVER_PROTOCOL: HTTP/1.1
format: text/html
hostname: ns314528.ip-5-135-138.eu
path_parameters: {:action=>"statistics", :controller=>"courses", :course_id=>"1"}
pid: 7536
query_parameters: {}
request_parameters: {}

        wrong argument type nil (expected Fixnum)

        /usr/local/rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.19/lib/action_view/helpers/number_helper.rb:363:in `round'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.19/lib/action_view/helpers/number_helper.rb:363:in `number_with_precision'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.19/lib/action_view/helpers/number_helper.rb:461:in `number_to_human_size'
/var/www/nginx-apps/domain/releases/20141015083827/app/views/courses/statistics.html.erb:133:in `_app_views_courses_statistics_html_erb___2791800251944464028_162935800'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.19/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/actionpack-3.2.19/lib/action_view/template.rb:143:in `render'
/var/www/nginx-apps/domain/releases/20141015083827/config/initializers/i18n.rb:204:in `render_with_i18n_scope'
```

I had the same error accessing the "Files page" of the course. 

I had to add ":precision => 5" option to the number_to_human_size function in those views in order to solve the issue. The number_to_human_size functions just don"t work in this app because precision seems to be nil when rails tries to use the "round" function. 

Strange thing is that I don't have this issue in another app where I use the exact same version of rails. 

Does someone have any clue on what may be happening? 

Otherwise, wouldn't it be better to add a precision to the number_to_human_size functions you use?
If so, I could do a pull request where I add a :precision => 5 option to each number_to_human_size functions. 

Thanks, 
Regis & Unow team.

**Comment by simonista** [comment]
Looks like these are showing up in non-english locales now, so I don't this this is an issue any longer.
