### ISSUE TITLE
** Execute db:migrate fails at quiz_submission_events

### ISSUE THREAD

**Issue by stumari** [instructure/canvas-lms#563]
Hello,
I am trying to installed Canvas LMs production using PostgreSQL 9.4.0.
I am using
ruby -v
ruby 1.9.3p550 (2014-10-27) [x86_64-linux] Brightbox
gem list
bundler (1.6.0)
psql --version
psql (PostgreSQL) 9.4.0
Everything went fine till the DB migration

```
wwadmin@stem:/opt/canvas$ sudo RAILS_ENV=production bundle exec rake db:initial_setup
[sudo] password for wwadmin: 
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': iconv will be deprecated in the future, use String#encode instead.
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /opt/canvas/Rakefile:11)
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /opt/canvas/Rakefile:11)
** Invoke db:initial_setup (first_time)
** Invoke db:generate_security_key (first_time)
** Execute db:generate_security_key
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
1: production:public
==  AddIndicesToQuizSubmissionEvents: migrating ===============================
-- add_index("quiz_submission_events_2015_2", :created_at, {:name=>"qse_2015_2_idx_on_created_at"})
   -> 0.0947s
-- add_index("quiz_submission_events_2015_2", [:quiz_submission_id, :attempt, :created_at], {:name=>"qse_2015_2_predecessor_locator_idx"})
   -> 0.0024s
-- add_foreign_key("quiz_submission_events_2015_2", :quiz_submissions)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateObject: ERROR:  constraint "quiz_submission_events_2015_2_quiz_submission_id_fk" for relation "quiz_submission_events_2015_2" already exists
: ALTER TABLE "quiz_submission_events_2015_2" ADD CONSTRAINT "quiz_submission_events_2015_2_quiz_submission_id_fk" FOREIGN KEY ("quiz_submission_id") REFERENCES "quiz_submissions"(id)/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/patches/sql_patches.rb:160:in `exec'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/patches/sql_patches.rb:160:in `async_exec'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/switchman/sharded_instrumenter.rb:19:in `instrument'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/switchman/active_record/abstract_adapter.rb:20:in `log_with_timestamp'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/foreigner-0.9.2/lib/foreigner/connection_adapters/sql_2003.rb:22:in `add_foreign_key'
/opt/canvas/config/initializers/active_record.rb:1051:in `add_foreign_key_with_delayed_validation'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:466:in `block in method_missing'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:438:in `block in say_with_time'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:438:in `say_with_time'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:458:in `method_missing'
/opt/canvas/db/migrate/20141115282315_add_indices_to_quiz_submission_events.partitions.rb:17:in `block in up'
/opt/canvas/gems/canvas_partman/lib/canvas_partman/migration.rb:21:in `each'
/opt/canvas/gems/canvas_partman/lib/canvas_partman/migration.rb:21:in `with_each_partition'
/opt/canvas/db/migrate/20141115282315_add_indices_to_quiz_submission_events.partitions.rb:8:in `up'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block in migrate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/switchman/connection_pool_proxy.rb:11:in `with_connection'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:338:in `migrate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/opt/canvas/config/initializers/active_record.rb:1370:in `block (2 levels) in migrate'
/opt/canvas/config/initializers/active_record.rb:1384:in `block in ddl_transaction'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/opt/canvas/config/initializers/active_record.rb:1384:in `ddl_transaction'
/opt/canvas/config/initializers/active_record.rb:1368:in `block in migrate'
/opt/canvas/config/initializers/active_record.rb:1344:in `each'
/opt/canvas/config/initializers/active_record.rb:1344:in `migrate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:570:in `up'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/migration.rb:551:in `migrate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/tasks/switchman.rake:70:in `call'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/tasks/switchman.rake:70:in `each'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/tasks/switchman.rake:70:in `block (4 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/switchman/database_server.rb:93:in `unshackle'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/tasks/switchman.rake:69:in `block (3 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/app/models/switchman/shard.rb:287:in `block (2 levels) in with_each_shard'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/app/models/switchman/shard.rb:55:in `activate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/app/models/switchman/shard.rb:461:in `activate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/app/models/switchman/shard.rb:285:in `block in with_each_shard'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/app/models/switchman/shard.rb:281:in `with_each_shard'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/tasks/switchman.rake:64:in `block (2 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/switchman/shackles.rb:22:in `activate'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.22/lib/tasks/switchman.rake:13:in `block in shardify_task'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/opt/canvas/vendor/bundle/ruby/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/opt/canvas/vendor/bundle/ruby/1.9.1/bin/rake:23:in `load'
/opt/canvas/vendor/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
Tasks: TOP => db:initial_setup => db:migrate
wwadmin@stem:/opt/canvas$
```

**Comment by simonista** [comment]
Hey @stumari, I just replicated this issue on a fresh install myself, I can verify it's a problem with our database migration code, not anything about your environment.  We'll get this resolved and let you know, sorry for the trouble!

**Comment by simonista** [comment]
Hey @stumari, looks like this commit actually fixes the issue: 65cd872f8e1163be9dbeb99795320d28b6be6069.  I just updated the stable branch to include it, so if you pull the latest, it should be fixed.

**Comment by stumari** [comment]
Thank you!

**Comment by vhcoder** [comment]
Hello,
I am having this exact same issue -followed the instructions to the letter till the DB migration, and then hit by the same error.
- the only difference is that I am on PgSQL 10.  
Any insight would be welcome!
Thank you!
