### ISSUE TITLE
Mysql migration error

### ISSUE THREAD

**Issue by kurapatijayaram** [instructure/canvas-lms#598]
Hi,

While performing 'rake db:initial_setup' at some point I am getting the following error ....

Mysql2::Error: FUNCTION canvas_production.pg_advisory_xact_lock does not exist: SELECT pg_advisory_xact_lock(half_md5_as_bigint('long_datafixups'))/home/heresy/canvas_production/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/rack-mini-profiler-0.9.1/lib/patches/sql_patches.rb:45:in `query'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/sharded_instrumenter.rb:19:in `instrument'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/active_record/abstract_adapter.rb:20:in `log_with_timestamp'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/canvas-jobs-0.9.11/lib/delayed/backend/active_record.rb:42:in `lock_strand_on_create'
(eval):7:in `run_callbacks'
/home/heresy/canvas_production/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
/home/heresy/canvas_production/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `run_callbacks'
/home/heresy/canvas_production/config/initializers/active_record.rb:1554:in `block in run_callbacks'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `block in scoping'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/scoping.rb:98:in `with_scope'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `scoping'
/home/heresy/canvas_production/config/initializers/active_record.rb:1554:in `run_callbacks'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:268:in `create'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/persistence.rb:348:in `create_or_update'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `block in create_or_update'
(eval):14:in `run_callbacks'
/home/heresy/canvas_production/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
/home/heresy/canvas_production/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `run_callbacks'
/home/heresy/canvas_production/config/initializers/active_record.rb:1554:in `block in run_callbacks'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `block in scoping'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/scoping.rb:98:in `with_scope'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `scoping'
/home/heresy/canvas_production/config/initializers/active_record.rb:1554:in `run_callbacks'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `create_or_update'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/persistence.rb:84:in `save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/validations.rb:50:in `save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:22:in `save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:42:in `block in transaction'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/active_record/relation.rb:91:in `activate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:37:in `transaction'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:259:in `block in save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:258:in `save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:85:in `block in save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `block in scoping'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/scoping.rb:98:in `with_scope'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `scoping'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:85:in `save'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/persistence.rb:45:in `create'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/canvas-jobs-0.9.11/lib/delayed/backend/base.rb:75:in `enqueue'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/canvas-jobs-0.9.11/lib/delayed/message_sending.rb:32:in `send_later_enqueue_args'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/canvas-jobs-0.9.11/lib/delayed/message_sending.rb:71:in `send_later_if_production_enqueue_args'
/home/heresy/canvas_production/db/migrate/20131003221953_populate_submission_versions.rb:5:in `up'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:370:in `up'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:410:in `block in migrate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:338:in `migrate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/home/heresy/canvas_production/config/initializers/active_record.rb:1385:in `block (2 levels) in migrate'
/home/heresy/canvas_production/config/initializers/active_record.rb:1401:in `ddl_transaction'
/home/heresy/canvas_production/config/initializers/active_record.rb:1383:in `block in migrate'
/home/heresy/canvas_production/config/initializers/active_record.rb:1359:in `each'
/home/heresy/canvas_production/config/initializers/active_record.rb:1359:in `migrate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:570:in `up'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/migration.rb:551:in `migrate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/tasks/switchman.rake:51:in `call'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/tasks/switchman.rake:51:in `each'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/tasks/switchman.rake:51:in `block (4 levels) in shardify_task'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/database_server.rb:93:in `unshackle'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/tasks/switchman.rake:50:in `block (3 levels) in shardify_task'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/app/models/switchman/shard.rb:128:in `with_each_shard'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/tasks/switchman.rake:45:in `block (2 levels) in shardify_task'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/switchman/shackles.rb:22:in `activate'
/home/heresy/canvas_production/vendor/bundle/ruby/2.0.0/gems/switchman-1.2.28/lib/tasks/switchman.rake:19:in `block in shardify_task'
Tasks: TOP => db:initial_setup => db:migrate
(See full trace by running task with --trace)

Please help me ....
Thank you

**Comment by kurapatijayaram** [comment]
I came to know that support for mysql was no longer exists from July '12 :-(

source : https://groups.google.com/forum/#!topic/canvas-lms-users/_h2t-0IJg1I
