### ISSUE TITLE
Quiz Submission Notification Error

### ISSUE THREAD

**Issue by pyros2097** [instructure/canvas-lms#607]
I'm running canvas in development mode using docker-canvas and Sometimes when I submit a Quiz I get this error and once this happens the same error occurs again and again on the quiz show page. Is this related the not starting the notification jobs in development?

```sh
id" = 1 AND "feature_flags"."context_type" = 'Course' AND "feature_flags"."feature" = 'differentiated_assignments' LIMIT 1  [shard 1 master]
[- 271ebb30-ab8b-0132-c83a-07734cc4462f]   SQL  (0.4ms)  ROLLBACK  [shard 1 master]
[- 271ebb30-ab8b-0132-c83a-07734cc4462f] 
ActiveRecord::AssociationTypeMismatch (Notification(#189668820) expected, got Notification(#184876540)):
  /var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/belongs_to_association.rb:6:in `replace'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/singular_association.rb:17:in `writer'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/associations/builder/association.rb:51:in `block in define_writers'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_assignment.rb:85:in `block in assign_attributes'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_assignment.rb:78:in `each'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/base.rb:498:in `initialize'
  /var/canvas/app/models/delayed_notification.rb:50:in `new'
  /var/canvas/app/models/delayed_notification.rb:50:in `process'
  /var/canvas/gems/plugins/delayed_job/lib/delayed/message_sending.rb:78:in `send_later_if_production_enqueue_args'
  /var/canvas/app/models/notifier.rb:7:in `send_notification'
  /var/canvas/gems/broadcast_policy/lib/broadcast_policy/notification_policy.rb:87:in `broadcast'
  /var/canvas/gems/broadcast_policy/lib/broadcast_policy/policy_list.rb:33:in `block in broadcast'
  /var/canvas/gems/broadcast_policy/lib/broadcast_policy/policy_list.rb:33:in `each'
  /var/canvas/gems/broadcast_policy/lib/broadcast_policy/policy_list.rb:33:in `broadcast'
  /var/canvas/gems/broadcast_policy/lib/broadcast_policy/instance_methods.rb:65:in `broadcast_notifications'
  (eval):120:in `run_callbacks'
  /var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
  /var/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `run_callbacks'
  /var/canvas/config/initializers/active_record.rb:1593:in `block in run_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation.rb:241:in `block in scoping'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/scoping.rb:98:in `with_scope'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation.rb:241:in `scoping'
  /var/canvas/config/initializers/active_record.rb:1593:in `run_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/callbacks.rb:264:in `create_or_update'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/persistence.rb:84:in `save'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/validations.rb:50:in `save'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods/dirty.rb:22:in `save'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:208:in `transaction'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.21/lib/switchman/active_record/base.rb:42:in `block in transaction'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.21/lib/switchman/active_record/relation.rb:89:in `activate'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.21/lib/switchman/active_record/base.rb:37:in `transaction'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:259:in `block in save'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:258:in `save'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.21/lib/switchman/active_record/base.rb:85:in `block in save'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation.rb:241:in `block in scoping'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/scoping.rb:98:in `with_scope'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation.rb:241:in `scoping'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.21/lib/switchman/active_record/base.rb:85:in `save'
  /var/canvas/app/models/quizzes/submission_grader.rb:41:in `block in grade_submission'
  /var/canvas/gems/plugins/simply_versioned/lib/simply_versioned.rb:144:in `with_versioning'
  /var/canvas/app/models/quizzes/submission_grader.rb:40:in `grade_submission'
  /var/canvas/app/controllers/quizzes/quizzes_controller.rb:274:in `show'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:167:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:657:in `block in _run__4131672270557862777__process_action__373825994300077953__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_30649'
  /var/canvas/app/controllers/application_controller.rb:196:in `set_locale'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_30649'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:447:in `_run__4131672270557862777__process_action__373825994300077953__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/callbacks.rb:17:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/base.rb:121:in `process'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/abstract_controller/rendering.rb:45:in `process'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:203:in `dispatch'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_controller/metal.rb:246:in `block in action'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:36:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/routing/route_set.rb:608:in `call'
  /var/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/head.rb:14:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  /var/canvas/lib/canvas/request_throttle.rb:58:in `block in call'
  /var/canvas/lib/canvas/request_throttle.rb:229:in `reserve_capacity'
  /var/canvas/lib/canvas/request_throttle.rb:54:in `call'
  /var/canvas/app/middleware/stats_timing.rb:8:in `block in call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  /var/canvas/app/middleware/stats_timing.rb:8:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/flash.rb:242:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/encrypted_cookie_store-instructure-1.1.8/lib/encrypted_cookie_store.rb:45:in `call'
  /var/canvas/app/middleware/sessions_timeout.rb:22:in `call'
  /var/canvas/app/middleware/load_account.rb:12:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/query_cache.rb:64:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `_run__4014728572390332437__call__238190533153361740__callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:405:in `__run_callback'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.19/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/reloader.rb:65:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:32:in `call_app'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/rack/logger.rb:18:in `call'
  /var/canvas/app/middleware/request_context_generator.rb:34:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  /var/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.19/lib/action_dispatch/middleware/static.rb:63:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiler.rb:193:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:484:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:231:in `call'
  /var/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/request_handler.rb:97:in `process_request'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_request_handler.rb:520:in `accept_and_process_next_request'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/utils.rb:470:in `safe_fork'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/lib/ruby/1.9.1/phusion_passenger/rack/application_spawner.rb:129:in `start'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in `synchronize'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/1.9.1/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99:in `<main>'
```

**Comment by simonista** [comment]
We've seen this in development mode too, and we're pretty sure it's a code reloading problem.  Unfortunately canvas is a little unstable with things like spring or dev reload at the moment, so for now the safest way is to just restart your server when you change code.
