### ISSUE TITLE
URI::InvalidURIError compiling assets

### ISSUE THREAD

**Issue by strocode** [instructure/canvas-lms#637]
Hi,

(I raised this at the [forum]  (https://groups.google.com/forum/#!topic/canvas-lms-users/ua_kQYZQ3_Q) but thought a ticket might be more suitable.)

I'm upgrading a Canvas installation (and I'm a complete noob when it comes to canvas & ruby).

Ubuntu 14.04.2 LTS
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Canvas from git:
commit 5cbb96b79c3e814a6e474ac630ef4013e64c5fab
Merge: 0ec3df3 84e04f1
Author: Cody Cutrer <cody@....>
Date:   Mon Dec 8 12:51:04 2014 -0700

Running

`bundle exec rake canvas:compile_assets --trace`
Jammit complains about a bunch of missing assets, then

`URI::InvalidURIError: bad URI(is not URI?): #{$url-path-to-this-file}images/sort-desc.gif`

Looks like this:
```
keith@steamer:/var/canvas$ bundle exec rake canvas:compile_assets --trace | tee /tmp/badcompile.txt
/var/canvas/gems/utf8_cleaner/lib/utf8_cleaner.rb:20:in `<top (required)>': iconv will be deprecated in the future, use String#encode instead.
** Invoke canvas:compile_assets (first_time)
** Execute canvas:compile_assets
working in 1 processes
--> Starting: 'Compile sass and make jammit css bundles'
--> Starting: 'npm run compile-sass'
 
> canvas-lms@0.0.0 compile-sass /var/canvas
> node script/compile-sass.js
 
--> Finished: 'npm run compile-sass' in 125.646636244
--> Starting: 'Jammit'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/react_files/compiler-react_files.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/instructure_eportfolio.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/course_show.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/legacy_normal_contrast/pages/course_list.css'

... [ Bunch more Jammit Warnings ] ...

Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/all_courses.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/pages/external_tools/full_width.css'
Jammit Warning: No assets match 'public/stylesheets_compiled/k12_high_contrast/client_apps/canvas_quiz_statistics.css'
rake aborted!
URI::InvalidURIError: bad URI(is not URI?): #{$url-path-to-this-file}images/sort-desc.gif
/usr/lib/ruby/1.9.1/uri/common.rb:176:in `split'
/usr/lib/ruby/1.9.1/uri/common.rb:211:in `parse'
/usr/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/compressor.rb:158:in `block (2 levels) in concatenate_and_tag_assets'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/compressor.rb:156:in `gsub'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/compressor.rb:156:in `block in concatenate_and_tag_assets'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/compressor.rb:154:in `map'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/compressor.rb:154:in `concatenate_and_tag_assets'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/compressor.rb:95:in `compress_css'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/packager.rb:79:in `pack_stylesheets'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/packager.rb:38:in `block in precache_all'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/packager.rb:37:in `each'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit/packager.rb:37:in `precache_all'
/home/keith/.bundler/ruby/1.9.1/jammit-98b50a67029c/lib/jammit.rb:146:in `package!'
/var/canvas/lib/tasks/canvas.rake:131:in `block (4 levels) in <top (required)>'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:129:in `block (3 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:168:in `call'
/var/canvas/lib/tasks/canvas.rake:168:in `block (5 levels) in <top (required)>'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:168:in `block (4 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:275:in `call'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:275:in `call_with_index'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:225:in `process_incoming_jobs'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:203:in `block in worker'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:196:in `fork'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:196:in `worker'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:181:in `block in create_workers'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:180:in `each'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:180:in `create_workers'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:144:in `work_in_processes'
/var/lib/gems/1.9.1/gems/parallel-0.5.16/lib/parallel.rb:55:in `map'
/var/canvas/lib/tasks/canvas.rake:167:in `block (3 levels) in <top (required)>'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/canvas/lib/tasks/canvas.rake:166:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => canvas:compile_assets
keith@steamer:/var/canvas$
keith@steamer:/var/canvas$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

```

Full trace:
http://pastebin.com/vqg8yTKs

**Comment by nkokkos** [comment]
Did you run:
``npm install`` 
at the root of the canvas installation after upgrading and before running:
``bundle exec rake canvas:compile_assets --trace``? 
``npm install``  has to be executed after every git pull upgrade. That's what I have experienced.

**Comment by strocode** [comment]
Hi nkokkos,

I gave up on upgrading the `/var/canvas` area (I've already done the SQL migration though).

Last night I did a completely fresh git clone, and did everything according to the installation instructions in a brand new /var/canvas, which included an `npm install` before the `bundle exec rake canvas:compile_assets --trace`. I had to do a 'mkdir -p public/stylesheets_compiled` though. Still the same `InvalidURIError` :-( (thanks to shawniverson on IRC for talking me through a few things). 

We did narrow the InvalidURIError down to this line in `jammit/compressor.rb`. Is it possible that URI.parse used to return a boolean, but now throws an InvalidURIError? Have I somehow got the wrong version of Jammit?

```
ipath, cpath = Pathname.new($1), Pathname.new(File.expand_path(css_path))
          is_url = URI.parse($1).absolute? <<< ERROR HERE
          is_url ? url : "url(#{construct_asset_path(ipath, cpath, variant)})"
```

Does anyone else get those Jammit warnings? It looks like the previous step before Jammit, which is  `npm run compile-sass` might not be generating all the CSS, but I can't find any log files to work out why.


K

**Comment by strocode** [comment]
I wonder whether Ubuntu has some funny packaging going on? Bundle seems to want to use ruby 1.9.1 and installs gems in that directory but the default ruby command is 1.9.3

```
keith@steamer:/var/canvas$ head -n 1 `which bundle`
#!/usr/bin/ruby1.9.1
keith@steamer:/var/canvas$ ls vendor/bundle/ruby/
1.9.1
keith@steamer:/var/canvas$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
``

**Comment by claydiffrient** [comment]
@strocode Thanks for letting us know about this. We'll look into it.

**Comment by claydiffrient** [comment]
@strocode After looking at this a bit, I would definitely continue down the Ubuntu packaging path.  I'm not sure why it would be doing that, but it is very likely that that is the problem.  There aren't any recent changes in Canvas relating to CSS compilation so it's unlikely that it's an issue with Canvas itself.

**Comment by ccutrer** [comment]
The ruby 1.9.1 thing is simply an oddity of Debian packaging of Ruby 1.9.3, and is a red herring.

**Comment by strocode** [comment]
Thanks @claydiffrient  and @ccutrer. If there's anything I can do to help debug, letme know.

**Comment by strocode** [comment]
I worked out what the problem was. I was copying config/*.yml from my original canvas installation to the new one. Bad idea. Copying the original config/*.yml from the fresh git tree fixed the build problem.

Thanks for all your help. Sorry for being such a dope. Hope I didn't waste too much time.

K
