### ISSUE TITLE
 undefined method `default_locale_changed?'

### ISSUE THREAD

**Issue by derrickmar** [instructure/canvas-lms#655]
When running ```CODES.sh``` as specified on the getting started page, I'm getting an error when it tries to run the migrations

```
undefined method `default_locale_changed?' for #<Account:0x0000000efd4158>/home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in`instance_eval'
```

Does anyone know a fix? Thank you

Full stacktrace

```
undefined method `default_locale_changed?' for #<Account:0x0000000efd4158>/home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/attribute_methods.rb:149:in `method_missing'
(eval):564:in `run_callbacks'
/home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
/home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `run_callbacks'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in `block in run_callbacks'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `block in scoping'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/scoping.rb:98:in `with_scope'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `scoping'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in `run_callbacks'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activemodel/lib/active_model/validations.rb:228:in `run_validations!'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activemodel/lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
(eval):36:in `run_callbacks'
/home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
/home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `run_callbacks'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in `block in run_callbacks'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `block in scoping'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/scoping.rb:98:in `with_scope'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `scoping'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in `run_callbacks'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activemodel/lib/active_model/validations/callbacks.rb:53:in `run_validations!'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activemodel/lib/active_model/validations.rb:195:in `valid?'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/validations.rb:69:in `valid?'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/validations.rb:77:in `perform_validations'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/validations.rb:56:in `save!'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:264:in `block in save!'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:42:in `block in transaction'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/active_record/relation.rb:91:in `activate'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:37:in `transaction'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:264:in `save!'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:90:in `block in save!'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `block in scoping'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/scoping.rb:98:in `with_scope'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `scoping'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:90:in `save!'
/home/vagrant/canvas-lms/app/models/account.rb:1085:in `block in get_special_account'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/default_shard.rb:6:in `activate'
/home/vagrant/canvas-lms/app/models/account.rb:1066:in `get_special_account'
(eval):2:in `default'
/home/vagrant/canvas-lms/db/migrate/20121127212421_grandfather_default_account_invitation_previews.rb:6:in `up'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:370:in `up'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:410:in `block in migrate'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:389:in `migrate'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:338:in `migrate'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:528:in `migrate'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1453:in `block (2 levels) in migrate'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1467:in `block in ddl_transaction'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1467:in `ddl_transaction'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1451:in `block in migrate'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1427:in `each'
/home/vagrant/canvas-lms/config/initializers/active_record.rb:1427:in `migrate'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:570:in `up'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/migration.rb:551:in `migrate'
/home/vagrant/.bundler/ruby/1.9.1/rails-b344986bc3d9/activerecord/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/tasks/switchman.rake:51:in `call'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/tasks/switchman.rake:51:in `each'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/tasks/switchman.rake:51:in `block (4 levels) in shardify_task'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/database_server.rb:93:in `unshackle'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/tasks/switchman.rake:50:in `block (3 levels) in shardify_task'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/app/models/switchman/shard.rb:130:in `with_each_shard'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/tasks/switchman.rake:45:in `block (2 levels) in shardify_task'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/switchman/shackles.rb:22:in `activate'
/var/lib/gems/1.9.1/gems/switchman-1.2.35/lib/tasks/switchman.rake:19:in `block in shardify_task'
Tasks: TOP => db:initial_setup => db:migrate
(See full trace by running task with --trace)
```

**Comment by fmarkwong** [comment]
@derrickmar . I ran into the same thing and had to redo db initialization with `rake db:initial_setup` for it to work.  I'm not sure why it doesn't work the first time.

After starting up and attempting to log in, I ran into other issues that @claydiffrient helped me to work around here  https://github.com/instructure/canvas-lms/issues/654 .

**Comment by derrickmar** [comment]
Hey Mark thanks. Yeah had to drop the database because of a duplicate table error but I'll see if it works after that.

**Comment by simonista** [comment]
I believe this issue has been fixed by b247cd4517f4aae0845e4800286de28551241f4a.  Sorry for the trouble!

**Comment by derrickmar** [comment]
@simonista not sure if this has been merged in yet, but when you run the script this is still happening.

**Comment by ccutrer** [comment]
It has not been merged to the stable branch yet. I'm waiting on another fix (the rspec-support gem) to get through our testing process, then I'm going to get both of them onto the stable branch.

**Comment by ccutrer** [comment]
The fix has been pushed to the stable branch now.
