### ISSUE TITLE
Error: running BrandableCSS CLI

### ISSUE THREAD

**Issue by chrisjoywebb** [instructure/canvas-lms#666]
Hey again,

I'm running the automated install script on a brand new EC2 Ubuntu 14.04 server and run into 2 problems:

First:
```
https://github.com/maneframe/mocha.git (at bb8813f) is not yet checked out. Run `bundle install` first.

The asset compilation failed.
You can continue setup but the assets will need to be
successfully built before you can run Canvas
(You build them with 'bundle exec rake canvas:compile_assets')
Continue with setup? ([Y]/N):
```

At this point I continue with the setup which goes through database creation, population, etc. It finishes successfully.

I then run,
```
bundle exec rake canvas:compile_assets
```

which errors out while logging this:
```
Killed
rake aborted!
Error: running BrandableCSS CLI: ./node_modules/.bin/brandable_css 2>&1
/home/ubuntu/canvas-lms/lib/brandable_css.rb:102:in `run_cli!'
/home/ubuntu/canvas-lms/lib/brandable_css.rb:85:in `compile_all!'
/home/ubuntu/canvas-lms/lib/tasks/canvas.rake:121:in `block (3 levels) in <top (required)>'
/home/ubuntu/canvas-lms/lib/tasks/canvas.rake:7:in `log_time'
/home/ubuntu/canvas-lms/lib/tasks/canvas.rake:121:in `block (2 levels) in <top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

Does anyone know a workaround for this?

Thanks,
Chris

**Comment by chrisjoywebb** [comment]
Also, this is running the most recent version of Canvas as of today.

**Comment by ccutrer** [comment]
How much memory do you have? Is brandable_css getting killed because you're out of memory?

**Comment by chrisjoywebb** [comment]
That's very likely. We're testing it out on the free AWS tier which has 1GB of memory. Just realized that. I know that 2GB is the minimum recommended to run Canvas, so I'll see what we can do with more.

**Comment by chrisjoywebb** [comment]
The install script worked great on an EC2 instance with 2GB of RAM. Thanks!

**Comment by darmie** [comment]
I am running Canvas on a 2GB RAM machine but I still get the error

```
/usr/local/rvm/gems/ruby-2.1.6/bin/rake: No such file or directory - node
node is:
npm WARN lifecycle canvas-lms@0.0.0~preinstall: cannot run in wd %s %s (wd=%s) canvas-lms@0.0.0 script/gem_npm install /root/BeniAmerican
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN i18nliner-handlebars@0.2.0 requires a peer of i18nliner@~0.1.5 but none was installed.
npm WARN instructure-icons@0.0.8 requires a peer of react@^0.14.7 || ^15.0.0 but none was installed.
npm WARN instructure-icons@0.0.8 requires a peer of react-dom@^0.14.7 || ^15.0.0 but none was installed.
npm WARN instructure-ui@0.13.3 requires a peer of react@^0.14.7 || ~15.1.0 but none was installed.
npm WARN instructure-ui@0.13.3 requires a peer of react-dom@^0.14.7 || ~15.1.0 but none was installed.
npm WARN react-addons-css-transition-group@15.1.0 requires a peer of react@^15.1.0 but none was installed.
npm WARN react-overlays@0.6.6 requires a peer of react@>=0.14.0 but none was installed.
npm WARN react-overlays@0.6.6 requires a peer of react-dom@>=0.14.0 but none was installed.
npm WARN react-prop-types@0.4.0 requires a peer of react@>=0.14.0 but none was installed.
--> Finished: 'Making sure node_modules are up to date' in 11.828068983
** Invoke css:compile (first_time)
** Execute css:compile
--> Starting: 'compile css (including custom brands)'
rake aborted!
Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css
/root/BeniAmerican/lib/brandable_css.rb:266:in `block in run_cli!'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/open3.rb:188:in `popen2e'
/root/BeniAmerican/lib/brandable_css.rb:252:in `run_cli!'
/root/BeniAmerican/lib/brandable_css.rb:232:in `compile_all!'
/root/BeniAmerican/lib/tasks/css.rake:12:in `block (3 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/root/BeniAmerican/lib/tasks/css.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/root/BeniAmerican/lib/tasks/canvas.rake:126:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.6/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.6/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.1.6/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => css:compile
```

**Comment by darmie** [comment]
I fixed it by running `npm install node-sass`

**Comment by anmolsahoo25** [comment]
Hey Darmie, Could you tell me how you found out that issue? Even I had the same issue, but could not have debugged it, if I didn't find your post.
