### ISSUE TITLE
Assets not being served in RAILS_ENV=production

### ISSUE THREAD

**Issue by chrisjoywebb** [instructure/canvas-lms#671]
Hey hey,

I've successfully gone through the Production Start tutorial on a clean Ubuntu 14.04 server (including compiling of assets) except for one issue.

Assets are being loaded for RAILS_ENV=development, but not for RAILS_ENV=production. Here are the log errors:

```
ActionController::RoutingError (No route matches [GET] "/dist/brandable_css/legacy_normal_contrast/bundles/common-ddc5a1521e.css"):
  app/middleware/request_context_generator.rb:36:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
``` 

```
ActionController::RoutingError (No route matches [GET] "/dist/brandable_css/legacy_normal_contrast/bundles/login-893b221786.css"):
  app/middleware/request_context_generator.rb:36:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```

```
ActionController::RoutingError (No route matches [GET] "/dist/optimized/vendor/require-749d0c60e9.js"):
  app/middleware/request_context_generator.rb:36:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```

```
ActionController::RoutingError (No route matches [GET] "/dist/optimized/compiled/bundles/common-5258b2411b.js"):
  app/middleware/request_context_generator.rb:36:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```

```
ActionController::RoutingError (No route matches [GET] "/dist/optimized/compiled/bundles/login-3076cdd73b.js"):
  app/middleware/request_context_generator.rb:36:in `call'
  app/middleware/prevent_non_multipart_parse.rb:32:in `call'
```

No errors arise in development.

Any insight would be much appreciated. Thanks!

**Comment by chrisjoywebb** [comment]
This issue has been resolved.

**Comment by ivanatista** [comment]
Hi Chris, I'm having the same problem, how did you solve this problem?

**Comment by darmie** [comment]
@chrisjoywebb how was this issue resolved? I am having the same problem

**Comment by odedara** [comment]
@chrisjoywebb How did you fix this? I am having the same error

**Comment by odedara** [comment]
@ivanatista @darmie Have you fix this?
