### ISSUE TITLE
[Help] Problem to boot

### ISSUE THREAD

**Issue by candidosales** [instructure/canvas-lms#699]
I did an update and are experiencing this error:
 
**/var/log/apache2/error.log**
```
[ 2015-10-01 10:50:29.0065 11899/7f7940daf700 Pool2/Pool.h:777 ]: Process (pid=14321, group=/home/ubuntu/canvas#default) no longer exists! Detaching it from the pool.
App 14330 stdout:
App 11978 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:356:in `trap'
App 11978 stderr: : Invalid argument - SIGKILL (Errno::EINVAL)
App 11978 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:356:in `block in reset_signal_handlers'
App 11978 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:354:in `each_key'
App 11978 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:354:in `reset_signal_handlers'
App 11978 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:182:in `main_loop'
App 11978 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:161:in `<module:App>'
App 11978 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
App 11978 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'
```
**/var/log/apache2/canvas_error.log**
```
[Thu Oct 01 10:34:59.497609 2015] [core:error] [pid 11914:tid 140364187125504] [client 187.125.24.210:54318] End of script output before headers:
```

gem env
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.2.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.2
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/ubuntu/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.2.0
     - /home/ubuntu/.gem/ruby/2.2.0
     - /usr/share/rubygems-integration/2.2.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
```
Does anyone know what is the problem?

**Comment by candidosales** [comment]
Already found the problem, there were two passengers installed. The gem uninstalled, reinstalled via 
```
sudo apt-get install libapache2-mod-passenger -y
```
Reconfigured and it worked ...

This link helped me: https://www.phusionpassenger.com/library/install/apache/install/oss/trusty/
