### ISSUE TITLE
RAILS_ENV=development bundle exec rake canvas:compile_assets cannot compile css

### ISSUE THREAD

**Issue by sansarp** [instructure/canvas-lms#701]
When I run RAILS_ENV=development bundle exec rake canvas:compile_assets I get the following error.

```
###
error compiling sass [TypeError: Cannot call method 'parse' of undefined] TypeError: Cannot call method 'parse' of undefined
    at cssFilename (/home/subash/canvas-lms/node_modules/brandable_css/lib/main.js:617:51)
    at writeCss (/home/subash/canvas-lms/node_modules/brandable_css/lib/main.js:650:18)
    at callee$0$0$ (/home/subash/canvas-lms/node_modules/brandable_css/lib/main.js:598:41)
###
    at tryCatch (/home/subash/canvas-lms/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/subash/canvas-lms/node_modules/babel-core/node_modules/regenerator/runtime.js:323:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/subash/canvas-lms/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (/home/subash/canvas-lms/node_modules/babel-core/node_modules/regenerator/runtime.js:132:37)
    at run (/home/subash/canvas-lms/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /home/subash/canvas-lms/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/home/subash/canvas-lms/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at process._tickDomainCallback (node.js:492:13) Cannot call method 'parse' of undefined
--> Finished: 'compile css (including custom brands)' in 12.264115657
working in 4 processes
--> Starting: 'css:styleguide'--> Starting: 'compile coffee, js 18n, and run r.js optimizer'
```

The app works fine but I cannot see the design as css files are not compiled. 
Here is the working screenshot of the app without design.

![canvas_err](https://cloud.githubusercontent.com/assets/3773443/10272456/6ff40f8c-6b3f-11e5-80aa-545fc3dbbc84.png)

Any help would be highly appreciated.

**Comment by claydiffrient** [comment]
@subash This looks like an error that happens with Node < 12.5


Try upgrading your nose version and see if that helps.





—

**Comment by sansarp** [comment]
@claydiffrient I installed v0.12.7 but still getting the same error. 
I did this:
sudo apt-get autoremove node nodejs
nvm install 0.12.7
sudo apt-get install nodejs

```
error compiling sass [TypeError: Cannot call method 'parse' of undefined] TypeError: Cannot call method 'parse' of undefined
    at cssFilename (/home/subash/canvas-lms/node_modules/brandable_css/lib/main.js:617:51)
```

subash@subash-Aspire-E5-571:~/canvas-lms[stable]$ node -v
  v0.12.7
subash@subash-Aspire-E5-571:~/canvas-lms[stable]$ nodejs -v
  v0.10.40

**Comment by claydiffrient** [comment]
@sansarp Try doing `rm -rf node_modules && rm -rf gems/**/node_modules && npm cache clean && npm install` after you've upgraded to 0.12.7 then try and compile assets.

**Comment by williamflock** [comment]
@claydiffrient, your solution worked for me after I upgraded to 0.12.7.

Thank you
Bill
