### ISSUE TITLE
I can not compile assets... Need help

### ISSUE THREAD

**Issue by candidosales** [instructure/canvas-lms#722]
node: 0.12.7
npm: 3.3.12
ruby: 2.1.15
ubuntu: 14.04 LTS
```
ubuntu@ip-000-00-00-000:~/canvas$ bundle exec rake canvas:compile_assets --trace
** Invoke canvas:compile_assets (first_time)
** Execute canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global node-gyp@3.0.3 should be installed with -g
/home/ubuntu/canvas/node_modules/nopt/lib/nopt.js:210
    if (t && ((type.name && t.type.name) ?
                   ^
TypeError: Cannot read property 'name' of null
    at validate (/home/ubuntu/canvas/node_modules/nopt/lib/nopt.js:210:20)
    at validate (/home/ubuntu/canvas/node_modules/nopt/lib/nopt.js:179:11)
    at /home/ubuntu/canvas/node_modules/nopt/lib/nopt.js:101:12
    at Array.map (native)
    at /home/ubuntu/canvas/node_modules/nopt/lib/nopt.js:67:15
    at Array.forEach (native)
    at Function.clean (/home/ubuntu/canvas/node_modules/nopt/lib/nopt.js:55:21)
    at /home/ubuntu/canvas/node_modules/npmconf/npmconf.js:411:10
    at Array.forEach (native)
    at validate (/home/ubuntu/canvas/node_modules/npmconf/npmconf.js:410:11)
npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/canvas/npm-debug.log
--> Finished: 'Making sure node_modules are up to date' in 23.518886034
--> Starting: 'compile css (including custom brands)'
rake aborted!
Errno::ENOENT: No such file or directory - ./node_modules/.bin/brandable_css
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/open3.rb:193:in `spawn'
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/open3.rb:188:in `popen2e'
/home/ubuntu/canvas/lib/brandable_css.rb:106:in `run_cli!'
/home/ubuntu/canvas/lib/brandable_css.rb:86:in `compile_all!'
/home/ubuntu/canvas/lib/tasks/canvas.rake:121:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/ubuntu/canvas/lib/tasks/canvas.rake:7:in `log_time'
/home/ubuntu/canvas/lib/tasks/canvas.rake:121:in `block (2 levels) in <top (required)>'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => canvas:compile_assets
ubuntu@ip-000-00-00-000:~/canvas$
```

**Comment by FreedomBen** [comment]
Hi @candidosales .  You could be missing some required packages.  You can look at https://github.com/FreedomBen/canvas-development-tools/blob/master/CODES.sh#L219-L235 for clues.  You can also try the mailing list (https://groups.google.com/forum/#!forum/canvas-lms-users) for more immediate help.

**Comment by candidosales** [comment]
@FreedomBen I installed all dependencies to versions of wiki:
node: 0.12.7, npm: 2.11.3, ruby: 2.1.15

Removed all node_modules and reinstalled:
```
rm -rf node_modules && rm -rf gems/**/node_modules && npm cache clean && npm install 
```
...With this worked compile the assets, in the meantime a new error:

```
/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:218
      throw er
            ^
Error: EACCES, permission denied 'tmp/compiled'
```
Below all the log:
```
 bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
--> Finished: 'Making sure node_modules are up to date' in 4.690694049
--> Starting: 'compile css (including custom brands)'
brandable_css warning bundles/common.scss new_styles_normal_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_normal_contrast has an external url() to: http://www.vikstar.com.br/wp-content/themes/vikstar/dist/img/logo-200-canvas.svg that's not a problem but normally our css only links to files in our repo
brandable_css warning bundles/common.scss new_styles_normal_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/common.scss new_styles_normal_contrast  in 2321 ms
brandable_css warning bundles/common.scss legacy_normal_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_normal_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_high_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_high_contrast has an external url() to: http://www.vikstar.com.br/wp-content/themes/vikstar/dist/img/logo-200-canvas.svg that's not a problem but normally our css only links to files in our repo
brandable_css warning bundles/common.scss new_styles_high_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_high_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_high_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/common.scss legacy_normal_contrast  in 3385 ms
compiled bundles/common.scss new_styles_high_contrast  in 3383 ms
compiled bundles/common.scss legacy_high_contrast  in 3384 ms
skipping: bundles/common.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 0d68178b21 already exists. set BRANDABLE_CSS_FORCE_UPLOAD_EVEN_IF_EXISTS to generate anyway
--> Finished: 'compile css (including custom brands)' in 4.941486204
working in 2 processes
--> Starting: 'css:styleguide'--> Starting: 'compile coffee, js 18n, and run r.js optimizer'

--> Starting: 'js:generate'
--> creating styleguide
Building client app 'canvas_quizzes'
        Running 'npm install'...
npm WARN package.json canvas_quizzes@1.0.0 No repository field.
npm WARN package.json canvas_quizzes@1.0.0 No license field.
        Running 'npm run build'...
/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:218
      throw er
            ^
Error: EACCES, permission denied 'tmp/compiled'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:883:18)
    at rimrafSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:211:13)
    at /home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:244:26)
    at rmdirSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:237:7)
    at Function.rimrafSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:219:5)
    at Object.rmrfSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/lib/remove.js:7:19)
    at Object.<anonymous> (/home/ubuntu/canvas/client_apps/canvas_quizzes/script/build:16:4)
            -------------------------------------------------------------------
            BUILD FAILURE:

            -------------------------------------------------------------------
# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 4.433677676
rake aborted!
Undumpable Exception -- #<RuntimeError: Build script failed for client app canvas_quizzes>
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

```

**Comment by wizkid686** [comment]
Have you tried running npm install before bundle exec rake canvas:compile_assets? I usually run the npm install first before the compile assets command. Also, make sure that canvasuser has permissions in a few areas, including that one. Try this command: 
sudo chown -R canvasuser config/environment.rb log tmp public/assets \
                              public/stylesheets/compiled Gemfile.lock config.ru

Then try an npm install, followed by the compile assets command. Also, after the initial install, you will have to run bundle commands as root because of the permissions changes. Since npm install does not like running as root (will fail quickly/silently), make sure to run that before your compile assets command.

**Comment by candidosales** [comment]
@wizkid686 It occurred the same mistake:

```
ubuntu@ip-000-00-00-000:~/canvas$ sudo chown -R canvasuser config/environment.rb                                                                                         log tmp public/assets \
> public/stylesheets/compiled Gemfile.lock config.ru
ubuntu@ip-000-00-00-000:~/canvas$ ls -la
total 1604
drwxrwxr-x 24 ubuntu     ubuntu    4096 Nov 13 12:21 .
drwxr-xr-x 21 ubuntu     ubuntu    4096 Nov 13 13:58 ..
drwxrwxr-x 14 ubuntu     ubuntu    4096 Oct  1 08:16 app
drwxrwxr-x  2 ubuntu     ubuntu    4096 Oct  1 08:16 bin
-rw-rw-r--  1 ubuntu     ubuntu    1098 Nov  9 11:11 bower.json
-rw-rw-r--  1 ubuntu     ubuntu      46 Oct  1 08:16 .bowerrc
drwxrwxr-x  2 ubuntu     ubuntu    4096 Nov 13 11:30 build
drwxrwxr-x  2 ubuntu     ubuntu    4096 Oct  1 08:21 .bundle
drwxrwxr-x  3 ubuntu     ubuntu    4096 Oct  1 08:16 client_apps
-rw-rw-r--  1 ubuntu     ubuntu    1676 Oct  1 08:16 code_of_conduct.md
drwxrwxrwt  5 ubuntu     ubuntu    4096 Nov 13 13:58 config
-rw-rw-r--  1 canvasuser ubuntu     236 Nov  9 11:11 config.ru
-rw-rw-r--  1 ubuntu     ubuntu    4799 Oct  1 08:16 CONTRIBUTING.md
-rw-rw-r--  1 ubuntu     ubuntu     621 Oct  1 08:16 COPYRIGHT
drwxrwxr-x  3 ubuntu     ubuntu    4096 Oct  1 08:16 db
drwxrwxr-x  7 ubuntu     ubuntu    4096 Nov  9 11:11 doc
drwxrwxr-x  5 ubuntu     ubuntu    4096 Nov  9 11:11 docker-compose
-rw-rw-r--  1 ubuntu     ubuntu    1107 Nov  9 11:11 docker-compose.yml
-rw-rw-r--  1 ubuntu     ubuntu      27 Oct  1 08:16 .dockerignore
-rw-rw-r--  1 ubuntu     ubuntu      18 Oct 26 15:40 dump.rdb
-rw-rw-r--  1 ubuntu     ubuntu       0 Nov 13 12:21 Finished:
-rw-rw-r--  1 ubuntu     ubuntu   20176 Nov  9 11:11 .fontcustom-manifest.json
-rw-rw-r--  1 ubuntu     ubuntu    1103 Oct  1 08:16 Gemfile
drwxrwxr-x  2 ubuntu     ubuntu    4096 Nov  9 11:11 Gemfile.d
-rw-rw-r--  1 canvasuser ubuntu   24891 Nov  9 11:13 Gemfile.lock
drwxrwxr-x 52 ubuntu     ubuntu    4096 Oct  1 08:16 gems
drwxrwxr-x  8 ubuntu     ubuntu    4096 Nov  9 11:43 .git
-rw-rw-r--  1 ubuntu     ubuntu    1650 Nov  9 11:11 .gitignore
drwxrwxr-x  2 ubuntu     ubuntu    4096 Oct  1 08:16 guard
-rw-rw-r--  1 ubuntu     ubuntu     852 Oct  1 08:16 Guardfile
-rw-rw-r--  1 ubuntu     ubuntu    1630 Oct  1 08:16 gulpfile.babel.js
-rw-rw-r--  1 ubuntu     ubuntu      65 Oct  1 08:16 .i18nignore
-rw-rw-r--  1 ubuntu     ubuntu    1742 Oct  1 08:16 .jshintrc
-rw-rw-r--  1 ubuntu     ubuntu    2204 Oct  1 08:16 karma.conf.js
drwxrwxr-x 20 ubuntu     ubuntu    4096 Nov  9 11:11 lib
-rw-rw-r--  1 ubuntu     ubuntu   34520 Oct  1 08:16 LICENSE
drwxrwxrwt  2 canvasuser ubuntu    4096 Nov 13 13:48 log
drwxrwxr-x 27 ubuntu     ubuntu    4096 Nov 13 12:10 node_modules
-rw-rw-r--  1 ubuntu     ubuntu      18 Nov  9 11:11 .npmrc
-rw-rw-r--  1 ubuntu     ubuntu    1127 Nov  9 11:11 package.json
drwxrwxrwt 14 ubuntu     ubuntu    4096 Nov 13 11:55 public
-rw-rw-r--  1 ubuntu     ubuntu     434 Oct  1 08:16 Rakefile
-rw-rw-r--  1 ubuntu     ubuntu     582 Oct  1 08:16 README.md
-rw-rw-r--  1 ubuntu     ubuntu    3221 Nov  9 11:11 .rubocop.yml
drwxrwxr-x  4 ubuntu     ubuntu    4096 Nov 13 11:58 script
drwxrwxr-x 24 ubuntu     ubuntu    4096 Nov  9 11:11 spec
drwxrwxrwt  6 canvasuser ubuntu    4096 Nov 12 18:09 tmp
-rw-rw-r--  1 ubuntu     ubuntu    1242 Oct  1 08:16 .travis.yml
-rw-rw-r--  1 ubuntu     ubuntu 1359872 Oct  1 12:55 typescript
drwxrwxr-x  3 ubuntu     ubuntu    4096 Oct  1 08:21 vendor
drwxr-xr-x  3 root       root      4096 Nov 12 18:12 .yardoc
ubuntu@ip-000-00-00-000:~/canvas$ npm install

> canvas-lms@0.0.0 preinstall /home/ubuntu/canvas
> script/gem_npm install

ubuntu@ip-000-00-00-000:~/canvas$ bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
--> Finished: 'Making sure node_modules are up to date' in 4.791863975
--> Starting: 'compile css (including custom brands)'
brandable_css warning bundles/common.scss new_styles_normal_contrast contains a                                                                                         url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_normal_contrast has an exte                                                                                        rnal url() to: http://www.vikstar.com.br/wp-content/themes/vikstar/dist/img/logo                                                                                        -200-canvas.svg that's not a problem but normally our css only links to files in                                                                                         our repo
brandable_css warning bundles/common.scss new_styles_normal_contrast contains a                                                                                         url() to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/common.scss new_styles_normal_contrast  in 2331 ms
brandable_css warning bundles/common.scss legacy_normal_contrast contains a url(                                                                                        ) to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_normal_contrast contains a url(                                                                                        ) to: /images/mediaelement/skipback.png which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_high_contrast contains a ur                                                                                        l() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_high_contrast has an extern                                                                                        al url() to: http://www.vikstar.com.br/wp-content/themes/vikstar/dist/img/logo-2                                                                                        00-canvas.svg that's not a problem but normally our css only links to files in o                                                                                        ur repo
brandable_css warning bundles/common.scss new_styles_high_contrast contains a ur                                                                                        l() to: /images/mediaelement/skipback.png which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_high_contrast contains a url()                                                                                         to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_high_contrast contains a url()                                                                                         to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/common.scss legacy_normal_contrast  in 3375 ms
compiled bundles/common.scss new_styles_high_contrast  in 3373 ms
compiled bundles/common.scss legacy_high_contrast  in 3374 ms
skipping: bundles/common.scss new_styles_normal_contrast a1f113321fa024e7a14cb09                                                                                        48597a2a4 0d68178b21 already exists. set BRANDABLE_CSS_FORCE_UPLOAD_EVEN_IF_EXIS                                                                                        TS to generate anyway
--> Finished: 'compile css (including custom brands)' in 5.373393106
working in 2 processes
--> Starting: 'css:styleguide'--> Starting: 'compile coffee, js 18n, and run r.j                                                                                        s optimizer'

--> Starting: 'js:generate'
--> creating styleguide
Building client app 'canvas_quizzes'
        Running 'npm install'...
npm WARN package.json canvas_quizzes@1.0.0 No repository field.
npm WARN package.json canvas_quizzes@1.0.0 No license field.
        Running 'npm run build'...
/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:218
      throw er
            ^
Error: EACCES, permission denied 'tmp/compiled'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:883:18)
    at rimrafSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:211:13)
    at /home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:244:26)
    at rmdirSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:237:7)
    at Function.rimrafSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/node_modules/rimraf/rimraf.js:219:5)
    at Object.rmrfSync (/home/ubuntu/canvas/client_apps/canvas_quizzes/node_modules/fs-extra/lib/remove.js:7:19)
    at Object.<anonymous> (/home/ubuntu/canvas/client_apps/canvas_quizzes/script/build:16:4)
            -------------------------------------------------------------------
            BUILD FAILURE:

            -------------------------------------------------------------------
# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 4.582735127
rake aborted!
Undumpable Exception -- #<RuntimeError: Build script failed for client app canvas_quizzes>
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
ubuntu@ip-172-31-21-165:~/canvas$ npm install

> canvas-lms@0.0.0 preinstall /home/ubuntu/canvas
> script/gem_npm install

ubuntu@ip-000-00-00-000:~/canvas$

```

What can is causing this error?

**Comment by candidosales** [comment]
I found the problem. Folders "public/javascripts" and clients_app/canvas_quizzes had permission only to root. 

The problem was not the "canvas/tmp" folder of the project root, but the tmp folder of "clients_app/ canvas_quizzes/tmp". I changed the permissions:

```
/canvas$ sudo chmod 777 -R client_apps/canvas_quizzes/
/canvas$ sudo chown -R canvasuser client_apps/canvas_quizzes/

/canvas$ sudo chmod 777 -R public/javascripts/
/canvas$ sudo chmod -R canvasuser public/javascripts/
```
Other error occurred at the end of compilation:
```
 bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
npm WARN prefer global react-tools@0.13.3 should be installed with -g
--> Finished: 'Making sure node_modules are up to date' in 4.825321199
--> Starting: 'compile css (including custom brands)'
brandable_css warning bundles/common.scss new_styles_normal_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_normal_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/common.scss new_styles_normal_contrast  in 2322 ms
brandable_css warning bundles/common.scss legacy_normal_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_normal_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_high_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss legacy_high_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_high_contrast contains a url() to: /images/inst_tree/node-drag.gif which doesn't exist on disk
brandable_css warning bundles/common.scss new_styles_high_contrast contains a url() to: /images/mediaelement/skipback.png which doesn't exist on disk
compiled bundles/common.scss legacy_normal_contrast  in 3336 ms
compiled bundles/common.scss legacy_high_contrast  in 3335 ms
compiled bundles/common.scss new_styles_high_contrast  in 3334 ms
skipping: bundles/common.scss new_styles_normal_contrast a1f113321fa024e7a14cb0948597a2a4 b09e2dacbb already exists. set BRANDABLE_CSS_FORCE_UPLOAD_EVEN_IF_EXISTS to generate anyway
--> Finished: 'compile css (including custom brands)' in 4.608376096
working in 2 processes
--> Starting: 'css:styleguide'
--> Starting: 'compile coffee, js 18n, and run r.js optimizer'
--> Starting: 'js:generate'
--> creating styleguide
Building client app 'canvas_quizzes'
        Running 'npm install'...
npm WARN package.json canvas_quizzes@1.0.0 No repository field.
npm WARN package.json canvas_quizzes@1.0.0 No license field.
        Running 'npm run build'...
# writing file: app/views/info/styleguide.html.erb
--> Finished: 'css:styleguide' in 4.671758168
--> Starting: 'Generate documentation [yardoc]'
Client app 'canvas_quizzes' was built successfully.
--> Creating ember app bundles
--> Pre-compiling ember handlebars templates
--> Creating ember app bundles finished in 0.009937872--> Pre-compiling handlebars templates
--> Compiling React JSX

--> Generating plugin extensions
--> Generating plugin extensions finished in 0.000877472
--> Compiling CoffeeScript with 'coffee' binaryr.rb....
--> Pre-compiling ember handlebars templates finished in 4.807625565
--> Pre-compiling handlebars templates finished in 9.739761954
[warn]: @param tag has unknown parameter name: conversations
    in file `app/controllers/quizzes/quiz_submission_users_controller.rb' near line 139
--> Compiling React JSX finished in 20.435743297
--> Compiling CoffeeScript finished in 52.176759834
--> Finished: 'js:generate' in 61.924634168
--> Starting: 'i18n:generate_js'
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 15.18 seconds

2083 files, 4669 strings, 0 failures
--> Finished: 'i18n:generate_js' in 19.86278135
--> Starting: 'js:build'
--> Concatenating JavaScript bundles with r.js
rake aborted!
Undumpable Exception -- #<RuntimeError: Error running js:build:
Error: Error: EPERM, operation not permitted '/home/ubuntu/canvas/public/optimized/bower/README'
    at Error (native)


ABORTING>/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/home/ubuntu/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)

```

**Comment by candidosales** [comment]
The previous error was also permission issue.

```
 sudo chmod 777 -R public/optimized/bower/ public/optimized/bower/README
 sudo chmod 777 -R public/optimized/
 sudo chmod 777 -R .yardoc/
 sudo chown -R canvasuser .yardoc/
```

**Comment by FreedomBen** [comment]
@candidosales thanks for the followup!
