### ISSUE TITLE
Random Notification Error

### ISSUE THREAD

**Issue by amulgarg** [instructure/canvas-lms#727]
Hi
I've been facing this issue on my dev server  at random. For example while enrolling a user to a course or while submitting a quiz. It gets resolved on restarting the server, but restarting the server takes me some time.
```
ActiveRecord::AssociationTypeMismatch (Notification(#161149380) expected, got Notification(#144122800)):
  /home/knolly/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/associations/belongs_to_association.rb:6:in `replace'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/associations/singular_association.rb:17:in `writer'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/associations/builder/association.rb:51:in `block in define_writers'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/attribute_assignment.rb:85:in `block in assign_attributes'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/attribute_assignment.rb:78:in `each'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/base.rb:498:in `initialize'
  /home/knolly/canvas/app/models/delayed_notification.rb:50:in `new'
  /home/knolly/canvas/app/models/delayed_notification.rb:50:in `process'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.11/lib/delayed/message_sending.rb:73:in `send_later_if_production_enqueue_args'
  /home/knolly/canvas/app/models/notifier.rb:6:in `send_notification'
  /home/knolly/canvas/gems/broadcast_policy/lib/broadcast_policy/notification_policy.rb:87:in `broadcast'
  /home/knolly/canvas/gems/broadcast_policy/lib/broadcast_policy/policy_list.rb:33:in `block in broadcast'
  /home/knolly/canvas/gems/broadcast_policy/lib/broadcast_policy/policy_list.rb:33:in `each'
  /home/knolly/canvas/gems/broadcast_policy/lib/broadcast_policy/policy_list.rb:33:in `broadcast'
  /home/knolly/canvas/gems/broadcast_policy/lib/broadcast_policy/instance_methods.rb:63:in `broadcast_notifications'
  (eval):120:in `run_callbacks'
  /home/knolly/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
  /home/knolly/canvas/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `run_callbacks'
  /home/knolly/canvas/config/initializers/active_record.rb:1554:in `block in run_callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `block in scoping'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/scoping.rb:98:in `with_scope'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `scoping'
  /home/knolly/canvas/config/initializers/active_record.rb:1554:in `run_callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `create_or_update'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/persistence.rb:84:in `save'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/validations.rb:50:in `save'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:22:in `save'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:42:in `block in transaction'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.28/lib/switchman/active_record/relation.rb:91:in `activate'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:37:in `transaction'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:259:in `block in save'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:258:in `save'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:85:in `block in save'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `block in scoping'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/scoping.rb:98:in `with_scope'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/relation.rb:241:in `scoping'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/switchman-1.2.28/lib/switchman/active_record/base.rb:85:in `save'
  /home/knolly/canvas/app/models/quizzes/submission_grader.rb:39:in `block in grade_submission'
  /home/knolly/canvas/gems/plugins/simply_versioned/lib/simply_versioned.rb:144:in `with_versioning'
  /home/knolly/canvas/app/models/quizzes/submission_grader.rb:38:in `grade_submission'
  /home/knolly/canvas/app/controllers/quizzes/quiz_submissions_controller.rb:70:in `create'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:614:in `block (2 levels) in _run__4212908564492232603__process_action__601507851393038582__callbacks'
  /home/knolly/canvas/app/controllers/application_controller.rb:1798:in `call'
  /home/knolly/canvas/app/controllers/application_controller.rb:1798:in `block (2 levels) in batch_jobs_in_actions'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.11/lib/delayed/batch.rb:27:in `block in serial_batch'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.11/lib/delayed/batch.rb:37:in `prepare_batches'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/canvas-jobs-0.9.11/lib/delayed/batch.rb:27:in `serial_batch'
  /home/knolly/canvas/app/controllers/application_controller.rb:1797:in `block in batch_jobs_in_actions'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_16508'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:613:in `block in _run__4212908564492232603__process_action__601507851393038582__callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_16507'
  /home/knolly/canvas/app/controllers/application_controller.rb:258:in `set_locale'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_16507'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:436:in `_run__4212908564492232603__process_action__601507851393038582__callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiling_methods.rb:79:in `block in profile_method'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  /home/knolly/canvas/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  /home/knolly/canvas/lib/canvas/request_throttle.rb:58:in `block in call'
  /home/knolly/canvas/lib/canvas/request_throttle.rb:238:in `reserve_capacity'
  /home/knolly/canvas/lib/canvas/request_throttle.rb:54:in `call'
  /home/knolly/canvas/app/middleware/stats_timing.rb:8:in `block in call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  /home/knolly/canvas/app/middleware/stats_timing.rb:8:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/encrypted_cookie_store-instructure-1.1.10/lib/encrypted_cookie_store.rb:47:in `call'
  /home/knolly/canvas/app/middleware/sessions_timeout.rb:22:in `call'
  /home/knolly/canvas/app/middleware/load_account.rb:12:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__3300216772217482946__call__2610225169326210192__callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:65:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:18:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
  /home/knolly/canvas/app/middleware/request_context_generator.rb:34:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  /home/knolly/canvas/app/middleware/prevent_non_multipart_parse.rb:32:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-mini-profiler-0.9.1/lib/mini_profiler/profiler.rb:193:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/log_tailer.rb:17:in `call'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/handler/thin.rb:13:in `run'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:268:in `start'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
  /home/knolly/canvas/vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
  script/rails:11:in `require'
  script/rails:11:in `<main>'


Created ErrorReport ID 10000000001868
DEPRECATION WARNING: Passing a template handler in the template name is deprecated. You can simply remove the handler name or pass render :handlers => [:erb] instead. (called from realtime at /usr/lib/ruby/1.9.1/benchmark.rb:295)
  Rendered shared/errors/_error_form.html.erb (3.9ms)
```
How to solve this?

Amul

**Comment by FreedomBen** [comment]
Hi @amulgarg.  This can happen when your server is not in production mode `RAILS_ENV=production` .  Can you check that?

**Comment by FreedomBen** [comment]
Hi @amulgarg .  This is related to having `config.cache_classes = false` set for the development environment.  This means that the classes are reloaded each time a request comes in.  This is nice since you don't have to restart the server every time you change a file, but it is prone to bugs like the one you are seeing, where a class is essentially getting defined twice.

You are correct, restarting the server fixes the problem.  It is painful, but without dedicating time to dive in and troubleshoot further, it's what we have at the moment.

**Comment by amulgarg** [comment]
Thank you for your response, @FreedomBen. "Where a class is essentially getting defined twice" seems like an interesting problem to solve.  Now, I understand the problem better!
