### ISSUE TITLE
Importing a .imscc course cartridge to Canvas

### ISSUE THREAD

**Issue by AndranikMarkosyan** [instructure/canvas-lms#741]
When I try to import a .imscc course  from another canvas installation I get the following error:
please help!
``` 
unknown mime type unknown/unknown

        /var/canvas/gems/canvas_unzip/lib/canvas_unzip.rb:130:in `each_entry'
/var/canvas/gems/canvas_unzip/lib/canvas_unzip.rb:71:in `extract_archive'
/var/canvas/lib/canvas/migration/archive.rb:79:in `unzip_archive'
/var/canvas/lib/canvas/migration/migrator.rb:53:in `unzip_archive'
/var/canvas/lib/cc/importer/canvas/converter.rb:43:in `export'
/var/canvas/lib/cc/importer/cc_worker.rb:49:in `perform'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/backend/base.rb:232:in `block in invoke_job'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:63:in `call'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:63:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:68:in `call'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:68:in `execute'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:41:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/backend/base.rb:229:in `invoke_job'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:142:in `block (2 levels) in perform'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:136:in `block in perform'
/var/canvas/config/initializers/delayed_job.rb:75:in `call'
/var/canvas/config/initializers/delayed_job.rb:75:in `block (2 levels) in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas_statsd-1.0.3/lib/canvas_statsd/statsd.rb:75:in `time'
/var/canvas/config/initializers/delayed_job.rb:74:in `block in <top (required)>'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:81:in `call'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:81:in `block (2 levels) in add'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:63:in `call'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:63:in `block in initialize'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:81:in `call'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:81:in `block in add'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:68:in `call'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:68:in `execute'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/lifecycle.rb:41:in `run_callbacks'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:133:in `perform'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:108:in `block in run'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:202:in `configure_for_job'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:107:in `run'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:84:in `block in start'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:83:in `loop'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/worker.rb:83:in `start'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:161:in `block in spawn_worker'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:172:in `block in fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:169:in `fork'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:169:in `fork_with_reconnects'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:160:in `spawn_worker'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:148:in `block (2 levels) in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:148:in `times'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:148:in `block in spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:146:in `each'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:146:in `spawn_all_workers'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:108:in `start'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.0/lib/delayed/pool.rb:34:in `run'
/var/canvas/script/delayed_job:10:in `<main>'   
```

**Comment by claydiffrient** [comment]
@AndranikMarkosyan I'm sorry you're having some trouble with this.

This may actually be a more appropriate thing for our [mailing list](https://groups.google.com/forum/#!forum/canvas-lms-users).  With the information given, it's kind of tough to begin to figure it out.  Please see our [CONTRIBUTING.md](https://github.com/instructure/canvas-lms/blob/stable/CONTRIBUTING.md) for our preferred issue format.

That being said my initial guess looking at the stack trace is possible file corruption with whichever file is showing the unknown/unknown mime type.

**Comment by simonista** [comment]
see also https://github.com/instructure/canvas-lms/issues/572 and https://groups.google.com/forum/#!searchin/canvas-lms-users/unknown$20mime$20type/canvas-lms-users/uwV85SNVgdc/8OMnXlLLa2EJ
