### ISSUE TITLE
Problem compiling assets on stable 

### ISSUE THREAD

**Issue by themusicman** [instructure/canvas-lms#744]
When I run `RAILS_ENV=production bundle exec rake canvas:compile_assets` I get the following errors:

```
--> Starting: 'i18n:generate_js'
ELOOP, too many symbolic links encountered 'client_apps/canvas_quizzes/apps/events.js'
Error extracting JS translations; confirm that `./gems/canvas_i18nliner/bin/i18nliner generate_js` works
rake aborted!
Parallel::DeadWorker: Parallel::DeadWorker
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:61:in `rescue in work'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:58:in `work'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
EOFError: end of file reached
/var/canvas/canvas/gems/canvas_ext/lib/canvas_ext/marshal.rb:8:in `load'
/var/canvas/canvas/gems/canvas_ext/lib/canvas_ext/marshal.rb:8:in `load'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:59:in `work'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/var/canvas/canvas/vendor/bundle/ruby/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

If I run `./gems/canvas_i18nliner/bin/i18nliner generate_js` by it self I get the same:

```
ELOOP, too many symbolic links encountered 'client_apps/canvas_quizzes/apps/events.js'
```

Any ideas?

**Comment by claydiffrient** [comment]
@themusicman It looks like somehow a wonky symlink is throwing things off.  I'm not sure where it would be at, but deleting it should fix the problem for you.  It may take a little digging to find it, but getting rid of it  should fix the issue.

You shouldn't see the issue with a clean checkout of the repository though.

**Comment by themusicman** [comment]
Thanks.  I blew away the client_apps dir and restored it and everything compiles now. 

`rm -Rf client_apps` and `git reset HEAD --hard` did the trick.
