### ISSUE TITLE
[Bug] Web application could not be started when using NewRelic

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#752]
Hello, 

I have a strange new bug when using newrelic:

```ruby
super: no superclass method `log' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00000006cbe048> (NoMethodError)
  /usr/local/rvm/gems/ruby-2.1.5/gems/switchman-1.3.11/lib/switchman/active_record/abstract_adapter.rb:20:in `log'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:885:in `schema_search_path='
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:1239:in `configure_connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:1229:in `connect'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:324:in `initialize'
  /my_app_path/config/application.rb:141:in `initialize'
  /my_app_path/config/application.rb:164:in `new'
  /my_app_path/config/application.rb:164:in `postgresql_connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/switchman-1.3.11/lib/switchman/active_record/connection_pool.rb:28:in `checkout_new_connection_with_sharding'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
  /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/switchman-1.3.11/lib/switchman/active_record/connection_pool.rb:34:in `connection_with_sharding'
  /usr/local/rvm/gems/ruby-2.1.5/gems/switchman-1.3.11/lib/switchman/connection_pool_proxy.rb:51:in `connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/model_schema.rb:310:in `clear_cache!'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/railtie.rb:103:in `block (2 levels) in <class:Railtie>'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:429:in `_run__394292670429295608__prepare__1264913830997133210__callbacks'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
  /usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-3.2.22/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
  /usr/local/rvm/gems/ruby-2.1.5/gems/actionpack-3.2.22/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `each'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/application.rb:136:in `initialize!'
  /usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /my_app_path/config/environment.rb:11:in `<top (required)>'
  /my_app_path/config.ru:3:in `require'
  /my_app_path/config.ru:3:in `block in <main>'
  /usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
  /usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
  /my_app_path/config.ru:1:in `new'
  /my_app_path/config.ru:1:in `<main>'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.20/src/helper-scripts/rack-preloader.rb:107:in `eval'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.20/src/helper-scripts/rack-preloader.rb:107:in `preload_app'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.20/src/helper-scripts/rack-preloader.rb:153:in `<module:App>'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.20/src/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.20/src/helper-scripts/rack-preloader.rb:28:in `<main>'
```

It happens when I add the newrelic_rpm gem in a Gemfile and launch the app in production: 

```ruby
group :production do
  gem 'newrelic_rpm'
end
```

NewRelic was working fine before recent updates (at least until November 2015). 
Do you have any idea how to debug that issue?

I tried to but did not find anything to solve my problem. 
Thanks!
Regis.

**Comment by ccutrer** [comment]
The problem is a bad interaction between New Relic and Switchman (a gem Canvas uses for connecting to multiple databases) both augmenting `ActiveRecord::ConnectionAdapters::AbstractAdapter#log`, but in different ways. Switchman uses `prepend` and `super` (requires Ruby 2), while New Relic uses `include` and renaming the method to maintain access to the original (compatible with older versions of Ruby, but less clean). I'm unable to reproduce your exact error, but it's unlikely these will work together until New Relic updates their code to use prepend.

**Comment by ccutrer** [comment]
For a good writeup, you can read http://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/ and http://yehudakatz.com/2009/03/06/alias_method_chain-in-models/

**Comment by Kulgar** [comment]
Thanks @ccutrer ! 
By visiting newrelic_rpm gem I saw that there is already a pull request in progress to do exactly that. But maintainer of the gem say they won't accept it because they still need support for old ruby versions. 

Fortunately the PR author will continue his work as he can not run NewRelic as well in his project. So, I will use his fork I think :)

**Comment by Kulgar** [comment]
Hello :)

I am reopening this issue as a new bug appeared and I have some news.

I also wrote to NewRelic support team and they found a quick fix for me, which was: 

```ruby
# In your gemfile:
gem 'newrelic_rpm', require: false

# In application.rb:
Bundler.require(*Rails.groups)
# manually require newrelic_rpm after all gems have been loaded
require 'newrelic_rpm' if Rails.env.production?
```

Which worked for a while. But then I upgraded to version release/2016-04-02.13. I found that switchman upgraded to 1.5.2. Because of that new relic is now causing a stack level too deep error, even with the above fix. 

As a new quickfix we can stick to switchman 1.3... but I am sure it may break some things elsewhere. 

So... I reopened my ticket with NewRelic and I will work with them again to find a better fix. As soon as I have one, I will update this issue to let you know. :)

Regards, 
Regis.

**Comment by Kulgar** [comment]
Finally newrelic team gave me 2 solutions that actually work. 

**First one:** downgrade the gem newrelic_rpm to 3.12.0.288, `gem 'newrelic_rpm', '3.12.0.288'`

Explanation:

> Changes to our ActiveRecord instrumentation that exacerbate this issue were introduced in version 3.12.1.298 of the Ruby agent. So, if you were to downgrade to agent version 3.12.0, we suspect you'd be able to use the agent successfully without the need to disable our ActiveRecord instrumentation.

**Second one (if you can't do first one):** disable their ActiveRecord instrumentation. 

> This can be done by setting the NEW_RELIC_DISABLE_ACTIVERECORD_INSTRUMENTATION environment variable to true (or via the disable_activerecord_instrumentation setting in your newrelic.yml as described [here](https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration)).

But...

> Yes, disabling ActiveRecord instrumentation will prevent you from seeing ActiveRecord data for those transactions. Unfortunately, this option isn't ideal.

I hope it will come handy to others :)
