### ISSUE TITLE
Error when running db:initial_setup as part of a clean install

### ISSUE THREAD

**Issue by bermudezjd** [instructure/canvas-lms#773]
Hello!

I've brought this up on the IRC channel as well, but posting here for wider verification and help.

Here are some particulars of the environment:

OS: Ubuntu 14.04
Ruby: 2.1.8p440
DB: Postgres 9.4.1 (RDS)
Canvas versions tested: latest stable as of 2/17/16, release/2016-01-30.14
Database.yml: removed the "queue" section, so dealing with a single database

Here's what I get when running `db:initial_setup`.  The failure is in the `PopulateSubmissionVersions` migration, which I believe is the first to include the `n_strand` option.  Can someone verify this behavior and help me!

Thanks!
```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown attribute: max_concurrent/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/at
tribute_assignment.rb:47:in `rescue in _assign_attribute'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_assignment.rb:42:in `_ass
ign_attribute'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/att
ribute_assignment.rb:67:in `block in assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/att
ribute_assignment.rb:61:in `each'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/att
ribute_assignment.rb:61:in `assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/cor
e.rb:8:in `init_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/core.rb:185:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:34:in `block in init
ialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in
 instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:
in `instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrume
nt'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:33:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/per
sistence.rb:45:in `create'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/backend/base.rb:76:in `enqueue'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:35:in `send_later_enque
ue_args'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:75:in `send_later_if_pr
oduction_enqueue_args'
/opt/canvas/db/migrate/20131003221953_populate_submission_versions.rb:5:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:538:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:578:in `exec_migration
'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:559:in `block (2 level
s) in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:558:in `block in migra
te'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connec
tion_pool.rb:294:in `with_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/connection_pool_proxy.rb:13:in `with
_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:557:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:391:in `migrate'
```

**Comment by ccutrer** [comment]
You seem to be missing some lines at the bottom of your stack trace. What I'm looking for is that db:initialize_setup should have run predeploy migrations first (see https://github.com/instructure/canvas-lms/blob/stable/lib/tasks/db_load_data.rake#L237), which would add the max_concurrent column, and is now running regular migrations. you should try `rake db:migrate:up VERSION=20150807133223` to force that migration to run. if it doesn't do anything, it means it has already been marked as run, but obviously has not correctly. you can `DELETE FROM schema_migrations WHERE version='20150807133223'` to mark it as not-run, and then try again.

**Comment by bermudezjd** [comment]
I apologize for cutting the stack trace off short.  Here is the full stack trace and a file that lists all of the  migrations that ran up until the `PopulateSubmissionVersions` migration.  I checked the database after the failure and I see the max_concurrent column, so I believe that the predeploy migrations ran first.  Furthermore, there is a migration that adds the max_concurrent column in the set of migrations that ran successfully before the failed migration.  I think something else is at play here.
[migration failure.txt](https://github.com/instructure/canvas-lms/files/138167/migration.failure.txt)


```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

unknown attribute: max_concurrent/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_assignment.rb:47:in `rescue in _assign_attribute'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:67:in `block in assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `each'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/core.rb:185:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:34:in `block in initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:33:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/persistence.rb:45:in `create'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/backend/base.rb:76:in `enqueue'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:35:in `send_later_enqueue_args'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:75:in `send_later_if_production_enqueue_args'
/opt/canvas/db/migrate/20131003221953_populate_submission_versions.rb:5:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:538:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:578:in `exec_migration'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:559:in `block (2 levels) in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:558:in `block in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:557:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:391:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:713:in `migrate'
/opt/canvas/config/initializers/active_record.rb:1226:in `block (2 levels) in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:1009:in `block in ddl_transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/base.rb:50:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:1009:in `ddl_transaction'
/opt/canvas/config/initializers/active_record.rb:1224:in `block in migrate'
/opt/canvas/config/initializers/active_record.rb:1200:in `each'
/opt/canvas/config/initializers/active_record.rb:1200:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:768:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:746:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:42:in `block (2 levels) in <top (required)>'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `call'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `each'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `block (4 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/database_server.rb:93:in `unshackle'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:58:in `block (3 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:149:in `with_each_shard'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:53:in `block (2 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/shackles.rb:22:in `activate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:52:in `block in shardify_task'
/opt/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
ActiveRecord::UnknownAttributeError: unknown attribute: max_concurrent
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_assignment.rb:47:in `rescue in _assign_attribute'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:67:in `block in assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `each'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/core.rb:185:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:34:in `block in initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:33:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/persistence.rb:45:in `create'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/backend/base.rb:76:in `enqueue'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:35:in `send_later_enqueue_args'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:75:in `send_later_if_production_enqueue_args'
/opt/canvas/db/migrate/20131003221953_populate_submission_versions.rb:5:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:538:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:578:in `exec_migration'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:559:in `block (2 levels) in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:558:in `block in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:557:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:391:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:713:in `migrate'
/opt/canvas/config/initializers/active_record.rb:1226:in `block (2 levels) in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:1009:in `block in ddl_transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/base.rb:50:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:1009:in `ddl_transaction'
/opt/canvas/config/initializers/active_record.rb:1224:in `block in migrate'
/opt/canvas/config/initializers/active_record.rb:1200:in `each'
/opt/canvas/config/initializers/active_record.rb:1200:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:768:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:746:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:42:in `block (2 levels) in <top (required)>'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `call'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `each'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `block (4 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/database_server.rb:93:in `unshackle'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:58:in `block (3 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:149:in `with_each_shard'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:53:in `block (2 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/shackles.rb:22:in `activate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:52:in `block in shardify_task'
/opt/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `max_concurrent=' for #<Delayed::Backend::ActiveRecord::Job:0x00000007cbaaf0>
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activemodel-4.0.13/lib/active_model/attribute_methods.rb:439:in `method_missing'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_methods.rb:168:in `method_missing'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_assignment.rb:42:in `public_send'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:67:in `block in assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `each'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:61:in `assign_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/core.rb:185:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:34:in `block in initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/aroi-0.0.3/lib/aroi/instrumentation/active_record.rb:33:in `initialize'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/inheritance.rb:30:in `new'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/persistence.rb:45:in `create'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/backend/base.rb:76:in `enqueue'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:35:in `send_later_enqueue_args'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/canvas-jobs-0.10.3/lib/delayed/message_sending.rb:75:in `send_later_if_production_enqueue_args'
/opt/canvas/db/migrate/20131003221953_populate_submission_versions.rb:5:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:538:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:578:in `exec_migration'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:559:in `block (2 levels) in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:558:in `block in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/connection_pool_proxy.rb:13:in `with_connection'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:557:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:391:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:713:in `migrate'
/opt/canvas/config/initializers/active_record.rb:1226:in `block (2 levels) in migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:1009:in `block in ddl_transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/active_record/base.rb:50:in `transaction'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:1009:in `ddl_transaction'
/opt/canvas/config/initializers/active_record.rb:1224:in `block in migrate'
/opt/canvas/config/initializers/active_record.rb:1200:in `each'
/opt/canvas/config/initializers/active_record.rb:1200:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:768:in `up'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/migration.rb:746:in `migrate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/databases.rake:42:in `block (2 levels) in <top (required)>'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `call'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `each'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:59:in `block (4 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/database_server.rb:93:in `unshackle'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:58:in `block (3 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/app/models/switchman/shard.rb:149:in `with_each_shard'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:53:in `block (2 levels) in shardify_task'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/switchman/shackles.rb:22:in `activate'
/opt/canvas/vendor/bundle/ruby/2.1.0/gems/switchman-1.3.14.pre.1/lib/tasks/switchman.rake:52:in `block in shardify_task'
/opt/canvas/lib/tasks/db_load_data.rake:239:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

In the middle of all of those migrations that ran successfully, I see one that adds the max_concurrent column.  Seems like some other issue is at play here.

**Comment by grahamb** [comment]
I'm getting the same thing when spinning up a new install via vagrant. Stack trace and migrations list here: https://gist.github.com/grahamb/9664b146b3a5bf403102

**Comment by ccutrer** [comment]
4adaa67ed2ba0d5c0cf87523f68072d28f848b53 may be the solution to this; I'll pick it over to the stable branch

**Comment by ccutrer** [comment]
Never mind; the bug that commit fixed wasn't even introduced on the stable branch.
