### ISSUE TITLE
Compile Assets error

### ISSUE THREAD

**Issue by Andrewc65** [instructure/canvas-lms#784]
Getting an error when installing Canvas via the CODES.sh install script:

```
--> Compressing JavaScript with UglifyJS
rake aborted!
Undumpable Exception -- #<RuntimeError: Error running js:build:

> canvas-lms@0.0.0 compress /home/ubuntu/canvas-lms
> node script/compress.js

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
an error occured: compute process (1236) dies with code: null
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at ComputeCluster.emit (events.js:87:13)
    at ChildProcess.<anonymous> (/home/ubuntu/canvas-lms/node_modules/compute-cluster/lib/compute-cluster.js:58:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1078:12)

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compress"
npm ERR! node v0.12.12
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! canvas-lms@0.0.0 compress: `node script/compress.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas-lms@0.0.0 compress script 'node script/compress.js'.
npm ERR! This is most likely a problem with the canvas-lms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node script/compress.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas-lms
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/canvas-lms/npm-debug.log

ABORTING>/var/lib/gems/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/var/lib/gems/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/var/lib/gems/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/var/lib/gems/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/var/lib/gems/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/var/lib/gems/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/var/lib/gems/2.1.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

**Comment by FreedomBen** [comment]
Out of memory eh?  How much RAM do you have?  Do you have a swap file activated?

**Comment by Andrewc65** [comment]
I tried that. Let me try tomorrow afternoon to see if there are any problems.

**Comment by simonista** [comment]
I'm going to close this out, if you're still having issues, can you open an issue over at https://github.com/FreedomBen/canvas-development-tools please?  Good luck!
