### ISSUE TITLE
compile assest error

### ISSUE THREAD

**Issue by eemirtekin** [instructure/canvas-lms#810]
Hello All,
I'm trying to install canvas-lms on ubuntu 12.04, but I'm getting error below
root@canvas-lms:/var/canvas# **bundle exec rake canvas:compile_assets**
Help me!

Thanks in advance!
```
DEPRECATION WARNING: Syck is deprecated and support for serialization has been removed. ActiveRecord::Core#yaml_initialize will be removed in 4.1 which will break deserialization support with Syck. (called from require at /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77)
--> Starting: 'Making sure node_modules are up to date'
npm WARN cannot run in wd canvas-lms@0.0.0 script/gem_npm install (wd=/var/canvas)
npm WARN optional dep failed, continuing fsevents@1.0.11
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.13"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/canvas/node_modules/brandable_css/node_modules/node-zopfli/.node-gyp"
make: *** No rule to make target `../.node-gyp/0.12.13/include/node/common.gypi', needed by `Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Linux 3.13.0-83-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/canvas/node_modules/brandable_css/node_modules/node-zopfli/lib/binding/node-v14-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/var/canvas/node_modules/brandable_css/node_modules/node-zopfli/lib/binding/node-v14-linux-x64"
gyp ERR! cwd /var/canvas/node_modules/brandable_css/node_modules/node-zopfli
gyp ERR! node -v v0.12.13
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/canvas/node_modules/brandable_css/node_modules/node-zopfli/lib/binding/node-v14-linux-x64/zopfli.node --module_name=zopfli --module_path=/var/canvas/node_modules/brandable_css/node_modules/node-zopfli/lib/binding/node-v14-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/canvas/node_modules/brandable_css/node_modules/node-zopfli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1019:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
node-pre-gyp ERR! System Linux 3.13.0-83-generic
node-pre-gyp ERR! command "node" "/var/canvas/node_modules/brandable_css/node_modules/node-zopfli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/canvas/node_modules/brandable_css/node_modules/node-zopfli
node-pre-gyp ERR! node -v v0.12.13
node-pre-gyp ERR! node-pre-gyp -v v0.6.26
node-pre-gyp ERR! not ok
npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-zopfli@1.4.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the node-zopfli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-zopfli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-zopfli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/canvas/npm-debug.log
--> Finished: 'Making sure node_modules are up to date' in 33.280089069
--> Starting: 'compile css (including custom brands)'
rake aborted!
Errno::ENOENT: No such file or directory - ./node_modules/.bin/brandable_css
/var/canvas/lib/brandable_css.rb:173:in `run_cli!'
/var/canvas/lib/brandable_css.rb:153:in `compile_all!'
/var/canvas/lib/tasks/canvas.rake:123:in `block (3 levels) in <top (required)>'
/var/canvas/lib/tasks/canvas.rake:7:in `log_time'
/var/canvas/lib/tasks/canvas.rake:123:in `block (2 levels) in <top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

**Comment by amulgarg** [comment]
Hi @eemirtekin 

Did you install **node_modules** as root?

**Comment by eemirtekin** [comment]
Hi @amulgarg 
Yes i install node_modules as root.
Thanks for your answer.

**Comment by amulgarg** [comment]
EACESS issues usually come when you install using sudo. Remove **node_modules** from your canvas directory. Also delete **node_modules** from **gems/canvas_i18inliner** directory. 

Reinstall node_modules without using sudo. And run the compile assets task without using sudo.
