### ISSUE TITLE
bundle install : can install thrift

### ISSUE THREAD

**Issue by gabrieltong** [instructure/canvas-lms#827]
ruby version 2.1.5 , gem version 1.10.6

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/shangliang/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20160520-20541-1undjkx.rb extconf.rb
checking for strlcpy() in string.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binary_protocol_accelerated.c
compiling compact_protocol.c
compiling memory_buffer.c
compiling protocol.c
compiling strlcpy.c
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: expected parameter declarator
extern size_t strlcpy(char *, const char *, size_t);
              ^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: expected ')'
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2
                               ^
./strlcpy.h:28:15: note: to match this '('
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:53: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                    ^
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
extern size_t strlcpy(char *, const char *, size_t);
              ^
/usr/include/secure/_string.h:105:44: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
                                           ^
/usr/include/secure/_common.h:39:31: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                              ^
In file included from strlcpy.c:20:
./strlcpy.h:28:15: error: conflicting types for '__builtin___strlcpy_chk'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
./strlcpy.h:28:15: note: '__builtin___strlcpy_chk' is a builtin with type 'unsigned long (char *, const char *, unsigned long, unsigned long)'
/usr/include/secure/_string.h:105:3: note: expanded from macro 'strlcpy'
  __builtin___strlcpy_chk (dest, src, len, __darwin_obsz (dest))
  ^
4 errors generated.
make: *** [strlcpy.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/shangliang/.rvm/gems/ruby-2.1.5/gems/thrift-0.8.0 for inspection.
Results logged to /Users/shangliang/.rvm/gems/ruby-2.1.5/extensions/x86_64-darwin-15/2.1.0/thrift-0.8.0/gem_make.out
An error occurred while installing thrift (0.8.0), and Bundler cannot continue.
Make sure that `gem install thrift -v '0.8.0'` succeeds before bundling.
```

**Comment by bootstraponline** [comment]
Try:
`gem install thrift -v '0.8.0' -- --with-cppflags='-D_FORTIFY_SOURCE=0'`

**Comment by hudakdidit** [comment]
If on Mac El Capitan try:

`gem install thrift -- --with-cppflags=\"-D_FORTIFY_SOURCE=0 -Wno-shift-negative-value\"`

http://stackoverflow.com/questions/36378190/cant-install-thrift-gem-on-os-x-el-capitan#answer-36523125

**Comment by ajhenley** [comment]
problem is, this allows you to install the gem, but the bundle install still fails

**Comment by defaria** [comment]
I am having the same issue. I have managed to install thrift as suggested by @hudakdidit (installed the same version as required by canvas) , however, canvas still tries to install thrift and fails.

**Comment by defaria** [comment]
I fixed by update CODES.sh (line 997) to `bundle config build.thrift "--with-cppflags=\"-D_FORTIFY_SOURCE=0 -Wno-shift-negative-value\""`

I am on El Captain.

**Comment by abhishekaj** [comment]
Faced the same issue even after installing thrift as suggested by @hudakdidit. But got fixed by @defaria method.

**Comment by dcodeakshay** [comment]
Can you tell me how to fix this issue ? I'm using ubuntu server. 

getting error 

Could not find thrift-0.9.3.0 in any of the sources
Run `bundle install` to install missing gems.

in fact i have already installed the thrift 0.9.3.0

**Comment by eduar-apaza-exa** [comment]
hey guys I am facing the same issue, I am on Big Sour ? is there another option to fix this issue ? 

thanks

**Comment by dmgonzales** [comment]
on ubuntu:18.04.6 this worked for me
 bundle config build.thrift -v 0.9.3.0  --with-cppflags='-D_FORTIFY_SOURCE=2'
 then re-issue the bundle command
 bundle _2.2.19_ install --path vendor/bundle

**Comment by BatesJernigan** [comment]
I just had the same issue on macOS Monterey and @bablooashok fix worked. Thank you for posting!

**Comment by shrihari007** [comment]
Thanks... @bablooashok .. Fixed issue on macOS Monterey

**Comment by aikoanji** [comment]
@bablooashok can u help me ?
macOS: monterey M1
gem install thrift -v 0.16.0 -- --with-cppflags="-Wno-compound-token-split-by-macro"
Building native extensions with: '--with-cppflags=-Wno-compound-token-split-by-macro'
This could take a while...
ERROR:  Error installing thrift:
        ERROR: Failed to build gem native extension.

**Comment by harshit98** [comment]
I am getting issues while running this command suggested by @bablooashok to install thrift v0.16.0 :

```shell
gem install thrift -v 0.16.0 -- --with-cppflags="-Wno-compound-token-split-by-macro"
```

Gives me following output:

```
Building native extensions with: '--with-cppflags=-Wno-compound-token-split-by-macro'
This could take a while...
ERROR:  Error installing thrift:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.2.0/gems/thrift-0.16.0/ext
/usr/local/opt/ruby/bin/ruby extconf.rb --with-cppflags\=-Wno-compound-token-split-by-macro
checking for strlcpy() in string.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/Cellar/ruby/3.2.2_1/bin/$(RUBY_BASE_NAME)
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:583:in `try_link0'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:601:in `try_link'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:812:in `try_func'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:1116:in `block in have_func'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:989:in `block in checking_for'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:354:in `block (2 levels) in postpone'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:324:in `open'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:354:in `block in postpone'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:324:in `open'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:350:in `postpone'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:988:in `checking_for'
        from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/mkmf.rb:1115:in `have_func'
        from extconf.rb:31:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/3.2.0/extensions/x86_64-darwin-20/3.2.0/thrift-0.16.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/3.2.0/gems/thrift-0.16.0 for inspection.
Results logged to /usr/local/lib/ruby/gems/3.2.0/extensions/x86_64-darwin-20/3.2.0/thrift-0.16.0/gem_make.out
```

**Comment by ccutrer** [comment]
The solution is in your output:

> You have to install development tools first.

Also note that Canvas does not yet officially support Ruby 3.2

**Comment by harshit98** [comment]
@ccutrer - Does it mean the Xcode development tools? Those tools are already installed.

**Comment by ccutrer** [comment]
It means the Xcode command line tools, not Xcode itself.

**Comment by harshit98** [comment]
@ccutrer 

Hmm, I tried running this command:

```
> clang --version

Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
This is pretty much shows that XCode command line tools are already installed.
