### ISSUE TITLE
error compiling assets

### ISSUE THREAD

**Issue by kinsomicrote** [instructure/canvas-lms#830]
I am short of ideas on what to do, here is what I get when I try to compile assets on canvaslms

```
--> Starting: 'Making sure node_modules are up to date'
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp) 
../src/zopfli-binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodezopfli::CompressBinding::Sync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/zopfli-binding.cc:173:20: warning: ‘format’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     &out, &outsize);
                    ^
../src/zopfli-binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodezopfli::CompressBinding::Async(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/zopfli-binding.cc:105:78: warning: ‘format’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   : Nan::AsyncWorker(callback), format(format), zopfli_options(zopfli_options) {
                                                                              ^
../src/zopfli-binding.cc:150:16: note: ‘format’ was declared here
   ZopfliFormat format;
                ^
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN i18nliner-handlebars@0.1.1 requires a peer of i18nliner@~0.1.0 but none was installed.
npm WARN i18nliner-handlebars@0.1.1 requires a peer of jsdom@~0.8.10 but none was installed.
--> Finished: 'Making sure node_modules are up to date' in 191.20733762999953
--> Starting: 'compile css (including custom brands)'
/home/kinsomicrote/lab/canvas/canvas/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
    ^

Error: The `libsass` binding was not found in /home/kinsomicrote/lab/canvas/canvas/node_modules/node-sass/vendor/linux-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/home/kinsomicrote/lab/canvas/canvas/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/home/kinsomicrote/lab/canvas/canvas/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/kinsomicrote/lab/canvas/canvas/node_modules/brandable_css/lib/compileBundle.js:64:47)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/kinsomicrote/lab/canvas/canvas/node_modules/brandable_css/lib/main.js:617:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
rake aborted!
Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css
/home/kinsomicrote/lab/canvas/canvas/lib/brandable_css.rb:248:in `block in run_cli!'
/home/kinsomicrote/lab/canvas/canvas/lib/brandable_css.rb:234:in `run_cli!'
/home/kinsomicrote/lab/canvas/canvas/lib/brandable_css.rb:214:in `compile_all!'
/home/kinsomicrote/lab/canvas/canvas/lib/tasks/canvas.rake:123:in `block (3 levels) in <top (required)>'
/home/kinsomicrote/lab/canvas/canvas/lib/tasks/canvas.rake:7:in `log_time'
/home/kinsomicrote/lab/canvas/canvas/lib/tasks/canvas.rake:123:in `block (2 levels) in <top (required)>'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

Any clue on what could be the cause?

**Comment by claydiffrient** [comment]
@kinsomicrote looks like you are using too new of a version of Node.  You need to make sure you are using Node 0.12.5 but less than Node 4.0.  We're working on getting Canvas working with newer versions, but for now downgrading your Node version, then running this should fix it for you: `rm -rf node_modules && rm -rf gems/**/node_modules && npm cache clean && npm install`

**Comment by kinsomicrote** [comment]
@claydiffrient Thanks, that solved it. Check this error out.

```
npm ERR! Linux 4.6.0-040600-generic
npm ERR! argv "/usr/local/bin/nodejs/bin/node" "/usr/local/bin/nodejs/bin/npm" "install"
npm ERR! node v0.12.14
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.12 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.12 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/npm-debug.log
            -------------------------------------------------------------------
            INSTALL FAILURE:
            
> phantomjs@1.9.12 install /home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
Install exited unexpectedly

> node-sass@0.9.3 install /home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/node_modules/node-sass
> node build.js

make: Entering directory '/home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/binding.o
  CXX(target) Release/obj.target/binding/sass_context_wrapper.o
  CXX(target) Release/obj.target/binding/libsass/ast.o
  CXX(target) Release/obj.target/binding/libsass/base64vlq.o
  CXX(target) Release/obj.target/binding/libsass/bind.o
  CXX(target) Release/obj.target/binding/libsass/constants.o
  CXX(target) Release/obj.target/binding/libsass/context.o
  CXX(target) Release/obj.target/binding/libsass/contextualize.o
  CXX(target) Release/obj.target/binding/libsass/copy_c_str.o
  CXX(target) Release/obj.target/binding/libsass/error_handling.o
  CXX(target) Release/obj.target/binding/libsass/eval.o
  CXX(target) Release/obj.target/binding/libsass/expand.o
  CXX(target) Release/obj.target/binding/libsass/extend.o
  CXX(target) Release/obj.target/binding/libsass/file.o
  CXX(target) Release/obj.target/binding/libsass/functions.o
  CXX(target) Release/obj.target/binding/libsass/inspect.o
  CXX(target) Release/obj.target/binding/libsass/output_compressed.o
  CXX(target) Release/obj.target/binding/libsass/output_nested.o
  CXX(target) Release/obj.target/binding/libsass/parser.o
  CXX(target) Release/obj.target/binding/libsass/prelexer.o
  CXX(target) Release/obj.target/binding/libsass/sass.o
  CXX(target) Release/obj.target/binding/libsass/sass_interface.o
  CXX(target) Release/obj.target/binding/libsass/source_map.o
  CXX(target) Release/obj.target/binding/libsass/to_c.o
  CXX(target) Release/obj.target/binding/libsass/to_string.o
  CXX(target) Release/obj.target/binding/libsass/units.o
  CXX(target) Release/obj.target/binding/libsass/utf8_string.o
  CXX(target) Release/obj.target/binding/libsass/util.o
  CXX(target) Release/obj.target/binding/libsass/sass2scss/sass2scss.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/node_modules/node-sass/build'
Installed in `/home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/node_modules/node-sass/bin/linux-x64-v8-3.28/binding.node`

            -------------------------------------------------------------------
rake aborted!
Undumpable Exception -- #<RuntimeError: Package installation failure for client app canvas_quizzes>
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

**Comment by simonista** [comment]
We see this error from time to time as well, we think it's just a flakey connection with bitbucket.  I'd try again once or twice and see if you can get past it.  The key is these lines: 

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
Install exited unexpectedly
```
