### ISSUE TITLE
persistent assests compilation error

### ISSUE THREAD

**Issue by kinsomicrote** [instructure/canvas-lms#834]
This is the error I get when I try to compile assets on CanvasLMS.
I have no clue what the issue is.

```
Modules:         0 (    0 undocumented)
Classes:        98 (   30 undocumented)
Constants:       0 (    0 undocumented)
Methods:       433 (    8 undocumented)
 92.84% documented
API Documentation successfully generated in public/doc/api
See public/doc/api/index.html
--> Finished: 'Generate documentation [yardoc]' in 89.05911996899886
  [=======---------------------------------] 18% 0.0sError making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:561:26)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Linux 4.6.0-040600-generic
npm ERR! argv "/home/kinsomicrote/.nodenv/versions/0.12.14/bin/node" "/home/kinsomicrote/.nodenv/versions/0.12.14/bin/npm" "install"
npm ERR! node v0.12.14
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.12 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.12 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/npm-debug.log
            -------------------------------------------------------------------
            INSTALL FAILURE:

> phantomjs@1.9.12 install /home/kinsomicrote/lab/canvas/canvas/client_apps/canvas_quizzes/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...


            -------------------------------------------------------------------
rake aborted!
Undumpable Exception -- #<RuntimeError: Package installation failure for client app canvas_quizzes>
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:63:in `work'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:280:in `block (4 levels) in work_in_processes'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:447:in `with_instrumentation'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:279:in `block (3 levels) in work_in_processes'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `loop'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:273:in `block (2 levels) in work_in_processes'
/home/kinsomicrote/lab/canvas/canvas/vendor/bundle/ruby/2.3.0/gems/parallel-1.4.1/lib/parallel.rb:138:in `block (2 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
(See full trace by running task with --trace)
```

**Comment by illegalnumbers** [comment]
It seems like PhantomJS isn't installing correctly.

```npm ERR! phantomjs@1.9.12 install: `node install.js`
npm ERR! Exit status 1```

Could try uninstalling PhatomJS and then re-running a node install.

**Comment by illegalnumbers** [comment]
This also might help! https://github.com/Medium/phantomjs#troubleshooting

**Comment by dracorna** [comment]
Ran into the same issue. Turns out to be because of firewalls in my office. 
If you set
`npm set strict-ssl false`
then run the compile_assets task it should work.
Don't forget to set
`npm set strict-ssl true`
when you are done.
