### ISSUE TITLE
Delayed::Periodic Job failed to load: Unknown handler

### ISSUE THREAD

**Issue by geekx1** [instructure/canvas-lms#854]
### Summary: 
I find in my Canvas that Delayed::Periodic doesn't work. Then I checked for error_reports showing the job failed to load because of the unknown handler.Looks something like:

### Steps to reproduce:
```
Job failed to load: Unknown handler. Try to manually require the appropriate file.

        /var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/backend/base.rb:311:in `deserialize'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/backend/base.rb:201:in `payload_object'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/backend/base.rb:206:in `name'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:135:in `block in perform'
/var/www/rails_apps/ndmooc-lms/config/initializers/delayed_job.rb:71:in `call'
/var/www/rails_apps/ndmooc-lms/config/initializers/delayed_job.rb:71:in `block (2 levels) in <top (required)>'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas_statsd-1.0.3/lib/canvas_statsd/statsd.rb:75:in `time'
/var/www/rails_apps/ndmooc-lms/config/initializers/delayed_job.rb:70:in `block in <top (required)>'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:81:in `call'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:81:in `block (2 levels) in add'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:63:in `call'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:63:in `block in initialize'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:81:in `call'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:81:in `block in add'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:68:in `call'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:68:in `execute'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/lifecycle.rb:41:in `run_callbacks'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:134:in `perform'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:108:in `block in run'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:203:in `configure_for_job'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:107:in `run'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:84:in `block in start'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:83:in `loop'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/worker.rb:83:in `start'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:161:in `block in spawn_worker'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:172:in `block in fork_with_reconnects'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:169:in `fork'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:169:in `fork_with_reconnects'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:160:in `spawn_worker'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:215:in `block in join'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:202:in `loop'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:202:in `join'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:110:in `start'
/var/www/rails_apps/ndmooc-lms/vendor/bundle/ruby/2.2.0/gems/canvas-jobs-0.10.5/lib/delayed/pool.rb:34:in `run'
script/delayed_job:11:in `<main>'
```
      

### Additional notes:

**Comment by ccutrer** [comment]
Is this a repeating error, or only happened once? IIRC, we removed a periodic job, which due to how they are scheduled would cause this error to happen once or twice, and could be safely ignored.

**Comment by geekx1** [comment]
@ccutrer this is a repeating errror which occurs frequently,it influenced runtime in our platform.
