### ISSUE TITLE
Trouble running specs

### ISSUE THREAD

**Issue by Kulgar** [instructure/canvas-lms#892]
Hello 

### Summary:

I have some errors when I try to run specs. 
They are new as I did not have any issues previous week (my app was up to date). It started this morning when I did a new update with your last release. 

It happens with  **last master version and last stable version and Rails 4.0 and Rails 4.2** (I tried everything to fix it). 
Those errors don't show up if I run a specific file.

### Steps to reproduce:

 1. Just run 'rspec spec/apis' or 'rspec'

### Expected behavior:

Should run rspec, but it doesn't, it fires errors. 

### Additional notes:

Here are the errors I get with Rails 4.0.13 in instructure master branch: 

```ruby
An error occurred in an `after(:context)` hook.
  NoMethodError: undefined method `rollback' for #<ActiveRecord::ConnectionAdapters::ClosedTransaction:0x00000005cf8370>
  occurred at /home/regmillet/.rvm/gems/ruby-2.1.6/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:241:in `rollback_transaction'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/once-ler-0.0.16/lib/onceler/transactions/active_record_4.rb:8:in `rollback_transaction'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/once-ler-0.0.16/lib/onceler/recorder.rb:134:in `block in rollback_transactions!'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/once-ler-0.0.16/lib/onceler/recorder.rb:133:in `each'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/once-ler-0.0.16/lib/onceler/recorder.rb:133:in `rollback_transactions!'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/once-ler-0.0.16/lib/onceler/recorder.rb:77:in `reset!'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/once-ler-0.0.16/lib/onceler/basic_helpers.rb:124:in `block in add_onceler_hooks!'
/home/regmillet/Workspace/RailsProjects/saved-canvas-lms/spec/spec_helper.rb:105:in `instance_exec'
/home/regmillet/Workspace/RailsProjects/saved-canvas-lms/spec/spec_helper.rb:105:in `run'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:520:in `each'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:473:in `run'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:529:in `block in run_after_context_hooks'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:528:in `run_after_context_hooks'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:554:in `run'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `map'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
/home/regmillet/.rvm/gems/ruby-2.1.6/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
/home/regmillet/.rvm/gems/ruby-2.1.6/bin/rspec:23:in `load'
/home/regmillet/.rvm/gems/ruby-2.1.6/bin/rspec:23:in `<main>'
/home/regmillet/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
/home/regmillet/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
```

And in rspec report: 

```ruby
  X) Any spec ... :
       Failure/Error: Shard.default.destroy if Shard.default.is_a?(Shard)
       
       RuntimeError:
         Cannot destroy the default shard
       # /home/regmillet/.rvm/gems/ruby-2.1.6/gems/switchman-1.6.0/app/models/switchman/shard_internal.rb:667:in `destroy'
       # ./spec/sharding_spec_helper.rb:35:in `block (2 levels) in <top (required)>'
```

Any idea? :)

**Comment by Kulgar** [comment]
Some news: with specific files sometimes it  works, sometimes it doesn't.
It is definitely linked to last release as when I downgrade to the 27th of August release, it works fine.

**Comment by Kulgar** [comment]
Problem solved 👍
