### ISSUE TITLE
Pandarus fails to build against master

### ISSUE THREAD

**Issue by johnnaegle** [instructure/canvas-lms#900]
### Summary:

I've tried to track down as many issues as I can with re-building pandarus from the master or stable branch of canvas-lms, but it fails horribly.  Apparently, building pandarus is not part of the build process and the API documentation used to generate the API client is badly broken.
### Steps to reproduce:
1. Get latest code 

```
git clone git@github.com:instructure/canvas-lms.git
git clone git@github.com:instructure/pandarus.git
cd canvas-lms
bundle install
cd ../pandarus
```
1. Uncomment the important parts of `pandarus/build-all` that causes it to re-generate the whole API from canvas-lsm
2. ./build-all
3. It fails.  See #899, #898, #897, #896, #895 and many other issues that I could not work around

```
api version: 1.0
missing models: Set(,  QuizReport , GroupMembership | Progress, Grading Standard, Collaboration)
----------

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
    at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at scala.collection.immutable.StringOps.apply(StringOps.scala:39)
    at com.wordnik.swagger.codegen.BasicRubyGenerator.toDeclaration(BasicRubyGenerator.scala:78)
    at com.wordnik.swagger.codegen.Codegen$$anonfun$modelToMap$1.apply(Codegen.scala:492)
    at com.wordnik.swagger.codegen.Codegen$$anonfun$modelToMap$1.apply(Codegen.scala:441)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
    at scala.collection.mutable.LinkedHashMap.foreach(LinkedHashMap.scala:129)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
    at scala.collection.mutable.LinkedHashMap.map(LinkedHashMap.scala:48)
    at com.wordnik.swagger.codegen.Codegen.modelToMap(Codegen.scala:441)
    at com.wordnik.swagger.codegen.Codegen$$anonfun$generateSource$1.apply(Codegen.scala:57)
    at com.wordnik.swagger.codegen.Codegen$$anonfun$generateSource$1.apply(Codegen.scala:55)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at com.wordnik.swagger.codegen.Codegen.generateSource(Codegen.scala:55)
    at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$bundleToSource$1$$anonfun$apply$8.apply(BasicGenerator.scala:216)
    at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$bundleToSource$1$$anonfun$apply$8.apply(BasicGenerator.scala:215)
    at scala.collection.immutable.Map$Map1.foreach(Map.scala:118)
    at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$bundleToSource$1.apply(BasicGenerator.scala:215)
    at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$bundleToSource$1.apply(BasicGenerator.scala:214)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at com.wordnik.swagger.codegen.BasicGenerator.bundleToSource(BasicGenerator.scala:214)
    at com.wordnik.swagger.codegen.BasicGenerator.generateClientWithoutExit(BasicGenerator.scala:89)
    at com.wordnik.swagger.codegen.BasicGenerator.generateClient(BasicGenerator.scala:47)
    at RubyCanvasCodegen$.main(RubyCanvasCodegen.scala:21)
    at RubyCanvasCodegen.main(RubyCanvasCodegen.scala)
```
### Expected behavior:

Pandarus should be part of the build process and should work with stable and master.

**Comment by bootstraponline** [comment]
> Pandarus should be part of the build process and should work with stable and master.

I agree. 

> building pandarus is not part of the build process and the API documentation used to generate the API client is badly broken.

That's true. I have an issue open about the [invalid documentation](https://github.com/instructure/canvas-lms/issues/869). Canvas LMS needs to adopt swagger validation as part of the build process. Otherwise Pandarus will keep breaking.

**Comment by simonista** [comment]
Hi @johnnaegle, thanks for reporting the api docs issues.  I've tried to address most of the little things you found, although as you point out here, without a swagger build as part of the normal test process, more things will creep in.

We've been talking a bit about how best to address this, and have the beginnings of a proposal to upgrade to swagger 2.0 and add verification to the test suite, but it's a decent sized project, and I don't have a sense of when it will happen yet, unfortunately.

To date our priority has been to have working and usable api documentation (api.instructure.com), and so that is part of the test suite, but unfortunately working documentation doesn't guarantee working code generation.
