### ISSUE TITLE
npm setup and asset compilation issue

### ISSUE THREAD

**Issue by eriko** [instructure/canvas-lms#920]
### Summary:
Needed to manually install react and react-dom for node to install i18nliner and other packages .
Asset compile still fails Invoke css:compile (first_time)
while following instructions from https://github.com/instructure/canvas-lms/blob/stable/doc/development_with_docker.md

### Steps to reproduce:

 1. docker-compose run --rm web npm install  (this will fail to install i18nliner)
 2. docker-compose run --rm web npm  --no-optional install react
docker-compose run --rm web npm   --no-optional install react-dom
(--no-optional used as fsevents is not compatible with vm)
 3.docker-compose run --rm web bundle exec rake canvas:compile_assets --trace
(error return are listed below

### Additional notes:

Node install error

```
➜  canvas-lms git:(master) ✗ docker-compose run --rm web npm install

> canvas-lms@0.0.0 preinstall /usr/src/app
> script/gem_npm install

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN i18nliner-handlebars@0.2.0 requires a peer of i18nliner@~0.1.5 but none was installed.
npm WARN instructure-icons@0.0.10 requires a peer of react@^0.14.7 || ^15.0.0 but none was installed.
npm WARN instructure-icons@0.0.10 requires a peer of react-dom@^0.14.7 || ^15.0.0 but none was installed.
npm WARN instructure-ui@0.14.4 requires a peer of react@^0.14.7 || ^15.0.0 but none was installed.
npm WARN instructure-ui@0.14.4 requires a peer of react-dom@^0.14.7 || ^15.0.0 but none was installed.
npm WARN react-addons-css-transition-group@15.3.2 requires a peer of react@^15.3.2 but none was installed.
npm WARN react-overlays@0.6.10 requires a peer of react@>=0.14.0 but none was installed.
npm WARN react-overlays@0.6.10 requires a peer of react-dom@>=0.14.0 but none was installed.
npm WARN react-prop-types@0.4.0 requires a peer of react@>=0.14.0 but none was installed.

```
Compilation error
```
➜  canvas-lms git:(master) ✗ docker-compose run --rm web bundle exec rake canvas:compile_assets --trace
** Invoke canvas:compile_assets (first_time)
** Execute canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
node is: /usr/bin/node
 v6.7.0
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
--> Finished: 'Making sure node_modules are up to date' in 21.342605132
** Invoke css:compile (first_time)
** Execute css:compile
--> Starting: 'compile css (including custom brands)'
rake aborted!
Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css
/usr/src/app/lib/brandable_css.rb:267:in `block in run_cli!'
/usr/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
/usr/lib/ruby/2.1.0/open3.rb:188:in `popen2e'
/usr/src/app/lib/brandable_css.rb:253:in `run_cli!'
/usr/src/app/lib/brandable_css.rb:233:in `compile_all!'
/usr/src/app/lib/tasks/css.rake:12:in `block (3 levels) in <top (required)>'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/usr/src/app/lib/tasks/css.rake:12:in `block (2 levels) in <top (required)>'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/usr/src/app/lib/tasks/canvas.rake:126:in `block (2 levels) in <top (required)>'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/docker/.gem/ruby/2.1.0/bin/rake:23:in `load'
/home/docker/.gem/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => css:compile

```

**Comment by eriko** [comment]
Using current Docker for mac install w/ virtual box for vm host and dinghy to run it.

**Comment by tierra** [comment]
how much ram have you given your VM? the whole compile process is a huge resource hog, and tends to get really unreliable with smaller VMs

**Comment by tierra** [comment]
fwiw, I do see the NPM package issue, just not the brandable_css error

**Comment by eriko** [comment]
Does it need more than 4 gigs?
I build it with 
`dinghy create --memory=4096 --cpus=4 --provider=virtualbox
`

**Comment by eriko** [comment]
Oh and this is one the master branch.

**Comment by tierra** [comment]
I think that should be adequate... what if you run just the css compile?
```
docker-compose run --rm web bundle exec rake css:compile
```

**Comment by eriko** [comment]
Basically the same 
```
docker-compose run --rm web bundle exec rake css:compile
--> Starting: 'compile css (including custom brands)'
rake aborted!
Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css
/usr/src/app/lib/brandable_css.rb:267:in `block in run_cli!'
/usr/src/app/lib/brandable_css.rb:253:in `run_cli!'
/usr/src/app/lib/brandable_css.rb:233:in `compile_all!'
/usr/src/app/lib/tasks/css.rake:12:in `block (3 levels) in <top (required)>'
/usr/src/app/lib/tasks/css.rake:12:in `block (2 levels) in <top (required)>'
/home/docker/.gem/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => css:compile
(See full trace by running task with --trace)
```

**Comment by simonista** [comment]
What about running `./node_modules/.bin/brandable_css` directly?

**Comment by simonista** [comment]
er, I guess inside docker `docker-compose run --rm web ./node_modules/.bin/brandable_css`

**Comment by eriko** [comment]
So I rebuilt the containers from scratch and ran 
`docker-compose run --rm web ./node_modules/.bin/brandable_css
`
instead of canvas:compile_assets  and it failed also canvas:compile_assets still fails in the new containers. 

```
docker-compose run --rm web ./node_modules/.bin/brandable_css
compiled bundles/account_admin_tools.scss new_styles_normal_contrast  in 608 ms
compiled bundles/account_course_user_search.scss new_styles_high_contrast  in 960 ms
compiled bundles/account_admin_tools.scss new_styles_high_contrast  in 965 ms
compiled bundles/account_course_user_search.scss new_styles_normal_contrast  in 964 ms
compiled bundles/agenda_view.scss new_styles_high_contrast  in 965 ms
compiled bundles/agenda_view.scss new_styles_normal_contrast  in 968 ms
compiled bundles/alerts.scss new_styles_high_contrast  in 966 ms
compiled bundles/aligned_outcomes.scss new_styles_normal_contrast  in 968 ms
compiled bundles/aligned_outcomes.scss new_styles_high_contrast  in 974 ms
compiled bundles/all_courses.scss new_styles_normal_contrast  in 973 ms
compiled bundles/all_courses.scss new_styles_high_contrast  in 972 ms
compiled bundles/account_settings.scss new_styles_normal_contrast  in 978 ms
compiled bundles/account_settings.scss new_styles_high_contrast  in 977 ms
compiled bundles/alerts.scss new_styles_normal_contrast  in 975 ms
compiled bundles/assignments_edit.scss new_styles_high_contrast  in 969 ms
compiled bundles/assignment_moderation.scss new_styles_normal_contrast  in 971 ms
compiled bundles/assignment_moderation.scss new_styles_high_contrast  in 971 ms
compiled bundles/assignments_edit.scss new_styles_normal_contrast  in 970 ms
compiled bundles/attendance.scss new_styles_high_contrast  in 966 ms
compiled bundles/attendance.scss new_styles_normal_contrast  in 967 ms
compiled bundles/brand_config_index.scss new_styles_high_contrast  in 1301 ms
compiled bundles/brand_config_index.scss new_styles_normal_contrast  in 1303 ms
compiled bundles/assignments.scss new_styles_normal_contrast  in 1314 ms
compiled bundles/assignments.scss new_styles_high_contrast  in 1319 ms
compiled bundles/calendar_appointment_group_edit.scss new_styles_normal_contrast  in 1316 ms
compiled bundles/calendar_appointment_group_edit.scss new_styles_high_contrast  in 1317 ms
compiled bundles/calendar2.scss new_styles_high_contrast  in 1317 ms
compiled bundles/calendar2.scss new_styles_normal_contrast  in 1317 ms
compiled bundles/choose_mastery_path.scss new_styles_normal_contrast  in 1315 ms
compiled bundles/choose_mastery_path.scss new_styles_high_contrast  in 1314 ms
compiled bundles/canvas_quizzes.scss new_styles_normal_contrast  in 1316 ms
compiled bundles/canvas_quizzes.scss new_styles_high_contrast  in 1316 ms
compiled bundles/conferences.scss new_styles_normal_contrast  in 1314 ms
compiled bundles/conferences.scss new_styles_high_contrast  in 1477 ms
compiled bundles/content_migrations.scss new_styles_normal_contrast  in 1478 ms
compiled bundles/content_migrations.scss new_styles_high_contrast  in 1477 ms
compiled bundles/content_next.scss new_styles_normal_contrast  in 1477 ms
compiled bundles/content_next.scss new_styles_high_contrast  in 1477 ms
compiled bundles/context_list.scss new_styles_normal_contrast  in 1476 ms
compiled bundles/context_module_progressions.scss new_styles_normal_contrast  in 1475 ms
compiled bundles/context_list.scss new_styles_high_contrast  in 1477 ms
compiled bundles/context_module_progressions.scss new_styles_high_contrast  in 1477 ms
compiled bundles/context_modules2.scss new_styles_normal_contrast  in 1473 ms
compiled bundles/context_modules2.scss new_styles_high_contrast  in 1472 ms
compiled bundles/course_link_validator.scss new_styles_normal_contrast  in 1472 ms
compiled bundles/course_link_validator.scss new_styles_high_contrast  in 1472 ms
error compiling sass { Error: File to import not found or unreadable: ../../../public/javascripts/vendor/bootstrap-select/bootstrap-select
Parent style sheet: /usr/src/app/app/stylesheets/bundles/conversations_new.scss
    at options.error (/usr/src/app/node_modules/node-sass/lib/index.js:292:26)
  cause: 
   { Error: File to import not found or unreadable: ../../../public/javascripts/vendor/bootstrap-select/bootstrap-select
   Parent style sheet: /usr/src/app/app/stylesheets/bundles/conversations_new.scss
       at options.error (/usr/src/app/node_modules/node-sass/lib/index.js:292:26)
     status: 1,
     file: '/usr/src/app/app/stylesheets/bundles/conversations_new.scss',
     line: 2,
     column: 1,
     message: 'File to import not found or unreadable: ../../../public/javascripts/vendor/bootstrap-select/bootstrap-select\nParent style sheet: /usr/src/app/app/stylesheets/bundles/conversations_new.scss',
     formatted: 'Error: File to import not found or unreadable: ../../../public/javascripts/vendor/bootstrap-select/bootstrap-select\n       Parent style sheet: /usr/src/app/app/stylesheets/bundles/conversations_new.scss\n        on line 2 of app/stylesheets/bundles/conversations_new.scss\n>> @import "../../../public/javascripts/vendor/bootstrap-select/bootstrap-select"\n   ^\n' },
  isOperational: true,
  status: 1,
  file: '/usr/src/app/app/stylesheets/bundles/conversations_new.scss',
  line: 2,
  column: 1,
  formatted: 'Error: File to import not found or unreadable: ../../../public/javascripts/vendor/bootstrap-select/bootstrap-select\n       Parent style sheet: /usr/src/app/app/stylesheets/bundles/conversations_new.scss\n        on line 2 of app/stylesheets/bundles/conversations_new.scss\n>> @import "../../../public/javascripts/vendor/bootstrap-select/bootstrap-select"\n   ^\n' } Error: File to import not found or unreadable: ../../../public/javascripts/vendor/bootstrap-select/bootstrap-select
Parent style sheet: /usr/src/app/app/stylesheets/bundles/conversations_new.scss
    at options.error (/usr/src/app/node_modules/node-sass/lib/index.js:292:26) File to import not found or unreadable: ../../../public/javascripts/vendor/bootstrap-select/bootstrap-select
Parent style sheet: /usr/src/app/app/stylesheets/bundles/conversations_new.scss
```

**Comment by eriko** [comment]
Ok after wiping and git'ing the codebase and rebuilding everything it seems to be working.  It looks like npm installed other stuff so I do not know what happened.
