### ISSUE TITLE
EACCES: Permission denied

### ISSUE THREAD

**Issue by rameshbimarian** [instructure/canvas-lms#923]
### Steps to reproduce:

 1. installed Node js 6.8.0 , ruby 2.1 , ruby 2.1 dev, npm 3.10.8
 2. ran code.sh
 3. code.sh exited with message compile assets manually.
4.  then I ran `bundle exec rake canvas:compile_assets --trace`

### Expected behavior:
Should get compile assets
### Additional notes:
below are the error messages when I ran ` bundle exec rake canvas:compile_assets --trace`
```
 bundle exec rake canvas:compile_assets --trace
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /home/vizzario/canvas-lms/log/development.log
/usr/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
/usr/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/usr/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/usr/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/usr/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/usr/lib/ruby/2.1.0/logger.rb:318:in `new'
/usr/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/var/lib/gems/2.1.0/gems/activesupport-4.0.13/lib/active_support/logger.rb:45:in `initialize'
/home/vizzario/canvas-lms/lib/canvas_logger.rb:12:in `initialize'
/home/vizzario/canvas-lms/config/application.rb:85:in `new'
/home/vizzario/canvas-lms/config/application.rb:85:in `<class:Application>'
/home/vizzario/canvas-lms/config/application.rb:29:in `<module:CanvasRails>'
/home/vizzario/canvas-lms/config/application.rb:28:in `<top (required)>'
/home/vizzario/canvas-lms/Rakefile:4:in `require'
/home/vizzario/canvas-lms/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

```

**Comment by rameshbimarian** [comment]
gracefully we stopped considering canvas integration.
we looked out for another site in discussion with client.

Unfortunately,Canvas is not supporting well for integration of their services. Integration with canvas becoming expensive for us. so we stopped considering canvas
