### ISSUE TITLE
ERROR: zero-length delimited identifier at or near """" LINE 1: ...d_at" = '...

### ISSUE THREAD

**Issue by samuels410** [instructure/canvas-lms#933]
### Summary:

While viewing the file upload submission from SpeedGrader throwing internal server error.

<img width="1277" alt="screen shot 2016-10-26 at 6 58 40 pm" src="https://cloud.githubusercontent.com/assets/3351088/19727980/4a5d1d08-9baf-11e6-9c7f-38fed50c944d.png">
### Steps to reproduce:
1. View a file upload submission as a teacher in speedgrader.
2. Make sure the user object don't have the crocodoc_id in the user table (May be a new teacher).
3. Now its throwing the error: PG::SyntaxError: ERROR:  zero-length delimited identifier at or near """" LINE 1: ...d_at" = '2016-10-26 12:12:02.142280' WHERE "settings"."" = 1
### Additional notes:

Postgres version:
9.3.10
ruby -v:
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux-gnu]

Error report & stack trace:
```
#1584018 ERROR: zero-length delimited identifier at or near """" LINE 1: ...d_at" = '...

account: Greatlearning
category: PG::SyntaxError
created at: 2016-07-30 12:23:35 +0530
request context id: 9e235d96-bc14-4f8a-8858-723a69dc5bbf 
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8 
HTTP_ACCEPT_ENCODING: gzip, deflate, sdch 
HTTP_HOST: mycanvasinstallation.com 
HTTP_REFERER: https://mycanvasinstallation.com/courses/452/assignments/1766/submissions/3711?preview=1&rand=121873 
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36 
PATH_INFO: /api/v1/crocodoc_session 
QUERY_STRING: ?blob=%7B%22user_id%22:10000000003711,%22attachment_id%22:27545,%22type%22:%22crocodoc%22%7D&hmac=953b4b8e07578901a1b0ba0c641bae706ff7cc5b 
REMOTE_ADDR: 163.47.12.5 
REQUEST_METHOD: GET 
REQUEST_URI: https://mycanvasinstallation.com/api/v1/crocodoc_session?blob=%7B%22user_id%22:10000000003711,%22attachment_id%22:27545,%22type%22:%22crocodoc%22%7D&hmac=953b4b8e07578901a1b0ba0c641bae706ff7cc5b 
SERVER_NAME: mycanvasinstallation.com 
SERVER_PORT: 80 
SERVER_PROTOCOL: HTTP/1.1 
format: application/json 
hostname: ip-172-31-48-164 
path_parameters: {:controller=>"crocodoc_sessions", :action=>"show", :format=>"json"} 
pid: 5803 
query_parameters: {"blob"=>"{\"user_id\":10000000003711,\"attachment_id\":27545,\"type\":\"crocodoc\"}", "hmac"=>"953b4b8e07578901a1b0ba0c641bae706ff7cc5b"} 
request_parameters: {} 
response_code: 500 
type: 
```

```
ERROR:  zero-length delimited identifier at or near """"
LINE 1: ...d_at" = '2016-07-30 06:53:35.038983' WHERE "settings"."" = 1
                                                                 ^
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/patches/sql_patches.rb:160:in `exec'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/patches/sql_patches.rb:160:in `async_exec'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in`exec_no_cache'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:157:in `block in exec_delete'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:442:in`block in log'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/sharded_instrumenter.rb:20:in`instrument'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/abstract_adapter.rb:33:in`log'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:156:in `exec_delete'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:103:in`update'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/query_cache.rb:74:in`update'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/persistence.rb:504:in `_update_record'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/locking/optimistic.rb:70:in`_update_record'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_methods/dirty.rb:74:in `_update_record'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:310:in`block in _update_record'
/var/deploy/capistrano/canvas/releases/20160721124040/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:121:in `run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/config/initializers/active_record.rb:1348:in`block in run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:270:in `scoping'
/var/deploy/capistrano/canvas/releases/20160721124040/config/initializers/active_record.rb:1348:in`run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:310:in `_update_record'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/timestamp.rb:70:in`_update_record'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/persistence.rb:481:in `create_or_update'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:302:in`block in create_or_update'
/var/deploy/capistrano/canvas/releases/20160721124040/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:121:in `run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/config/initializers/active_record.rb:1348:in`block in run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:270:in `scoping'
/var/deploy/capistrano/canvas/releases/20160721124040/config/initializers/active_record.rb:1348:in`run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:302:in `create_or_update'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/persistence.rb:125:in`save!'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/validations.rb:57:in `save!'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/attribute_methods/dirty.rb:41:in`save!'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:275:in `block in save!'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:330:in`block in with_transaction_returning_status'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in`transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/base.rb:38:in `block in transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/relation.rb:79:in`activate'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/base.rb:33:in `transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:327:in`with_transaction_returning_status'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:275:in `save!'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/base.rb:108:in`block in save!'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:270:in `scoping'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/base.rb:108:in`save!'
/var/deploy/capistrano/canvas/releases/20160721124040/app/models/user.rb:2612:in `block in crocodoc_id!'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in`block in transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in`transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in `transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/switchman-1.5.2/lib/switchman/active_record/base.rb:46:in`transaction'
/var/deploy/capistrano/canvas/releases/20160721124040/app/models/user.rb:2609:in `crocodoc_id!'
/var/deploy/capistrano/canvas/releases/20160721124040/app/models/user.rb:2620:in`crocodoc_user'
/var/deploy/capistrano/canvas/releases/20160721124040/app/models/crocodoc_document.rb:68:in `session_url'
/var/deploy/capistrano/canvas/releases/20160721124040/app/controllers/crocodoc_sessions_controller.rb:35:in`show'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in`process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:565:in `block (2 levels) in _run__2115546549336060407__process_action__callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in`block in _conditional_callback_around_585'
/var/deploy/capistrano/canvas/releases/20160721124040/app/controllers/application_controller.rb:292:in `block in enable_request_cache'
/var/deploy/capistrano/canvas/releases/20160721124040/lib/temp_cache.rb:7:in`enable'
/var/deploy/capistrano/canvas/releases/20160721124040/app/controllers/application_controller.rb:291:in `enable_request_cache'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in`_conditional_callback_around_585'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:424:in `block in _run__2115546549336060407__process_action__callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:212:in`block in _conditional_callback_around_586'
/var/deploy/capistrano/canvas/releases/20160721124040/app/controllers/application_controller.rb:285:in `set_locale'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:211:in`_conditional_callback_around_586'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:423:in `_run__2115546549336060407__process_action__callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in`run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in`process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in`block in instrument'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in`instrument'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in`process'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiling_methods.rb:79:in`block in profile_method'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in`each'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/gems/plugins/respondus_soap_endpoint/lib/respondus_soap_endpoint/middleware.rb:61:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/etag.rb:23:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/conditionalget.rb:25:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/head.rb:11:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/request_throttle.rb:59:in `block in call'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/request_throttle.rb:257:in`reserve_capacity'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/request_throttle.rb:54:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/request_context_session.rb:25:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:225:in`context'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/encrypted_cookie_store-instructure-1.1.12/lib/encrypted_cookie_store.rb:47:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/sessions_timeout.rb:22:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/load_account.rb:12:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__354613599074578937__call__callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in`run_callbacks'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:22:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/request_context_generator.rb:49:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:21:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/app/middleware/prevent_non_multipart_parse.rb:32:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/runtime.rb:17:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/static.rb:84:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-1.5.4/lib/rack/sendfile.rb:112:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiler.rb:193:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:97:in`call'
/var/deploy/capistrano/canvas/releases/20160721124040/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in`process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in`main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in`block in create_thread_and_abort_on_exception'
```

**Comment by simonista** [comment]
Hey @samuels410, sorry for the lack of response.  are you still having this issue, or did you get it resolved?

**Comment by samuels410** [comment]
@simonista I was fixed this issue, by modify the id column of the settings table as a primary key.

**Comment by simonista** [comment]
Good deal.  strange that it wasn't that way already, but glad you got it worked out!
