### ISSUE TITLE
error ./node_modules/.bin/brandable_css

### ISSUE THREAD

**Issue by Paktusin** [instructure/canvas-lms#951]
Hi everyone. On command 
```
RAILS_ENV=production bundle exec rake canvas:compile_assets
--> Starting: 'Making sure node_modules are up to date'
node is: /usr/bin/node
 v6.9.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
--> Finished: 'Making sure node_modules are up to date' in 11.174331683
--> Starting: 'compile css (including custom brands)'
rake aborted!
Error running BrandableCSS CLI: ./node_modules/.bin/brandable_css
/var/canvas-releases/canvas-lms-release-2016-11-19.04/lib/brandable_css.rb:247:in `block in run_cli!'
/var/canvas-releases/canvas-lms-release-2016-11-19.04/lib/brandable_css.rb:233:in `run_cli!'
/var/canvas-releases/canvas-lms-release-2016-11-19.04/lib/brandable_css.rb:213:in `compile_all!'
/var/canvas-releases/canvas-lms-release-2016-11-19.04/lib/tasks/css.rake:12:in `block (3 levels) in <top (required)>'
/var/canvas-releases/canvas-lms-release-2016-11-19.04/lib/tasks/css.rake:12:in `block (2 levels) in <top (required)>'
/var/canvas-releases/canvas-lms-release-2016-11-19.04/lib/tasks/canvas.rake:50:in `block (2 levels) in <top (required)>'
/var/canvas-releases/canvas-lms-release-2016-11-19.04/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => css:compile
(See full trace by running task with --trace)
```
then i try run ./node_modules/.bin/brandable_css
```
compiled bundles/account_admin_tools.scss new_styles_high_contrast  in 756 ms
compiled bundles/account_admin_tools.scss new_styles_normal_contrast  in 760 ms
compiled bundles/account_course_user_search.scss new_styles_high_contrast  in 753 ms
compiled bundles/account_course_user_search.scss new_styles_normal_contrast  in 754 ms
compiled bundles/account_settings.scss new_styles_normal_contrast  in 751 ms
compiled bundles/agenda_view.scss new_styles_normal_contrast  in 745 ms
compiled bundles/alerts.scss new_styles_normal_contrast  in 742 ms
compiled bundles/aligned_outcomes.scss legacy_normal_contrast  in 739 ms
compiled bundles/aligned_outcomes.scss legacy_high_contrast  in 739 ms
compiled bundles/account_settings.scss new_styles_high_contrast  in 750 ms
compiled bundles/aligned_outcomes.scss new_styles_normal_contrast  in 739 ms
compiled bundles/all_courses.scss legacy_normal_contrast  in 738 ms
compiled bundles/all_courses.scss legacy_high_contrast  in 737 ms
compiled bundles/all_courses.scss new_styles_normal_contrast  in 736 ms
compiled bundles/all_courses.scss new_styles_high_contrast  in 680 ms
compiled bundles/aligned_outcomes.scss new_styles_high_contrast  in 739 ms
compiled bundles/agenda_view.scss new_styles_high_contrast  in 745 ms
compiled bundles/assignment_moderation.scss new_styles_normal_contrast  in 673 ms
compiled bundles/alerts.scss new_styles_high_contrast  in 742 ms
compiled bundles/assignments_edit.scss new_styles_high_contrast  in 673 ms
compiled bundles/assignment_moderation.scss new_styles_high_contrast  in 674 ms
compiled bundles/attendance.scss legacy_normal_contrast  in 663 ms
compiled bundles/assignments_edit.scss new_styles_normal_contrast  in 673 ms
compiled bundles/attendance.scss new_styles_normal_contrast  in 662 ms
compiled bundles/attendance.scss legacy_high_contrast  in 663 ms
compiled bundles/attendance.scss new_styles_high_contrast  in 662 ms
compiled bundles/assignments.scss new_styles_normal_contrast  in 674 ms
error compiling sass { Error: File to import not found or unreadable: variant_variables
Parent style sheet: app/stylesheets/base/_variables.scss
    at options.error (/var/canvas-releases/canvas-lms-release-2016-11-19.04/node_modules/node-sass/lib/index.js:283:26)
  cause: 
   { Error: File to import not found or unreadable: variant_variables
   Parent style sheet: app/stylesheets/base/_variables.scss
       at options.error (/var/canvas-releases/canvas-lms-release-2016-11-19.04/node_modules/node-sass/lib/index.js:283:26)
     status: 1,
     file: 'app/stylesheets/base/_variables.scss',
     line: 14,
     column: 1,
     message: 'File to import not found or unreadable: variant_variables\nParent style sheet: app/stylesheets/base/_variables.scss',
     formatted: 'Error: File to import not found or unreadable: variant_variables\n       Parent style sheet: app/stylesheets/base/_variables.scss\n        on line 14 of app/stylesheets/base/_variables.scss\n>> @import "variant_variables";\n   ^\n' },
  isOperational: true,
  status: 1,
  file: 'app/stylesheets/base/_variables.scss',
  line: 14,
  column: 1,
  formatted: 'Error: File to import not found or unreadable: variant_variables\n       Parent style sheet: app/stylesheets/base/_variables.scss\n        on line 14 of app/stylesheets/base/_variables.scss\n>> @import "variant_variables";\n   ^\n' } Error: File to import not found or unreadable: variant_variables
Parent style sheet: app/stylesheets/base/_variables.scss
    at options.error (/var/canvas-releases/canvas-lms-release-2016-11-19.04/node_modules/node-sass/lib/index.js:283:26) File to import not found or unreadable: variant_variables
Parent style sheet: app/stylesheets/base/_variables.scss
```
error in file app/stylesheets/base/_variables.scss
`@import "variant_variables"`
this imported file in /app/stylesheets/variants/new_styles_high_contrast/_variant_variables.scss
and in /app/stylesheets/variants/new_styles_normal_contrast/_variant_variables.scss

Just next to other import file code _variables.ssss used which are not contained in the folder /app/stylesheets /base/
Any one knows whats wrong ?

**Comment by Paktusin** [comment]
fixing this issue by 
`cp app/stylesheets/variants/new_styles_normal_contrast/_variant_variables.scss app/stylesheets/base/`
